/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/11.0.18
 * Generated at: 2026-03-24 04:36:17 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.util.List;
import java.util.Map;
import java.sql.Timestamp;

public final class admin_002ddashboard_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(4);
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("java.util.Map");
    _jspx_imports_classes.add("java.sql.Timestamp");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ms\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Dashboard Pentadbir - SPPA</title>\r\n");
      out.write("    <style>\r\n");
      out.write("        :root {\r\n");
      out.write("            --brand-blue: #0097d9;\r\n");
      out.write("            --brand-navy: #06344f;\r\n");
      out.write("            --brand-yellow: #fff212;\r\n");
      out.write("            --surface: #ffffff;\r\n");
      out.write("            --surface-soft: #f7fbff;\r\n");
      out.write("            --line: #d9e7f1;\r\n");
      out.write("            --text: #183244;\r\n");
      out.write("            --muted: #637d8d;\r\n");
      out.write("        }\r\n");
      out.write("        * { box-sizing: border-box; }\r\n");
      out.write("        body { margin: 0; font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; background: linear-gradient(180deg, #f4fbff 0%, #f9fcfd 100%); color: var(--text); }\r\n");
      out.write("        .navbar { background: linear-gradient(130deg, var(--brand-navy) 0%, var(--brand-blue) 76%, var(--brand-yellow) 190%); color: white; padding: 16px 28px; display: flex; justify-content: space-between; align-items: center; gap: 20px; }\r\n");
      out.write("        .brand { display: flex; align-items: center; gap: 14px; }\r\n");
      out.write("        .brand-logo { width: 54px; height: 54px; border-radius: 16px; object-fit: contain; padding: 4px; }\r\n");
      out.write("        .brand h1 { margin: 0; font-size: 20px; }\r\n");
      out.write("        .brand p { margin: 2px 0 0; font-size: 12px; opacity: 0.88; }\r\n");
      out.write("        .navbar a { color: white; text-decoration: none; margin-left: 16px; font-weight: 600; }\r\n");
      out.write("        .container { max-width: 1320px; margin: 28px auto; padding: 0 20px 32px; }\r\n");
      out.write("        .hero { display: grid; grid-template-columns: 1.8fr 1fr; gap: 20px; margin-bottom: 20px; }\r\n");
      out.write("        .panel { background: var(--surface); border: 1px solid var(--line); border-radius: 20px; box-shadow: 0 16px 40px rgba(6, 52, 79, 0.08); padding: 22px; }\r\n");
      out.write("        .hero h2 { margin-top: 0; font-size: 30px; }\r\n");
      out.write("        .hero p { color: var(--muted); line-height: 1.7; max-width: 760px; }\r\n");
      out.write("        .metric-strip { display: flex; gap: 10px; flex-wrap: wrap; margin-top: 16px; }\r\n");
      out.write("        .metric-chip { background: var(--surface-soft); border: 1px solid var(--line); padding: 10px 14px; border-radius: 999px; font-weight: 700; }\r\n");
      out.write("        .contact-image { width: 100%; border-radius: 16px; border: 1px solid var(--line); padding: 14px; background: #f7fbff; }\r\n");
      out.write("        .contact-image strong { display: block; margin-bottom: 8px; color: var(--brand-navy); }\r\n");
      out.write("        .contact-image p { margin: 4px 0; color: var(--muted); font-size: 14px; }\r\n");
      out.write("        .stats { display: grid; grid-template-columns: repeat(5, minmax(0, 1fr)); gap: 16px; margin-bottom: 20px; }\r\n");
      out.write("        .stat-card { background: var(--surface); padding: 18px; border-radius: 18px; border: 1px solid var(--line); box-shadow: 0 12px 30px rgba(6, 52, 79, 0.06); }\r\n");
      out.write("        .stat-card h3 { margin: 0 0 8px; font-size: 13px; text-transform: uppercase; letter-spacing: 0.04em; color: var(--muted); }\r\n");
      out.write("        .stat-card .number { font-size: 30px; font-weight: 800; color: var(--brand-navy); }\r\n");
      out.write("        .layout { display: grid; grid-template-columns: 1.9fr 1fr; gap: 20px; }\r\n");
      out.write("        .toolbar { display: grid; grid-template-columns: minmax(240px, 2fr) minmax(160px, 1fr) auto minmax(280px, 1.6fr) auto; gap: 12px; align-items: end; margin-bottom: 16px; }\r\n");
      out.write("        .export-control { min-width: 0; }\r\n");
      out.write("        .export-help { margin-top: 6px; font-size: 12px; color: var(--muted); }\r\n");
      out.write("        .field label { display: block; margin-bottom: 6px; font-size: 13px; font-weight: 700; color: var(--muted); }\r\n");
      out.write("        .field input, .field select { width: 100%; padding: 11px 12px; border-radius: 12px; border: 1px solid var(--line); }\r\n");
      out.write("        .btn { padding: 11px 15px; border-radius: 12px; border: 1px solid #fff; text-decoration: none; font-weight: 700; cursor: pointer; display: inline-flex; align-items: center; justify-content: center; }\r\n");
      out.write("        .btn-primary { background: var(--brand-blue); color: white; }\r\n");
      out.write("        .btn-secondary { background: #dcecf6; color: var(--brand-navy); }\r\n");
      out.write("        .btn-accent { background: #fff7b0; color: #6a5a00; }\r\n");
      out.write("        .section-stack { display: grid; gap: 18px; }\r\n");
      out.write("        .table-card h3 { margin-top: 0; }\r\n");
      out.write("        table { width: 100%; border-collapse: collapse; }\r\n");
      out.write("        th, td { padding: 13px 12px; border-bottom: 1px solid #e4edf4; text-align: left; vertical-align: top; }\r\n");
      out.write("        th { background: #f8fcff; font-size: 13px; text-transform: uppercase; letter-spacing: 0.04em; color: var(--muted); }\r\n");
      out.write("        tr:hover { background: #f7fcff; }\r\n");
      out.write("        .status-pill { display: inline-block; padding: 5px 12px; border-radius: 999px; font-weight: 700; font-size: 12px; }\r\n");
      out.write("        .status-pending { background: #fff3cd; color: #9a6700; }\r\n");
      out.write("        .status-approved { background: #dcfce7; color: #166534; }\r\n");
      out.write("        .status-rejected { background: #fee2e2; color: #b91c1c; }\r\n");
      out.write("        .status-suspended { background: #ffe4d6; color: #9a3412; }\r\n");
      out.write("        .status-draft { background: #e2e8f0; color: #334155; }\r\n");
      out.write("        .subtle { color: var(--muted); font-size: 13px; }\r\n");
      out.write("        .empty { text-align: center; color: var(--muted); padding: 26px 0; }\r\n");
      out.write("        .section-title { margin-top: 0; margin-bottom: 14px; }\r\n");
      out.write("        @media (max-width: 1100px) { .hero, .layout, .stats, .toolbar { grid-template-columns: 1fr; } .navbar { flex-direction: column; align-items: flex-start; } .navbar a { margin-left: 0; margin-right: 16px; } }\r\n");
      out.write("                    /* Enforce visible white border on all clickable buttons */\r\n");
      out.write("        button,\r\n");
      out.write("        input[type=\"submit\"],\r\n");
      out.write("        input[type=\"button\"],\r\n");
      out.write("        .btn,\r\n");
      out.write("        .login-btn,\r\n");
      out.write("        .modal-close,\r\n");
      out.write("        .btn-attachment,\r\n");
      out.write("        .attachment-list button,\r\n");
      out.write("        a.btn {\r\n");
      out.write("            border: 1px solid #fff !important;\r\n");
      out.write("            box-shadow: inset 0 0 0 1px #fff, 0 1px 2px rgba(0, 0, 0, 0.18) !important;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        button:hover,\r\n");
      out.write("        input[type=\"submit\"]:hover,\r\n");
      out.write("        input[type=\"button\"]:hover,\r\n");
      out.write("        .btn:hover,\r\n");
      out.write("        .login-btn:hover,\r\n");
      out.write("        .modal-close:hover,\r\n");
      out.write("        .btn-attachment:hover,\r\n");
      out.write("        .attachment-list button:hover,\r\n");
      out.write("        a.btn:hover,\r\n");
      out.write("        button:focus,\r\n");
      out.write("        input[type=\"submit\"]:focus,\r\n");
      out.write("        input[type=\"button\"]:focus,\r\n");
      out.write("        .btn:focus,\r\n");
      out.write("        .login-btn:focus,\r\n");
      out.write("        .modal-close:focus,\r\n");
      out.write("        .btn-attachment:focus,\r\n");
      out.write("        .attachment-list button:focus,\r\n");
      out.write("        a.btn:focus {\r\n");
      out.write("            border: 1px solid #fff !important;\r\n");
      out.write("            box-shadow: inset 0 0 0 1px #fff, 0 0 0 2px rgba(255, 255, 255, 0.35), 0 1px 2px rgba(0, 0, 0, 0.18) !important;\r\n");
      out.write("        }</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <div class=\"navbar\">\r\n");
      out.write("        <div class=\"brand\">\r\n");
      out.write("            <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/images/logo-jabatan-air-sabah.png?v=4\" class=\"brand-logo\" alt=\"Logo Jabatan Air Sabah\">\r\n");
      out.write("            <div>\r\n");
      out.write("                <h1>Dashboard Pentadbir</h1>\r\n");
      out.write("                <p>Pusat kawalan permohonan, produk, dan laporan SPPA</p>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div>\r\n");
      out.write("            <span>Selamat datang, ");
      out.print( session.getAttribute("username") );
      out.write("</span>\r\n");
      out.write("            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/products\">Senarai Produk</a>\r\n");
      out.write("            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/profile\">Kemaskini Portal</a>\r\n");
      out.write("            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/logout\">Log Keluar</a>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <div class=\"hero\">\r\n");
      out.write("            <div class=\"panel\">\r\n");
      out.write("                <h2>Pemantauan pentadbiran dengan carian, tapisan, dan eksport</h2>\r\n");
      out.write("                <div class=\"metric-strip\">\r\n");
      out.write("                    <div class=\"metric-chip\">Rekod dipaparkan: ");
      out.print( request.getAttribute("filtered_application_count") != null ? request.getAttribute("filtered_application_count") : "0" );
      out.write("</div>\r\n");
      out.write("                    <div class=\"metric-chip\">Produk dalam MySQL: ");
      out.print( request.getAttribute("total_products") != null ? request.getAttribute("total_products") : "0" );
      out.write("</div>\r\n");
      out.write("                    <div class=\"metric-chip\">Pengguna aktif: ");
      out.print( request.getAttribute("active_users") != null ? request.getAttribute("active_users") : "0" );
      out.write("</div>\r\n");
      out.write("                    <div class=\"metric-chip\">Jumlah pengguna berdaftar: ");
      out.print( request.getAttribute("registered_users") != null ? request.getAttribute("registered_users") : "0" );
      out.write("</div>\r\n");
      out.write("                    <div class=\"metric-chip\">Pengguna baharu (30 hari): ");
      out.print( request.getAttribute("new_registered_users") != null ? request.getAttribute("new_registered_users") : "0" );
      out.write("</div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"panel\">\r\n");
      out.write("                <div class=\"contact-image\" aria-label=\"Maklumat hubungan Jabatan Air Sabah\">\r\n");
      out.write("                    <strong>Hubungi JANS</strong>\r\n");
      out.write("                    <p>Telefon: 088-326888</p>\r\n");
      out.write("                    <p>Email: info@jwater.gov.my</p>\r\n");
      out.write("                    <p>Kota Kinabalu, Sabah</p>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"stats\">\r\n");
      out.write("            <div class=\"stat-card\">\r\n");
      out.write("                <h3>Jumlah Permohonan</h3>\r\n");
      out.write("                <div class=\"number\">");
      out.print( request.getAttribute("total_applications") != null ? request.getAttribute("total_applications") : "0" );
      out.write("</div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"stat-card\">\r\n");
      out.write("                <h3>Menunggu</h3>\r\n");
      out.write("                <div class=\"number\">");
      out.print( request.getAttribute("pending_count") != null ? request.getAttribute("pending_count") : "0" );
      out.write("</div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"stat-card\">\r\n");
      out.write("                <h3>Diluluskan</h3>\r\n");
      out.write("                <div class=\"number\">");
      out.print( request.getAttribute("approved_count") != null ? request.getAttribute("approved_count") : "0" );
      out.write("</div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"stat-card\">\r\n");
      out.write("                <h3>Ditolak</h3>\r\n");
      out.write("                <div class=\"number\">");
      out.print( request.getAttribute("rejected_count") != null ? request.getAttribute("rejected_count") : "0" );
      out.write("</div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"stat-card\">\r\n");
      out.write("                <h3>Produk Berdaftar</h3>\r\n");
      out.write("                <div class=\"number\">");
      out.print( request.getAttribute("total_products") != null ? request.getAttribute("total_products") : "0" );
      out.write("</div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"layout\">\r\n");
      out.write("            <div class=\"panel table-card\">\r\n");
      out.write("                <h3 class=\"section-title\">Permohonan Terkini</h3>\r\n");
      out.write("                <form method=\"get\" action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/dashboard\" class=\"toolbar\">\r\n");
      out.write("                    <div class=\"field\">\r\n");
      out.write("                        <label for=\"q\">Carian</label>\r\n");
      out.write("                        <input id=\"q\" name=\"q\" type=\"text\" value=\"");
      out.print( request.getAttribute("search_query") );
      out.write("\" placeholder=\"Cari syarikat, produk, pemohon atau email\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"field\">\r\n");
      out.write("                        <label for=\"status\">Status</label>\r\n");
      out.write("                        <select id=\"status\" name=\"status\">\r\n");
      out.write("                            <option value=\"\">Semua status</option>\r\n");
      out.write("                            <option value=\"PENDING\" ");
      out.print( "PENDING".equals(request.getAttribute("selected_status")) ? "selected" : "" );
      out.write(">PENDING</option>\r\n");
      out.write("                            <option value=\"APPROVED\" ");
      out.print( "APPROVED".equals(request.getAttribute("selected_status")) ? "selected" : "" );
      out.write(">APPROVED</option>\r\n");
      out.write("                            <option value=\"REJECTED\" ");
      out.print( "REJECTED".equals(request.getAttribute("selected_status")) ? "selected" : "" );
      out.write(">REJECTED</option>\r\n");
      out.write("                            <option value=\"SUSPENDED\" ");
      out.print( "SUSPENDED".equals(request.getAttribute("selected_status")) ? "selected" : "" );
      out.write(">SUSPENDED</option>\r\n");
      out.write("                            <option value=\"DRAFT\" ");
      out.print( "DRAFT".equals(request.getAttribute("selected_status")) ? "selected" : "" );
      out.write(">DRAFT</option>\r\n");
      out.write("                        </select>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <button class=\"btn btn-primary\" type=\"submit\">Tapis</button>\r\n");
      out.write("                    <div class=\"field export-control\">\r\n");
      out.write("                        <label for=\"exportOption\">Eksport</label>\r\n");
      out.write("                        <select id=\"exportOption\" name=\"exportOption\">\r\n");
      out.write("                            <optgroup label=\"Ikut penapis semasa\">\r\n");
      out.write("                                <option value=\"xlsx_current\">Excel</option>\r\n");
      out.write("                                <option value=\"pdf_current\">PDF</option>\r\n");
      out.write("                            </optgroup>\r\n");
      out.write("                            <optgroup label=\"Status khusus\">\r\n");
      out.write("                                <option value=\"xlsx_approved\">Excel - APPROVED</option>\r\n");
      out.write("                                <option value=\"xlsx_rejected\">Excel - REJECTED</option>\r\n");
      out.write("                                <option value=\"pdf_approved\">PDF - APPROVED</option>\r\n");
      out.write("                                <option value=\"pdf_rejected\">PDF - REJECTED</option>\r\n");
      out.write("                            </optgroup>\r\n");
      out.write("                        </select>\r\n");
      out.write("                        <div class=\"export-help\">Pilih format dan status, kemudian klik Muat Turun.</div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <button class=\"btn btn-secondary\" type=\"button\" id=\"exportDownloadBtn\">Muat Turun</button>\r\n");
      out.write("                </form>\r\n");
      out.write("\r\n");
      out.write("                <table>\r\n");
      out.write("                    <thead>\r\n");
      out.write("                        <tr>\r\n");
      out.write("                            <th>ID</th>\r\n");
      out.write("                            <th>Nama Syarikat</th>\r\n");
      out.write("                            <th>Kategori Produk</th>\r\n");
      out.write("                            <th>Status</th>\r\n");
      out.write("                            <th>Tarikh Penghantaran</th>\r\n");
      out.write("                            <th>Tindakan</th>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                    </thead>\r\n");
      out.write("                    <tbody>\r\n");
      out.write("                        ");

                            List<Map<String, Object>> applications = (List<Map<String, Object>>) request.getAttribute("pending_applications");
                            if (applications == null || applications.isEmpty()) {
                        
      out.write("\r\n");
      out.write("                        <tr>\r\n");
      out.write("                            <td colspan=\"6\" class=\"empty\">Tiada permohonan ditemui untuk penapis ini.</td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                        ");
 } else {
                            for (Map<String, Object> applicationRow : applications) {
                                Timestamp submittedAt = (Timestamp) applicationRow.get("submitted_at");
                                String status = String.valueOf(applicationRow.get("status")).toLowerCase();
                        
      out.write("\r\n");
      out.write("                        <tr>\r\n");
      out.write("                            <td><strong>#");
      out.print( applicationRow.get("id") );
      out.write("</strong></td>\r\n");
      out.write("                            <td>\r\n");
      out.write("                                <strong>");
      out.print( applicationRow.get("company_name") );
      out.write("</strong><br>\r\n");
      out.write("                                <span class=\"subtle\">Pemohon: ");
      out.print( applicationRow.get("full_name") );
      out.write("<br>Email: ");
      out.print( applicationRow.get("user_email") );
      out.write("</span>\r\n");
      out.write("                            </td>\r\n");
      out.write("                            <td>\r\n");
      out.write("                                <strong>");
      out.print( applicationRow.get("product_category") );
      out.write("</strong><br>\r\n");
      out.write("                                <span class=\"subtle\">");
      out.print( applicationRow.get("product_name") );
      out.write("</span>\r\n");
      out.write("                            </td>\r\n");
      out.write("                            <td><span class=\"status-pill status-");
      out.print( status );
      out.write('"');
      out.write('>');
      out.print( applicationRow.get("status") );
      out.write("</span></td>\r\n");
      out.write("                            <td>");
      out.print( submittedAt != null ? submittedAt.toString() : "Belum dihantar" );
      out.write("</td>\r\n");
      out.write("                            <td>\r\n");
      out.write("                                <a class=\"btn btn-primary\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admin/application?id=");
      out.print( applicationRow.get("id") );
      out.write("\">Semak</a>\r\n");
      out.write("                            </td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                        ");
      }
                           }
                        
      out.write("\r\n");
      out.write("                    </tbody>\r\n");
      out.write("                </table>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div>\r\n");
      out.write("                <div class=\"section-stack\">\r\n");
      out.write("                <div class=\"panel\">\r\n");
      out.write("                    <h3 class=\"section-title\">Pratonton Produk MySQL</h3>\r\n");
      out.write("                    <table>\r\n");
      out.write("                        <thead>\r\n");
      out.write("                            <tr>\r\n");
      out.write("                                <th>No.</th>\r\n");
      out.write("                                <th>Produk</th>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                        </thead>\r\n");
      out.write("                        <tbody>\r\n");
      out.write("                            ");

                                List<Map<String, Object>> products = (List<Map<String, Object>>) request.getAttribute("product_catalog");
                                if (products == null || products.isEmpty()) {
                            
      out.write("\r\n");
      out.write("                            <tr>\r\n");
      out.write("                                <td colspan=\"2\" class=\"empty\">Tiada produk ditemui.</td>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                            ");
 } else {
                                for (Map<String, Object> product : products) {
                            
      out.write("\r\n");
      out.write("                            <tr>\r\n");
      out.write("                                <td>");
      out.print( product.get("no") );
      out.write("</td>\r\n");
      out.write("                                <td>\r\n");
      out.write("                                    <strong>");
      out.print( product.get("product_materials") );
      out.write("</strong><br>\r\n");
      out.write("                                    <span class=\"subtle\">");
      out.print( product.get("brand") == null ? "-" : product.get("brand") );
      out.write(" â€¢ ");
      out.print( product.get("classification") );
      out.write("</span>\r\n");
      out.write("                                </td>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                            ");
      }
                                }
                            
      out.write("\r\n");
      out.write("                        </tbody>\r\n");
      out.write("                    </table>\r\n");
      out.write("                    <div style=\"margin-top:16px;\">\r\n");
      out.write("                        <a class=\"btn btn-secondary\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/products\">Buka Senarai Produk Penuh</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("<script>\r\n");
      out.write("    (function () {\r\n");
      out.write("        var toolbarForm = document.querySelector('.toolbar');\r\n");
      out.write("        var exportButton = document.getElementById('exportDownloadBtn');\r\n");
      out.write("        var exportOption = document.getElementById('exportOption');\r\n");
      out.write("        var searchInput = document.getElementById('q');\r\n");
      out.write("        var statusSelect = document.getElementById('status');\r\n");
      out.write("\r\n");
      out.write("        if (!toolbarForm || !exportButton || !exportOption || !searchInput || !statusSelect) {\r\n");
      out.write("            return;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        var contextPath = '");
      out.print( request.getContextPath() );
      out.write("';\r\n");
      out.write("\r\n");
      out.write("        function statusForSelection(optionValue) {\r\n");
      out.write("            if (optionValue === 'xlsx_approved' || optionValue === 'pdf_approved') {\r\n");
      out.write("                return 'APPROVED';\r\n");
      out.write("            }\r\n");
      out.write("            if (optionValue === 'xlsx_rejected' || optionValue === 'pdf_rejected') {\r\n");
      out.write("                return 'REJECTED';\r\n");
      out.write("            }\r\n");
      out.write("            return statusSelect.value || '';\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        function formatForSelection(optionValue) {\r\n");
      out.write("            return optionValue.indexOf('pdf_') === 0 ? 'pdf' : 'xlsx';\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        exportButton.addEventListener('click', function () {\r\n");
      out.write("            var optionValue = exportOption.value;\r\n");
      out.write("            var format = formatForSelection(optionValue);\r\n");
      out.write("            var status = statusForSelection(optionValue);\r\n");
      out.write("            var q = searchInput.value || '';\r\n");
      out.write("            var url = contextPath + '/admin/export?format=' + encodeURIComponent(format)\r\n");
      out.write("                + '&q=' + encodeURIComponent(q)\r\n");
      out.write("                + '&status=' + encodeURIComponent(status);\r\n");
      out.write("            window.location.href = url;\r\n");
      out.write("        });\r\n");
      out.write("    })();\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
