/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/11.0.18
 * Generated at: 2026-06-10 07:54:24 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.util.Map;
import java.util.Set;
import java.util.LinkedHashSet;

public final class application_002dform_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {


    private String toJs(Object value) {
        if (value == null) {
            return "";
        }
        String s = String.valueOf(value);
        return s.replace("\\", "\\\\")
                .replace("\"", "\\\"")
                .replace("\r", "")
                .replace("\n", "\\n")
                .replace("</", "<\\/");
    }

    private String appValue(Map<String, Object> app, String key) {
        if (app == null || key == null) {
            return "";
        }
        Object value = app.get(key);
        return value == null ? "" : String.valueOf(value);
    }

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(4);
    _jspx_imports_classes.add("java.util.Map");
    _jspx_imports_classes.add("java.util.Set");
    _jspx_imports_classes.add("java.util.LinkedHashSet");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write('\r');
      out.write('\n');

    Map<String, Object> editingApp = (Map<String, Object>) request.getAttribute("application");
    boolean editMode = Boolean.TRUE.equals(request.getAttribute("editMode"));
    boolean renewalMode = Boolean.TRUE.equals(request.getAttribute("renewalMode"));
    Object renewalSourceApplicationId = request.getAttribute("renewalSourceApplicationId");
    String formAction = request.getAttribute("formAction") != null
            ? String.valueOf(request.getAttribute("formAction"))
            : (request.getContextPath() + "/applications/new");
    Set<String> existingDocumentKeys = (Set<String>) request.getAttribute("existingDocumentKeys");
    if (existingDocumentKeys == null) {
        existingDocumentKeys = new LinkedHashSet<>();
    }
    StringBuilder existingDocKeysCsv = new StringBuilder();
    for (String key : existingDocumentKeys) {
        if (existingDocKeysCsv.length() > 0) {
            existingDocKeysCsv.append('|');
        }
        existingDocKeysCsv.append(key);
    }

    String jsApplicationType = toJs(appValue(editingApp, "application_type"));
    String jsSupplierEmail = toJs(appValue(editingApp, "supplier_email"));
    String jsSupplierPhone = toJs(appValue(editingApp, "supplier_phone"));
    String jsSupplierName = toJs(appValue(editingApp, "supplier_name"));
    String jsSupplierAddress = toJs(appValue(editingApp, "supplier_address"));
    String jsManufacturerName = toJs(appValue(editingApp, "manufacturer_name"));
    String jsManufacturerAddress = toJs(appValue(editingApp, "manufacturer_address"));
    String jsManufacturerPhone = toJs(appValue(editingApp, "manufacturer_phone"));
    String jsPrincipalName = toJs(appValue(editingApp, "principal_name"));
    String jsPrincipalAddress = toJs(appValue(editingApp, "principal_address"));
    String jsPrincipalPhone = toJs(appValue(editingApp, "principal_phone"));
    String jsProductCategory = toJs(appValue(editingApp, "product_category"));
    String jsProductName = toJs(appValue(editingApp, "product_name"));
    String jsBrand = toJs(appValue(editingApp, "brand"));
    String jsStandardName = toJs(appValue(editingApp, "standard_name"));
    String jsCertificationLicense = toJs(appValue(editingApp, "certification_license"));
    String jsCertificationValidUntil = toJs(appValue(editingApp, "certification_valid_until"));
    String jsTestReportReference = toJs(appValue(editingApp, "test_report_reference"));
    String jsTestReportDate = toJs(appValue(editingApp, "test_report_date"));
    String jsWarrantyYears = toJs(appValue(editingApp, "warranty_years"));
    String jsProductDescription = toJs(appValue(editingApp, "product_description"));
    String jsProductClass = toJs(appValue(editingApp, "product_class"));
    String jsProductSize = toJs(appValue(editingApp, "product_size"));
    String jsSabahRepName = toJs(appValue(editingApp, "sabah_rep_name"));
    String jsSabahRepAddress = toJs(appValue(editingApp, "sabah_rep_address"));
    String jsSabahRepPhone = toJs(appValue(editingApp, "sabah_rep_phone"));

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ms\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Borang Permohonan Online PPP1 - SPPA</title>\r\n");
      out.write("    <style>\r\n");
      out.write("        * { box-sizing: border-box; }\r\n");
      out.write("        body { font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; margin: 0; background: linear-gradient(180deg, #eff9ff 0%, #f7fbfd 100%); color: #223; }\r\n");
      out.write("        .navbar { background: linear-gradient(130deg, #0F6BAE 0%, #2A9D8F 30%, #6DBE45 58%, #CDE11D 80%, #F2F72E 100%); color: white; padding: 16px 28px; display: flex; justify-content: space-between; align-items: center; gap: 20px; }\r\n");
      out.write("        .brand { display: flex; align-items: center; gap: 14px; }\r\n");
      out.write("        .brand-logo { width: 48px; height: 48px; border-radius: 14px; object-fit: contain; padding: 3px; }\r\n");
      out.write("        .brand strong { display: block; }\r\n");
      out.write("        .brand span { font-size: 12px; opacity: 0.88; }\r\n");
      out.write("        .navbar a { color: white; text-decoration: none; margin-left: 16px; }\r\n");
      out.write("        .container { max-width: 1100px; margin: 28px auto; padding: 0 20px; }\r\n");
      out.write("        .panel { border-radius: 12px; box-shadow: 0 12px 30px rgba(16, 24, 40, 0.08); padding: 24px; margin-bottom: 24px; }\r\n");
      out.write("        .hero { display: grid; grid-template-columns: 2fr 1fr; gap: 20px; }\r\n");
      out.write("        .hero h1 { margin-top: 0; font-size: 30px; }\r\n");
      out.write("        .hero p { color: #556; line-height: 1.6; }\r\n");
      out.write("        .badge { display: inline-block; background: #dbeafe; color: #1d4ed8; border-radius: 999px; padding: 6px 10px; font-size: 12px; font-weight: 600; margin-bottom: 10px; }\r\n");
      out.write("        .docs-box { background: #f8fafc; border: 1px solid #d8e1ee; border-radius: 10px; padding: 16px; }\r\n");
      out.write("        .docs-box a { display: block; color: #0f766e; text-decoration: none; margin-bottom: 8px; }\r\n");
      out.write("        .section-title { margin: 0 0 16px; padding-bottom: 10px; border-bottom: 2px solid #e5e7eb; color: #0f172a; }\r\n");
      out.write("        .grid { display: grid; grid-template-columns: repeat(2, minmax(0, 1fr)); gap: 16px; }\r\n");
      out.write("        .grid-3 { display: grid; grid-template-columns: repeat(3, minmax(0, 1fr)); gap: 16px; }\r\n");
      out.write("        .field { display: flex; flex-direction: column; gap: 6px; }\r\n");
      out.write("        .field label { font-weight: 600; font-size: 14px; color: #334155; }\r\n");
      out.write("        .field input, .field textarea, .field select { width: 100%; padding: 11px 12px; border: 1px solid #cbd5e1; border-radius: 8px; font-size: 14px; }\r\n");
      out.write("        .field textarea { min-height: 110px; resize: vertical; }\r\n");
      out.write("        .field.full { grid-column: 1 / -1; }\r\n");
      out.write("        .hint { font-size: 12px; color: #64748b; }\r\n");
      out.write("        .alert { padding: 14px 16px; border-radius: 8px; margin-bottom: 18px; }\r\n");
      out.write("        .alert.error { background: #fef2f2; color: #b91c1c; }\r\n");
      out.write("        .alert.success { background: #ecfdf5; color: #047857; }\r\n");
      out.write("        .alert-with-gif { display: flex; align-items: center; gap: 10px; }\r\n");
      out.write("        .success-popup {\r\n");
      out.write("            position: fixed;\r\n");
      out.write("            top: 50%;\r\n");
      out.write("            left: 50%;\r\n");
      out.write("            z-index: 1300;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            flex-direction: column;\r\n");
      out.write("            justify-content: center;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            gap: 16px;\r\n");
      out.write("            min-width: 280px;\r\n");
      out.write("            max-width: min(94vw, 420px);\r\n");
      out.write("            padding: 28px 24px;\r\n");
      out.write("            border-radius: 16px;\r\n");
      out.write("            border: 1px solid #b8e7c6;\r\n");
      out.write("            background: #ffffff;\r\n");
      out.write("            color: #166534;\r\n");
      out.write("            font-size: 16px;\r\n");
      out.write("            line-height: 1.35;\r\n");
      out.write("            box-shadow: 0 16px 32px rgba(10, 64, 38, 0.2);\r\n");
      out.write("            transform: translate(-50%, -58%) scale(0.97);\r\n");
      out.write("            opacity: 0;\r\n");
      out.write("            pointer-events: none;\r\n");
      out.write("            transition: transform 0.22s ease, opacity 0.22s ease;\r\n");
      out.write("        }\r\n");
      out.write("        .success-popup.show {\r\n");
      out.write("            transform: translate(-50%, -50%) scale(1);\r\n");
      out.write("            opacity: 1;\r\n");
      out.write("            pointer-events: auto;\r\n");
      out.write("        }\r\n");
      out.write("        .unsuccessful-popup {\r\n");
      out.write("            border: 1px solid #fecaca;\r\n");
      out.write("            background: #fef2f2;\r\n");
      out.write("            color: #991b1b;\r\n");
      out.write("            box-shadow: 0 16px 32px rgba(127, 29, 29, 0.2);\r\n");
      out.write("        }\r\n");
      out.write("        .unsuccessful-title { color: #991b1b; font-size: 20px; line-height: 1.2; font-weight: 800; text-align: center; }\r\n");
      out.write("        .unsuccessful-ok { align-self: center; margin-top: 4px; border: 1px solid #7f1d1d !important; background: #b91c1c; color: #fff; border-radius: 10px; padding: 10px 24px; font-size: 14px; font-weight: 700; cursor: pointer; }\r\n");
      out.write("        .unsuccessful-icon {\r\n");
      out.write("            width: 52px;\r\n");
      out.write("            height: 52px;\r\n");
      out.write("            object-fit: contain;\r\n");
      out.write("            flex-shrink: 0;\r\n");
      out.write("            filter: drop-shadow(0 3px 8px rgba(127, 29, 29, 0.35));\r\n");
      out.write("        }\r\n");
      out.write("        .success-popup-content { display: flex; flex-direction: column; gap: 8px; align-items: center; }\r\n");
      out.write("        .success-title { font-size: 22px; line-height: 1.1; font-weight: 800; color: #0f5132; letter-spacing: 0.02em; text-transform: none; text-align: center; }\r\n");
      out.write("        .success-text { display: none; }\r\n");
      out.write("        .success-ok { align-self: center; margin-top: 4px; border: 1px solid #0f5132 !important; background: #166534; color: #fff; border-radius: 10px; padding: 10px 24px; font-size: 14px; font-weight: 700; cursor: pointer; }\r\n");
      out.write("        .success-gif {\r\n");
      out.write("            width: 84px;\r\n");
      out.write("            height: 84px;\r\n");
      out.write("            padding: 0;\r\n");
      out.write("            object-fit: contain;\r\n");
      out.write("            flex-shrink: 0;\r\n");
      out.write("            background: transparent;\r\n");
      out.write("            border-radius: 0;\r\n");
      out.write("            border: none;\r\n");
      out.write("            mix-blend-mode: normal;\r\n");
      out.write("            filter: drop-shadow(0 3px 8px rgba(22, 101, 52, 0.22)) saturate(1.05);\r\n");
      out.write("            transform-origin: center;\r\n");
      out.write("            animation: successGifPop 420ms ease-out 1, successGifPulse 1.9s ease-in-out infinite 520ms;\r\n");
      out.write("        }\r\n");
      out.write("        @keyframes successGifPop {\r\n");
      out.write("            0% { transform: scale(0.72) translateY(3px); opacity: 0.65; }\r\n");
      out.write("            70% { transform: scale(1.14) translateY(-1px); opacity: 1; }\r\n");
      out.write("            100% { transform: scale(1); opacity: 1; }\r\n");
      out.write("        }\r\n");
      out.write("        @keyframes successGifPulse {\r\n");
      out.write("            0%, 100% { transform: scale(1); }\r\n");
      out.write("            50% { transform: scale(1.06); }\r\n");
      out.write("        }\r\n");
      out.write("        .doc-list { display: grid; grid-template-columns: repeat(2, minmax(0, 1fr)); gap: 14px; }\r\n");
      out.write("        .doc-item { padding: 14px; border: 1px solid #dbe2ea; border-radius: 10px; background: #fcfdff; }\r\n");
      out.write("        .doc-item strong { display: block; margin-bottom: 8px; font-size: 14px; }\r\n");
      out.write("        .doc-item strong .required-mark { color: #b91c1c; margin-left: 4px; }\r\n");
      out.write("        .product-array-wrap { display: grid; gap: 10px; margin-bottom: 10px; }\r\n");
      out.write("        .product-array-head { display: flex; align-items: center; gap: 10px; flex-wrap: wrap; }\r\n");
      out.write("        .product-array-list { display: grid; gap: 10px; }\r\n");
      out.write("        .product-item { border: 1px solid #dbe2ea; border-radius: 10px; padding: 12px; background: #fcfdff; }\r\n");
      out.write("        .product-item-title { font-size: 13px; font-weight: 700; color: #0f172a; margin-bottom: 10px; }\r\n");
      out.write("        .product-item-actions { margin-top: 8px; display: flex; justify-content: flex-end; }\r\n");
      out.write("        .product-array-foot { margin-top: 12px; display: flex; justify-content: flex-start; }\r\n");
      out.write("        .btn.btn-add-product {\r\n");
      out.write("            display: inline-flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            gap: 8px;\r\n");
      out.write("            font-weight: 800;\r\n");
      out.write("            font-size: 13px;\r\n");
      out.write("            padding: 9px 14px;\r\n");
      out.write("            border-radius: 8px;\r\n");
      out.write("            background: #0F6BAE;\r\n");
      out.write("            color: #ffffff;\r\n");
      out.write("            border: 1px solid #0b4f81 !important;\r\n");
      out.write("            box-shadow: 0 4px 12px rgba(15, 107, 174, 0.28);\r\n");
      out.write("        }\r\n");
      out.write("        .btn.btn-add-product:hover,\r\n");
      out.write("        .btn.btn-add-product:focus {\r\n");
      out.write("            background: #0b5b94;\r\n");
      out.write("            color: #ffffff;\r\n");
      out.write("            transform: translateY(-1px);\r\n");
      out.write("        }\r\n");
      out.write("        .btn-add-product img { width: 16px; height: 16px; object-fit: contain; }\r\n");
      out.write("        .btn-remove-product { background: #fee2e2; color: #991b1b; border-color: #fecaca !important; }\r\n");
      out.write("        .actions { display: flex; gap: 12px; justify-content: flex-end; margin-top: 20px; }\r\n");
      out.write("        .btn { border: 1px solid #fff; border-radius: 8px; padding: 12px 18px; font-size: 14px; cursor: pointer; text-decoration: none; }\r\n");
      out.write("        .btn-secondary { background: #e2e8f0; color: #1e293b; }\r\n");
      out.write("        .btn-primary { background: linear-gradient(135deg, #0F6BAE 0%, #2A9D8F 45%, #6DBE45 100%); color: white; }\r\n");
      out.write("        .contact-card { width: 100%; max-width: 420px; border-radius: 12px; border: 1px solid #d8e1ee; background: #f8fbff; padding: 14px; color: #475569; }\r\n");
      out.write("        .contact-card strong { display: block; margin-bottom: 8px; color: #0f172a; }\r\n");
      out.write("        .contact-card p { margin: 4px 0; }\r\n");
      out.write("        .jans-contact-section { margin-top: 10px; border: 1px solid #d6e5ef; border-radius: 14px; background: #f8fcff; padding: 12px; }\r\n");
      out.write("        .jans-contact-section h3 { margin: 0 0 10px; color: #0f6bae; font-size: 16px; font-weight: 700; letter-spacing: 0; }\r\n");
      out.write("        .jans-contact-section .contact-line { display: flex; align-items: flex-start; gap: 8px; margin: 7px 0; color: #4e6a7c; font-size: 13px; line-height: 1.45; min-width: 0; }\r\n");
      out.write("        .jans-contact-section .contact-icon { display: inline-block; width: 10px; height: 10px; background: #0f6bae; border-radius: 2px; flex-shrink: 0; margin-top: 2px; }\r\n");
      out.write("        .jans-contact-section .contact-line span { line-height: 1.45; }\r\n");
      out.write("        @media (max-width: 900px) { .hero, .grid, .grid-3, .doc-list { grid-template-columns: 1fr; } }\r\n");
      out.write("                    /* Enforce visible white border on all clickable buttons */\r\n");
      out.write("        button,\r\n");
      out.write("        input[type=\"submit\"],\r\n");
      out.write("        input[type=\"button\"],\r\n");
      out.write("        .btn,\r\n");
      out.write("        .login-btn,\r\n");
      out.write("        .modal-close,\r\n");
      out.write("        .btn-attachment,\r\n");
      out.write("        .attachment-list button,\r\n");
      out.write("        a.btn {\r\n");
      out.write("            border: 1px solid #fff !important;\r\n");
      out.write("            box-shadow: inset 0 0 0 1px #fff, 0 1px 2px rgba(0, 0, 0, 0.18) !important;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        button:hover,\r\n");
      out.write("        input[type=\"submit\"]:hover,\r\n");
      out.write("        input[type=\"button\"]:hover,\r\n");
      out.write("        .btn:hover,\r\n");
      out.write("        .login-btn:hover,\r\n");
      out.write("        .modal-close:hover,\r\n");
      out.write("        .btn-attachment:hover,\r\n");
      out.write("        .attachment-list button:hover,\r\n");
      out.write("        a.btn:hover,\r\n");
      out.write("        button:focus,\r\n");
      out.write("        input[type=\"submit\"]:focus,\r\n");
      out.write("        input[type=\"button\"]:focus,\r\n");
      out.write("        .btn:focus,\r\n");
      out.write("        .login-btn:focus,\r\n");
      out.write("        .modal-close:focus,\r\n");
      out.write("        .btn-attachment:focus,\r\n");
      out.write("        .attachment-list button:focus,\r\n");
      out.write("        a.btn:focus {\r\n");
      out.write("            border: 1px solid #fff !important;\r\n");
      out.write("            box-shadow: inset 0 0 0 1px #fff, 0 0 0 2px rgba(255, 255, 255, 0.35), 0 1px 2px rgba(0, 0, 0, 0.18) !important;\r\n");
      out.write("        }\r\n");
      out.write("        .icon-inline { width: 20px; height: 20px; object-fit: contain; vertical-align: middle; }\r\n");
      out.write("        .icon-link { width: 40px; height: 40px; display: inline-flex; align-items: center; justify-content: center; border-radius: 999px; background: rgba(255,255,255,0.15); border: 1px solid rgba(255,255,255,0.38); transition: transform 0.18s ease, background 0.18s ease; text-decoration: none; margin-left: 4px; }\r\n");
      out.write("        .icon-link img { width: 20px; height: 20px; object-fit: contain; }\r\n");
      out.write("        .icon-link:hover { transform: translateY(-1px) scale(1.03); background: rgba(255,255,255,0.26); }\r\n");
      out.write("    </style>\r\n");
      out.write("<body>\r\n");
      out.write("    <div class=\"navbar\">\r\n");
      out.write("        <div class=\"brand\">\r\n");
      out.write("            <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/images/logo-jabatan-air-sabah.png?v=4\" class=\"brand-logo\" alt=\"Logo Jabatan Air Sabah\">\r\n");
      out.write("            <div>\r\n");
      out.write("                <strong>SPPA - Permohonan Online PPP1</strong>\r\n");
      out.write("                <span>Jabatan Air Negeri Sabah</span>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div>\r\n");
      out.write("            <a class=\"icon-link\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/dashboard\" title=\"Kembali ke Dashboard\" aria-label=\"Kembali ke Dashboard\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/icon/dashboard.png\" alt=\"Dashboard\"></a>\r\n");
      out.write("            <a class=\"icon-link\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/\" title=\"Laman Utama\" aria-label=\"Laman Utama\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/images/home.png\" alt=\"Home\"></a>\r\n");
      out.write("            <a class=\"icon-link\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/logout\" title=\"Log Keluar\" aria-label=\"Log Keluar\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/images/Logout.png\" alt=\"Log Keluar\"></a>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        ");
 if (request.getAttribute("error") != null) { 
      out.write("\r\n");
      out.write("            <div class=\"alert error\">");
      out.print( request.getAttribute("error") );
      out.write("</div>\r\n");
      out.write("        ");
 } 
      out.write("\r\n");
      out.write("        ");
 if (request.getParameter("success") != null) { 
      out.write("\r\n");
      out.write("            <div id=\"successPopup\" class=\"success-popup show\" role=\"dialog\" aria-live=\"polite\" aria-label=\"Notifikasi berjaya\">\r\n");
      out.write("                <img class=\"success-gif\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/images/success.png\" alt=\"Berjaya\">\r\n");
      out.write("                <div class=\"success-popup-content\">\r\n");
      out.write("                    <div class=\"success-title\">Berjaya!</div>\r\n");
      out.write("                    <div class=\"success-text\"></div>\r\n");
      out.write("                    <button type=\"button\" class=\"success-ok\" data-close-success-popup>OK</button>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        ");
 } 
      out.write("\r\n");
      out.write("        <div id=\"unsuccessfulPopup\" class=\"success-popup unsuccessful-popup\" role=\"dialog\" aria-live=\"polite\" aria-label=\"Notifikasi gagal\">\r\n");
      out.write("            <img class=\"unsuccessful-icon\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/images/unsuccessful.png\" alt=\"Tidak berjaya\">\r\n");
      out.write("            <div class=\"success-popup-content\">\r\n");
      out.write("                <div class=\"unsuccessful-title\">Tidak Berjaya Sila Lengkapkan Dokumen yang diperlukan!</div>\r\n");
      out.write("                <button type=\"button\" class=\"unsuccessful-ok\" data-close-unsuccessful-popup>OK</button>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"panel hero\">\r\n");
      out.write("            <div>\r\n");
      out.write("                <span class=\"badge\">PPP1 + PPP2 + Garis Panduan JANS</span>\r\n");
      out.write("                <h1>Borang Permohonan Pendaftaran Pembekal dan Produk Bekalan Air</h1>\r\n");
      out.write("                <p>\r\n");
      out.write("                    Borang online ini menggantikan pengisian manual PPP1. Pemohon perlu mengisi maklumat pembekal, produk,\r\n");
      out.write("                    dan sokongan teknikal dengan lengkap, kemudian memuat naik dokumen sokongan dalam format PDF mengikut PPP2\r\n");
      out.write("                    dan garis panduan pendaftaran pembekal dan produk bekalan air.\r\n");
      out.write("                </p>\r\n");
      out.write("                <p>\r\n");
      out.write("                    Permohonan baharu dan pembaharuan kedua-duanya disokong. Untuk pembaharuan, sijil/perakuan lama JANS perlu\r\n");
      out.write("                    dilampirkan dan pembaharuan perlu dibuat sekurang-kurangnya enam bulan sebelum tarikh tamat.\r\n");
      out.write("                </p>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"docs-box\">\r\n");
      out.write("                <strong>Rujukan Asal</strong>\r\n");
      out.write("                <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/forms/borang-ppp1-permohonan-pendaftaran-pembekal-produk_0.pdf\" target=\"_blank\">Borang PPP1</a>\r\n");
      out.write("                <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/forms/borang-ppp2-senarai-semak-pendaftaran-pembekal-produk_0.pdf\" target=\"_blank\">Senarai Semak PPP2</a>\r\n");
      out.write("                <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/forms/garis-panduan-pendaftaran-pembekal-dan-produk-bekalan-air.pdf\" target=\"_blank\">Garis Panduan Pendaftaran</a>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <form id=\"applicationForm\" class=\"panel\" method=\"post\" action=\"");
      out.print( formAction );
      out.write("\" enctype=\"multipart/form-data\">\r\n");
      out.write("            <input type=\"hidden\" name=\"_csrf\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${csrf_token}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("            <input type=\"hidden\" id=\"existingDocKeysCsv\" value=\"");
      out.print( toJs(existingDocKeysCsv.toString()) );
      out.write("\">\r\n");
      out.write("            ");
 if (renewalSourceApplicationId != null) { 
      out.write("\r\n");
      out.write("            <input type=\"hidden\" name=\"renew_from_application_id\" value=\"");
      out.print( renewalSourceApplicationId );
      out.write("\">\r\n");
      out.write("            ");
 } 
      out.write("\r\n");
      out.write("            ");
 if (editMode) { 
      out.write("\r\n");
      out.write("            <div class=\"alert success\">Mod kemaskini permohonan. Maklumat boleh dikemaskini dan dihantar semula.</div>\r\n");
      out.write("            ");
 } else if (renewalMode) { 
      out.write("\r\n");
      out.write("            <div class=\"alert success\">Permohonan ini ialah pembaharuan daripada rekod yang telah diluluskan. Dokumen lama akan digunakan semula dan anda hanya perlu memuat naik lampiran pembaharuan yang baharu.</div>\r\n");
      out.write("            ");
 } 
      out.write("\r\n");
      out.write("            <h2 class=\"section-title\">Bahagian A: Maklumat Pembekal / Pembuat / Prinsipal</h2>\r\n");
      out.write("            <div class=\"grid-3\">\r\n");
      out.write("                <div class=\"field\">\r\n");
      out.write("                    <label for=\"application_type\">Jenis Permohonan</label>\r\n");
      out.write("                    <select id=\"application_type\" name=\"application_type\" required>\r\n");
      out.write("                        <option value=\"\">Pilih</option>\r\n");
      out.write("                        <option value=\"BAHARU\" ");
      out.print( "BAHARU".equals(appValue(editingApp, "application_type")) ? "selected" : "" );
      out.write(">Baharu</option>\r\n");
      out.write("                        <option value=\"PEMBAHARUAN\" ");
      out.print( "PEMBAHARUAN".equals(appValue(editingApp, "application_type")) ? "selected" : "" );
      out.write(">Pembaharuan</option>\r\n");
      out.write("                    </select>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"field\">\r\n");
      out.write("                    <label for=\"supplier_email\">Email Pembekal</label>\r\n");
      out.write("                    <input id=\"supplier_email\" name=\"supplier_email\" type=\"email\" placeholder=\"contoh@syarikat.com\" value=\"");
      out.print( appValue(editingApp, "supplier_email") );
      out.write("\" />\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"field\">\r\n");
      out.write("                    <label for=\"supplier_phone\">No. Telefon Pembekal</label>\r\n");
      out.write("                    <input id=\"supplier_phone\" name=\"supplier_phone\" type=\"text\" placeholder=\"088-123456\" value=\"");
      out.print( appValue(editingApp, "supplier_phone") );
      out.write("\" />\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"grid\">\r\n");
      out.write("                <div class=\"field full\">\r\n");
      out.write("                    <label for=\"supplier_name\">Nama Syarikat Pembekal</label>\r\n");
      out.write("                    <input id=\"supplier_name\" name=\"supplier_name\" type=\"text\" required value=\"");
      out.print( appValue(editingApp, "supplier_name") );
      out.write("\" />\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"field full\">\r\n");
      out.write("                    <label for=\"supplier_address\">Alamat Pejabat Pembekal</label>\r\n");
      out.write("                    <textarea id=\"supplier_address\" name=\"supplier_address\" required>");
      out.print( appValue(editingApp, "supplier_address") );
      out.write("</textarea>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"field full\">\r\n");
      out.write("                    <label for=\"manufacturer_name\">Nama Syarikat Pembuat / Pengilang</label>\r\n");
      out.write("                    <input id=\"manufacturer_name\" name=\"manufacturer_name\" type=\"text\" value=\"");
      out.print( appValue(editingApp, "manufacturer_name") );
      out.write("\" />\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"field full\">\r\n");
      out.write("                    <label for=\"manufacturer_address\">Alamat Pejabat Pembuat / Pengilang</label>\r\n");
      out.write("                    <textarea id=\"manufacturer_address\" name=\"manufacturer_address\">");
      out.print( appValue(editingApp, "manufacturer_address") );
      out.write("</textarea>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"field\">\r\n");
      out.write("                    <label for=\"manufacturer_phone\">No. Telefon Pengilang</label>\r\n");
      out.write("                    <input id=\"manufacturer_phone\" name=\"manufacturer_phone\" type=\"text\" value=\"");
      out.print( appValue(editingApp, "manufacturer_phone") );
      out.write("\" />\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"field\"></div>\r\n");
      out.write("                <div class=\"field full\">\r\n");
      out.write("                    <label for=\"principal_name\">Nama Syarikat Prinsipal / Pemilik Produk</label>\r\n");
      out.write("                    <input id=\"principal_name\" name=\"principal_name\" type=\"text\" value=\"");
      out.print( appValue(editingApp, "principal_name") );
      out.write("\" />\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"field full\">\r\n");
      out.write("                    <label for=\"principal_address\">Alamat Pejabat Prinsipal / Pemilik Produk</label>\r\n");
      out.write("                    <textarea id=\"principal_address\" name=\"principal_address\">");
      out.print( appValue(editingApp, "principal_address") );
      out.write("</textarea>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"field\">\r\n");
      out.write("                    <label for=\"principal_phone\">No. Telefon Prinsipal</label>\r\n");
      out.write("                    <input id=\"principal_phone\" name=\"principal_phone\" type=\"text\" value=\"");
      out.print( appValue(editingApp, "principal_phone") );
      out.write("\" />\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <h2 class=\"section-title\">Bahagian B: Maklumat Produk</h2>\r\n");
      out.write("            <div class=\"product-array-wrap\">\r\n");
      out.write("                <div class=\"product-array-head\">\r\n");
      out.write("                    <span class=\"hint\">Pemohon boleh mohon lebih daripada satu produk.</span>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div id=\"productArrayList\" class=\"product-array-list\">\r\n");
      out.write("                    <div class=\"product-item\" data-product-item>\r\n");
      out.write("                        <div class=\"product-item-title\">Produk 1</div>\r\n");
      out.write("                        <div class=\"grid-3\">\r\n");
      out.write("                            <div class=\"field\">\r\n");
      out.write("                                <label for=\"product_category_1\">Kategori Produk</label>\r\n");
      out.write("                                <select id=\"product_category_1\" name=\"product_category[]\" required>\r\n");
      out.write("                                    <option value=\"\">Pilih kategori</option>\r\n");
      out.write("                                    <option value=\"Water Treatment Equipment\" ");
      out.print( "Water Treatment Equipment".equals(appValue(editingApp, "product_category")) ? "selected" : "" );
      out.write(">Water Treatment Equipment</option>\r\n");
      out.write("                                    <option value=\"Conveyance Of Water\" ");
      out.print( "Conveyance Of Water".equals(appValue(editingApp, "product_category")) ? "selected" : "" );
      out.write(">Conveyance Of Water</option>\r\n");
      out.write("                                    <option value=\"Flow Control\" ");
      out.print( "Flow Control".equals(appValue(editingApp, "product_category")) ? "selected" : "" );
      out.write(">Flow Control</option>\r\n");
      out.write("                                    <option value=\"Measuring Device\" ");
      out.print( "Measuring Device".equals(appValue(editingApp, "product_category")) ? "selected" : "" );
      out.write(">Measuring Device</option>\r\n");
      out.write("                                    <option value=\"Chemical For Water Treatment\" ");
      out.print( "Chemical For Water Treatment".equals(appValue(editingApp, "product_category")) ? "selected" : "" );
      out.write(">Chemical For Water Treatment</option>\r\n");
      out.write("                                    <option value=\"Storage Of Water\" ");
      out.print( "Storage Of Water".equals(appValue(editingApp, "product_category")) ? "selected" : "" );
      out.write(">Storage Of Water</option>\r\n");
      out.write("                                    <option value=\"Sanitary\" ");
      out.print( "Sanitary".equals(appValue(editingApp, "product_category")) ? "selected" : "" );
      out.write(">Sanitary</option>\r\n");
      out.write("                                    <option value=\"Lining\" ");
      out.print( "Lining".equals(appValue(editingApp, "product_category")) ? "selected" : "" );
      out.write(">Lining</option>\r\n");
      out.write("                                    <option value=\"Coating\" ");
      out.print( "Coating".equals(appValue(editingApp, "product_category")) ? "selected" : "" );
      out.write(">Coating</option>\r\n");
      out.write("                                    <option value=\"Waterproofing\" ");
      out.print( "Waterproofing".equals(appValue(editingApp, "product_category")) ? "selected" : "" );
      out.write(">Waterproofing</option>\r\n");
      out.write("                                    <option value=\"Sealant\" ");
      out.print( "Sealant".equals(appValue(editingApp, "product_category")) ? "selected" : "" );
      out.write(">Sealant</option>\r\n");
      out.write("                                    <option value=\"Adhesive\" ");
      out.print( "Adhesive".equals(appValue(editingApp, "product_category")) ? "selected" : "" );
      out.write(">Adhesive</option>\r\n");
      out.write("                                    <option value=\"Solvent Cement\" ");
      out.print( "Solvent Cement".equals(appValue(editingApp, "product_category")) ? "selected" : "" );
      out.write(">Solvent Cement</option>\r\n");
      out.write("                                </select>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"field\">\r\n");
      out.write("                                <label for=\"product_name_1\">Nama Produk</label>\r\n");
      out.write("                                <input id=\"product_name_1\" name=\"product_name[]\" type=\"text\" required value=\"");
      out.print( appValue(editingApp, "product_name") );
      out.write("\" />\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"field\">\r\n");
      out.write("                                <label for=\"brand_1\">Jenama</label>\r\n");
      out.write("                                <input id=\"brand_1\" name=\"brand[]\" type=\"text\" required value=\"");
      out.print( appValue(editingApp, "brand") );
      out.write("\" />\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"field\">\r\n");
      out.write("                                <label for=\"standard_name_1\">Piawaian / Standard</label>\r\n");
      out.write("                                <input id=\"standard_name_1\" name=\"standard_name[]\" type=\"text\" placeholder=\"MS / BS / ISO / lain-lain\" required value=\"");
      out.print( appValue(editingApp, "standard_name") );
      out.write("\" />\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"field\">\r\n");
      out.write("                                <label for=\"certification_license_1\">Badan Persijilan & No. Lesen</label>\r\n");
      out.write("                                <input id=\"certification_license_1\" name=\"certification_license[]\" type=\"text\" required value=\"");
      out.print( appValue(editingApp, "certification_license") );
      out.write("\" />\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"field\">\r\n");
      out.write("                                <label for=\"certification_valid_until_1\">Sah Sehingga</label>\r\n");
      out.write("                                <input id=\"certification_valid_until_1\" name=\"certification_valid_until[]\" type=\"date\" required value=\"");
      out.print( appValue(editingApp, "certification_valid_until") );
      out.write("\" />\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"field\">\r\n");
      out.write("                                <label for=\"test_report_reference_1\">Badan Persijilan & No. Laporan Pengujian</label>\r\n");
      out.write("                                <input id=\"test_report_reference_1\" name=\"test_report_reference[]\" type=\"text\" required value=\"");
      out.print( appValue(editingApp, "test_report_reference") );
      out.write("\" />\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"field\">\r\n");
      out.write("                                <label for=\"test_report_date_1\">Tarikh Laporan Pengujian</label>\r\n");
      out.write("                                <input id=\"test_report_date_1\" name=\"test_report_date[]\" type=\"date\" required value=\"");
      out.print( appValue(editingApp, "test_report_date") );
      out.write("\" />\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"field\">\r\n");
      out.write("                                <label for=\"warranty_years_1\">Tempoh Jaminan Produk (Tahun)</label>\r\n");
      out.write("                                <input id=\"warranty_years_1\" name=\"warranty_years[]\" type=\"number\" step=\"0.1\" min=\"0\" required value=\"");
      out.print( appValue(editingApp, "warranty_years") );
      out.write("\" />\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"field full\">\r\n");
      out.write("                                <label for=\"product_description_1\">Perihal Produk</label>\r\n");
      out.write("                                <textarea id=\"product_description_1\" name=\"product_description[]\" required>");
      out.print( appValue(editingApp, "product_description") );
      out.write("</textarea>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"field\">\r\n");
      out.write("                                <label for=\"product_class_1\">Class Produk</label>\r\n");
      out.write("                                <input id=\"product_class_1\" name=\"product_class[]\" type=\"text\" placeholder=\"Contoh: Class C\" value=\"");
      out.print( appValue(editingApp, "product_class") );
      out.write("\" />\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"field\">\r\n");
      out.write("                                <label for=\"product_size_1\">Saiz Produk</label>\r\n");
      out.write("                                <input id=\"product_size_1\" name=\"product_size[]\" type=\"text\" placeholder=\"Contoh: DN100\" value=\"");
      out.print( appValue(editingApp, "product_size") );
      out.write("\" />\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"product-item-actions\">\r\n");
      out.write("                            <button type=\"button\" class=\"btn btn-remove-product\" data-remove-product hidden>Buang</button>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"product-array-foot\">\r\n");
      out.write("                <button type=\"button\" id=\"addProductBtn\" class=\"btn btn-add-product\" aria-label=\"Tambah produk baharu\">\r\n");
      out.write("                    <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/icon/add-new.png\" alt=\"Tambah produk baharu\">\r\n");
      out.write("                    Add New\r\n");
      out.write("                </button>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <h2 class=\"section-title\">Bahagian C: Sokongan Teknikal di Negeri Sabah</h2>\r\n");
      out.write("            <div class=\"grid\">\r\n");
      out.write("                <div class=\"field\">\r\n");
      out.write("                    <label for=\"sabah_rep_name\">Nama Wakil di Sabah</label>\r\n");
      out.write("                    <input id=\"sabah_rep_name\" name=\"sabah_rep_name\" type=\"text\" value=\"");
      out.print( appValue(editingApp, "sabah_rep_name") );
      out.write("\" />\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"field\">\r\n");
      out.write("                    <label for=\"sabah_rep_phone\">No. Telefon Wakil</label>\r\n");
      out.write("                    <input id=\"sabah_rep_phone\" name=\"sabah_rep_phone\" type=\"text\" value=\"");
      out.print( appValue(editingApp, "sabah_rep_phone") );
      out.write("\" />\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"field full\">\r\n");
      out.write("                    <label for=\"sabah_rep_address\">Alamat Pejabat Wakil di Sabah</label>\r\n");
      out.write("                    <textarea id=\"sabah_rep_address\" name=\"sabah_rep_address\">");
      out.print( appValue(editingApp, "sabah_rep_address") );
      out.write("</textarea>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <h2 class=\"section-title\">Bahagian D: Dokumen Sokongan (PPP2)</h2>\r\n");
      out.write("                <p class=\"hint\">");
      out.print( renewalMode
                    ? "Dokumen sedia ada daripada permohonan yang telah diluluskan akan digunakan semula. Muat naik semula hanya jika anda mahu menggantikan dokumen tersebut. Lampiran sijil/perakuan lama JANS untuk pembaharuan masih wajib jika belum pernah dimuat naik."
                    : "Muat naik dokumen dalam format PDF. Untuk pembaharuan, lampiran sijil/perakuan lama adalah wajib. Medan 'jika ada' boleh dibiarkan kosong." );
      out.write("</p>\r\n");
      out.write("            <div class=\"doc-list\">\r\n");
      out.write("                ");
 Map<String, String> requiredDocuments = (Map<String, String>) request.getAttribute("requiredDocuments");
                   java.util.Set<String> mandatoryDocKeys = new java.util.HashSet<>();
                   mandatoryDocKeys.add("official_application_letter");
                   mandatoryDocKeys.add("principal_appointment_letter");
                   mandatoryDocKeys.add("certification_license_file");
                   mandatoryDocKeys.add("test_report_file");
                   mandatoryDocKeys.add("brochure_catalogue");
                   mandatoryDocKeys.add("price_list");
                   mandatoryDocKeys.add("product_benefit_summary");
                   mandatoryDocKeys.add("project_reference");
                   mandatoryDocKeys.add("sop_document");
                   mandatoryDocKeys.add("performance_monitoring_program");
                   if (requiredDocuments != null) {
                       for (Map.Entry<String, String> doc : requiredDocuments.entrySet()) {
                           boolean isMandatory = mandatoryDocKeys.contains(doc.getKey());
                           boolean hasExistingDocument = existingDocumentKeys.contains(doc.getKey());
                
      out.write("\r\n");
      out.write("                <div class=\"doc-item\">\r\n");
      out.write("                    <strong>");
      out.print( doc.getValue() );
 if (isMandatory && !hasExistingDocument) { 
      out.write("<span class=\"required-mark\">*</span>");
 } 
      out.write("</strong>\r\n");
      out.write("                    ");
 if (hasExistingDocument) { 
      out.write("\r\n");
      out.write("                    <div class=\"hint\" style=\"margin-bottom:8px;\">Dokumen sedia ada telah ditemui dan akan digunakan semula jika tiada fail baharu dimuat naik.</div>\r\n");
      out.write("                    ");
 } 
      out.write("\r\n");
      out.write("                    <input type=\"file\" name=\"");
      out.print( doc.getKey() );
      out.write("\" data-doc-key=\"");
      out.print( doc.getKey() );
      out.write("\" accept=\"application/pdf\" />\r\n");
      out.write("                </div>\r\n");
      out.write("                ");
   }
                   }
                
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"actions\">\r\n");
      out.write("                <a class=\"btn btn-secondary\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/dashboard\">Batal</a>\r\n");
      out.write("                <button class=\"btn btn-primary\" type=\"submit\">");
      out.print( editMode ? "Kemaskini Permohonan" : "Hantar Permohonan Online" );
      out.write("</button>\r\n");
      out.write("            </div>\r\n");
      out.write("        </form>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"container\" style=\"padding-top:0;\">\r\n");
      out.write("            <div class=\"jans-contact-section\">\r\n");
      out.write("                <h3>Hubungi JANS</h3>\r\n");
      out.write("                <p class=\"contact-line\"><a class=\"contact-address-link\" href=\"https://www.google.com/maps/place/Jabatan+Air+Negeri+Sabah/data=!4m7!3m6!1s0x323b69b770552161:0x46ddcd3e362b7115!8m2!3d5.9610727!4d116.0687216!16s%2Fg%2F1pzrm3yct!19sChIJYSFVcLdpOzIRFXErNj7N3UY?authuser=0&hl=en&rclk=1\" target=\"_blank\" rel=\"noopener noreferrer\">SABAH WATER DEPARTMENT</a></p>\r\n");
      out.write("                <p class=\"contact-line\"><a class=\"contact-address-link\" href=\"https://www.google.com/maps/place/Jabatan+Air+Negeri+Sabah/data=!4m7!3m6!1s0x323b69b770552161:0x46ddcd3e362b7115!8m2!3d5.9610727!4d116.0687216!16s%2Fg%2F1pzrm3yct!19sChIJYSFVcLdpOzIRFXErNj7N3UY?authuser=0&hl=en&rclk=1\" target=\"_blank\" rel=\"noopener noreferrer\">Tingkat 6, Blok A, Wisma MUIS, Beg Berkunci No. 210, 88825</a></p>\r\n");
      out.write("                <p class=\"contact-line\"><a class=\"contact-address-link\" href=\"https://www.google.com/maps/place/Jabatan+Air+Negeri+Sabah/data=!4m7!3m6!1s0x323b69b770552161:0x46ddcd3e362b7115!8m2!3d5.9610727!4d116.0687216!16s%2Fg%2F1pzrm3yct!19sChIJYSFVcLdpOzIRFXErNj7N3UY?authuser=0&hl=en&rclk=1\" target=\"_blank\" rel=\"noopener noreferrer\">Kota Kinabalu, Sabah, Malaysia</a></p>\r\n");
      out.write("                <p class=\"contact-line\"><span>Tel: +60-88-232364 (HQ) , Fax: +60-88-232396</span></p>\r\n");
      out.write("                <p class=\"contact-line\"><span>Email: jans.hq@sabah.gov.my</span></p>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("<script>\r\n");
      out.write("(function() {\r\n");
      out.write("    var applicationForm = document.getElementById('applicationForm');\r\n");
      out.write("    var productArrayList = document.getElementById('productArrayList');\r\n");
      out.write("    var addProductBtn = document.getElementById('addProductBtn');\r\n");
      out.write("    var unsuccessfulPopup = document.getElementById('unsuccessfulPopup');\r\n");
      out.write("    var popup = document.getElementById('successPopup');\r\n");
      out.write("    var mandatoryDocKeys = [\r\n");
      out.write("        'official_application_letter',\r\n");
      out.write("        'principal_appointment_letter',\r\n");
      out.write("        'certification_license_file',\r\n");
      out.write("        'test_report_file',\r\n");
      out.write("        'brochure_catalogue',\r\n");
      out.write("        'price_list',\r\n");
      out.write("        'product_benefit_summary',\r\n");
      out.write("        'project_reference',\r\n");
      out.write("        'sop_document',\r\n");
      out.write("        'performance_monitoring_program'\r\n");
      out.write("    ];\r\n");
      out.write("    var existingDocCsvField = document.getElementById('existingDocKeysCsv');\r\n");
      out.write("    var existingDocKeys = new Set(\r\n");
      out.write("        existingDocCsvField && existingDocCsvField.value\r\n");
      out.write("            ? existingDocCsvField.value.split('|').filter(function(v) { return v && v.trim() !== ''; })\r\n");
      out.write("            : []\r\n");
      out.write("    );\r\n");
      out.write("\r\n");
      out.write("    var initialFormData = {\r\n");
      out.write("        application_type: \"");
      out.print( jsApplicationType );
      out.write("\",\r\n");
      out.write("        supplier_email: \"");
      out.print( jsSupplierEmail );
      out.write("\",\r\n");
      out.write("        supplier_phone: \"");
      out.print( jsSupplierPhone );
      out.write("\",\r\n");
      out.write("        supplier_name: \"");
      out.print( jsSupplierName );
      out.write("\",\r\n");
      out.write("        supplier_address: \"");
      out.print( jsSupplierAddress );
      out.write("\",\r\n");
      out.write("        manufacturer_name: \"");
      out.print( jsManufacturerName );
      out.write("\",\r\n");
      out.write("        manufacturer_address: \"");
      out.print( jsManufacturerAddress );
      out.write("\",\r\n");
      out.write("        manufacturer_phone: \"");
      out.print( jsManufacturerPhone );
      out.write("\",\r\n");
      out.write("        principal_name: \"");
      out.print( jsPrincipalName );
      out.write("\",\r\n");
      out.write("        principal_address: \"");
      out.print( jsPrincipalAddress );
      out.write("\",\r\n");
      out.write("        principal_phone: \"");
      out.print( jsPrincipalPhone );
      out.write("\",\r\n");
      out.write("        product_category: \"");
      out.print( jsProductCategory );
      out.write("\",\r\n");
      out.write("        product_name: \"");
      out.print( jsProductName );
      out.write("\",\r\n");
      out.write("        brand: \"");
      out.print( jsBrand );
      out.write("\",\r\n");
      out.write("        standard_name: \"");
      out.print( jsStandardName );
      out.write("\",\r\n");
      out.write("        certification_license: \"");
      out.print( jsCertificationLicense );
      out.write("\",\r\n");
      out.write("        certification_valid_until: \"");
      out.print( jsCertificationValidUntil );
      out.write("\",\r\n");
      out.write("        test_report_reference: \"");
      out.print( jsTestReportReference );
      out.write("\",\r\n");
      out.write("        test_report_date: \"");
      out.print( jsTestReportDate );
      out.write("\",\r\n");
      out.write("        warranty_years: \"");
      out.print( jsWarrantyYears );
      out.write("\",\r\n");
      out.write("        product_description: \"");
      out.print( jsProductDescription );
      out.write("\",\r\n");
      out.write("        product_class: \"");
      out.print( jsProductClass );
      out.write("\",\r\n");
      out.write("        product_size: \"");
      out.print( jsProductSize );
      out.write("\",\r\n");
      out.write("        sabah_rep_name: \"");
      out.print( jsSabahRepName );
      out.write("\",\r\n");
      out.write("        sabah_rep_address: \"");
      out.print( jsSabahRepAddress );
      out.write("\",\r\n");
      out.write("        sabah_rep_phone: \"");
      out.print( jsSabahRepPhone );
      out.write("\"\r\n");
      out.write("    };\r\n");
      out.write("\r\n");
      out.write("    function setFieldValue(selector, value) {\r\n");
      out.write("        var field = document.querySelector(selector);\r\n");
      out.write("        if (!field || value == null || value === '') {\r\n");
      out.write("            return;\r\n");
      out.write("        }\r\n");
      out.write("        field.value = value;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    function closeUnsuccessfulPopup() {\r\n");
      out.write("        if (!unsuccessfulPopup) return;\r\n");
      out.write("        unsuccessfulPopup.classList.remove('show');\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    if (unsuccessfulPopup) {\r\n");
      out.write("        var closeUnsuccessfulBtn = unsuccessfulPopup.querySelector('[data-close-unsuccessful-popup]');\r\n");
      out.write("        if (closeUnsuccessfulBtn) closeUnsuccessfulBtn.addEventListener('click', closeUnsuccessfulPopup);\r\n");
      out.write("        unsuccessfulPopup.addEventListener('click', function(e) {\r\n");
      out.write("            if (e.target === unsuccessfulPopup) closeUnsuccessfulPopup();\r\n");
      out.write("        });\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    if (applicationForm) {\r\n");
      out.write("        function syncProductBlocks() {\r\n");
      out.write("            if (!productArrayList) {\r\n");
      out.write("                return;\r\n");
      out.write("            }\r\n");
      out.write("            var fieldConfigs = [\r\n");
      out.write("                { name: 'product_category[]', id: 'product_category_' },\r\n");
      out.write("                { name: 'product_name[]', id: 'product_name_' },\r\n");
      out.write("                { name: 'brand[]', id: 'brand_' },\r\n");
      out.write("                { name: 'standard_name[]', id: 'standard_name_' },\r\n");
      out.write("                { name: 'certification_license[]', id: 'certification_license_' },\r\n");
      out.write("                { name: 'certification_valid_until[]', id: 'certification_valid_until_' },\r\n");
      out.write("                { name: 'test_report_reference[]', id: 'test_report_reference_' },\r\n");
      out.write("                { name: 'test_report_date[]', id: 'test_report_date_' },\r\n");
      out.write("                { name: 'warranty_years[]', id: 'warranty_years_' },\r\n");
      out.write("                { name: 'product_description[]', id: 'product_description_' },\r\n");
      out.write("                { name: 'product_class[]', id: 'product_class_' },\r\n");
      out.write("                { name: 'product_size[]', id: 'product_size_' }\r\n");
      out.write("            ];\r\n");
      out.write("            var items = Array.prototype.slice.call(productArrayList.querySelectorAll('[data-product-item]'));\r\n");
      out.write("            items.forEach(function(item, index) {\r\n");
      out.write("                var number = index + 1;\r\n");
      out.write("                var title = item.querySelector('.product-item-title');\r\n");
      out.write("                if (title) {\r\n");
      out.write("                    title.textContent = 'Produk ' + number;\r\n");
      out.write("                }\r\n");
      out.write("                var removeBtn = item.querySelector('[data-remove-product]');\r\n");
      out.write("\r\n");
      out.write("                fieldConfigs.forEach(function(config) {\r\n");
      out.write("                    var field = item.querySelector('[name=\"' + config.name + '\"]');\r\n");
      out.write("                    if (!field) {\r\n");
      out.write("                        return;\r\n");
      out.write("                    }\r\n");
      out.write("                    var nextId = config.id + number;\r\n");
      out.write("                    field.id = nextId;\r\n");
      out.write("                    field.required = true;\r\n");
      out.write("\r\n");
      out.write("                    var label = item.querySelector('label[for^=\"' + config.id.replace(/_$/, '') + '\"]');\r\n");
      out.write("                    if (label) {\r\n");
      out.write("                        label.setAttribute('for', nextId);\r\n");
      out.write("                    }\r\n");
      out.write("                });\r\n");
      out.write("\r\n");
      out.write("                if (removeBtn) {\r\n");
      out.write("                    removeBtn.hidden = items.length <= 1;\r\n");
      out.write("                }\r\n");
      out.write("            });\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        if (addProductBtn && productArrayList) {\r\n");
      out.write("            addProductBtn.addEventListener('click', function() {\r\n");
      out.write("                var firstItem = productArrayList.querySelector('[data-product-item]');\r\n");
      out.write("                if (!firstItem) {\r\n");
      out.write("                    return;\r\n");
      out.write("                }\r\n");
      out.write("\r\n");
      out.write("                var clone = firstItem.cloneNode(true);\r\n");
      out.write("                Array.prototype.slice.call(clone.querySelectorAll('input')).forEach(function(input) {\r\n");
      out.write("                    input.value = '';\r\n");
      out.write("                });\r\n");
      out.write("                Array.prototype.slice.call(clone.querySelectorAll('select')).forEach(function(select) {\r\n");
      out.write("                    select.selectedIndex = 0;\r\n");
      out.write("                });\r\n");
      out.write("                Array.prototype.slice.call(clone.querySelectorAll('textarea')).forEach(function(textarea) {\r\n");
      out.write("                    textarea.value = '';\r\n");
      out.write("                });\r\n");
      out.write("\r\n");
      out.write("                productArrayList.appendChild(clone);\r\n");
      out.write("                syncProductBlocks();\r\n");
      out.write("            });\r\n");
      out.write("\r\n");
      out.write("            productArrayList.addEventListener('click', function(event) {\r\n");
      out.write("                var removeButton = event.target.closest('[data-remove-product]');\r\n");
      out.write("                if (!removeButton) {\r\n");
      out.write("                    return;\r\n");
      out.write("                }\r\n");
      out.write("                var items = productArrayList.querySelectorAll('[data-product-item]');\r\n");
      out.write("                if (items.length <= 1) {\r\n");
      out.write("                    return;\r\n");
      out.write("                }\r\n");
      out.write("                var block = removeButton.closest('[data-product-item]');\r\n");
      out.write("                if (block) {\r\n");
      out.write("                    block.remove();\r\n");
      out.write("                    syncProductBlocks();\r\n");
      out.write("                }\r\n");
      out.write("            });\r\n");
      out.write("\r\n");
      out.write("            syncProductBlocks();\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        setFieldValue('#application_type', initialFormData.application_type);\r\n");
      out.write("        setFieldValue('#supplier_email', initialFormData.supplier_email);\r\n");
      out.write("        setFieldValue('#supplier_phone', initialFormData.supplier_phone);\r\n");
      out.write("        setFieldValue('#supplier_name', initialFormData.supplier_name);\r\n");
      out.write("        setFieldValue('#supplier_address', initialFormData.supplier_address);\r\n");
      out.write("        setFieldValue('#manufacturer_name', initialFormData.manufacturer_name);\r\n");
      out.write("        setFieldValue('#manufacturer_address', initialFormData.manufacturer_address);\r\n");
      out.write("        setFieldValue('#manufacturer_phone', initialFormData.manufacturer_phone);\r\n");
      out.write("        setFieldValue('#principal_name', initialFormData.principal_name);\r\n");
      out.write("        setFieldValue('#principal_address', initialFormData.principal_address);\r\n");
      out.write("        setFieldValue('#principal_phone', initialFormData.principal_phone);\r\n");
      out.write("        setFieldValue('#product_category_1', initialFormData.product_category);\r\n");
      out.write("        setFieldValue('#product_name_1', initialFormData.product_name);\r\n");
      out.write("        setFieldValue('#brand_1', initialFormData.brand);\r\n");
      out.write("        setFieldValue('#standard_name_1', initialFormData.standard_name);\r\n");
      out.write("        setFieldValue('#certification_license_1', initialFormData.certification_license);\r\n");
      out.write("        setFieldValue('#certification_valid_until_1', initialFormData.certification_valid_until);\r\n");
      out.write("        setFieldValue('#test_report_reference_1', initialFormData.test_report_reference);\r\n");
      out.write("        setFieldValue('#test_report_date_1', initialFormData.test_report_date);\r\n");
      out.write("        setFieldValue('#warranty_years_1', initialFormData.warranty_years);\r\n");
      out.write("        setFieldValue('#product_description_1', initialFormData.product_description);\r\n");
      out.write("        setFieldValue('#product_class_1', initialFormData.product_class);\r\n");
      out.write("        setFieldValue('#product_size_1', initialFormData.product_size);\r\n");
      out.write("        setFieldValue('#sabah_rep_name', initialFormData.sabah_rep_name);\r\n");
      out.write("        setFieldValue('#sabah_rep_address', initialFormData.sabah_rep_address);\r\n");
      out.write("        setFieldValue('#sabah_rep_phone', initialFormData.sabah_rep_phone);\r\n");
      out.write("\r\n");
      out.write("        applicationForm.addEventListener('submit', function(e) {\r\n");
      out.write("            var applicationTypeField = document.getElementById('application_type');\r\n");
      out.write("            var applicationType = applicationTypeField ? applicationTypeField.value : '';\r\n");
      out.write("            var keysToCheck = mandatoryDocKeys.slice();\r\n");
      out.write("\r\n");
      out.write("            if (applicationType === 'PEMBAHARUAN') {\r\n");
      out.write("                keysToCheck.push('renewal_certificate');\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            var hasMissingRequiredDoc = keysToCheck.some(function(docKey) {\r\n");
      out.write("                var fileInput = applicationForm.querySelector('input[type=\"file\"][data-doc-key=\"' + docKey + '\"]');\r\n");
      out.write("                var hasNewUpload = fileInput && fileInput.files && fileInput.files.length > 0;\r\n");
      out.write("                return !hasNewUpload && !existingDocKeys.has(docKey);\r\n");
      out.write("            });\r\n");
      out.write("\r\n");
      out.write("            if (hasMissingRequiredDoc) {\r\n");
      out.write("                e.preventDefault();\r\n");
      out.write("                if (unsuccessfulPopup) {\r\n");
      out.write("                    unsuccessfulPopup.classList.add('show');\r\n");
      out.write("                }\r\n");
      out.write("            }\r\n");
      out.write("        });\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    if (!popup) return;\r\n");
      out.write("    function closePopup() {\r\n");
      out.write("        popup.classList.remove('show');\r\n");
      out.write("        window.setTimeout(function() {\r\n");
      out.write("            if (popup && popup.parentNode) popup.parentNode.removeChild(popup);\r\n");
      out.write("        }, 260);\r\n");
      out.write("    }\r\n");
      out.write("    var closeBtn = popup.querySelector('[data-close-success-popup]');\r\n");
      out.write("    if (closeBtn) closeBtn.addEventListener('click', closePopup);\r\n");
      out.write("})();\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
