/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/11.0.18
 * Generated at: 2026-06-10 07:15:34 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.util.Map;
import java.util.List;
import java.sql.Date;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;

public final class certificate_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {


    private String formatCertificateNumber(Object value) {
        if (value == null) {
            return "-";
        }
        String raw = String.valueOf(value).trim();
        if (raw.isEmpty() || "null".equalsIgnoreCase(raw) || "-".equals(raw)) {
            return "-";
        }

        String compact = raw.replaceAll("\\s+", "").toUpperCase(java.util.Locale.ROOT);
        java.util.regex.Matcher matcher = java.util.regex.Pattern
                .compile("^JANS([A-Z0-9]+)$", java.util.regex.Pattern.CASE_INSENSITIVE)
                .matcher(compact);
        if (matcher.find()) {
            String token = matcher.group(1).toUpperCase(java.util.Locale.ROOT);
            if (token.matches("\\d+") && token.length() < 6) {
                token = String.format("%06d", Integer.parseInt(token));
            }
            return "JANS" + token;
        }
        return compact;
    }

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(7);
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("java.util.Map");
    _jspx_imports_classes.add("java.time.LocalDate");
    _jspx_imports_classes.add("java.time.format.DateTimeFormatter");
    _jspx_imports_classes.add("java.sql.Date");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ms\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Perakuan Pendaftaran - JANS</title>\r\n");
      out.write("    <style>\r\n");
      out.write("        * { box-sizing: border-box; margin: 0; padding: 0; }\r\n");
      out.write("        body { font-family: Arial, Helvetica, sans-serif; background: #e8e8e8; color: #111; }\r\n");
      out.write("\r\n");
      out.write("        /* ── screen toolbar ── */\r\n");
      out.write("        .screen-bar {\r\n");
      out.write("            background: #1b2a52; color: white; padding: 10px 22px;\r\n");
      out.write("            display: flex; justify-content: space-between; align-items: center;\r\n");
      out.write("            font-size: 14px;\r\n");
      out.write("        }\r\n");
      out.write("        .screen-bar a { color: #fff; text-decoration: none; margin-left: 14px; }\r\n");
      out.write("\r\n");
      out.write("        /* ── button row ── */\r\n");
      out.write("        .btn-row {\r\n");
      out.write("            display: flex; gap: 10px; justify-content: center;\r\n");
      out.write("            padding: 16px 0 12px; flex-wrap: wrap;\r\n");
      out.write("        }\r\n");
      out.write("        .btn {\r\n");
      out.write("            border: none; border-radius: 6px; padding: 10px 24px;\r\n");
      out.write("            font-size: 14px; cursor: pointer; font-family: Arial, sans-serif;\r\n");
      out.write("            text-decoration: none; display: inline-flex; align-items: center; gap: 6px;\r\n");
      out.write("        }\r\n");
      out.write("        .btn-print { background: #1b2a52; color: #fff; }\r\n");
      out.write("        .btn-pdf   { background: #2e7d32; color: #fff; }\r\n");
      out.write("        .btn-print:hover { background: #2e4080; }\r\n");
      out.write("        .btn-pdf:hover   { background: #1b5e20; }\r\n");
      out.write("\r\n");
      out.write("        /* ── A4 page ── */\r\n");
      out.write("        .page-wrap { max-width: 794px; margin: 0 auto 40px; padding: 0 20px; }\r\n");
      out.write("\r\n");
      out.write("        .cert-page {\r\n");
      out.write("            background: #fff;\r\n");
      out.write("            border: 2.5px solid #1b2a52;\r\n");
      out.write("            outline: 1px solid #1b2a52;\r\n");
      out.write("            outline-offset: -9px;\r\n");
      out.write("            position: relative;\r\n");
      out.write("            padding: 50px 60px 44px;\r\n");
      out.write("            min-height: 1050px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* watermark */\r\n");
      out.write("        .cert-page::before {\r\n");
      out.write("            content: '';\r\n");
      out.write("            position: absolute; top: 50%; left: 50%;\r\n");
      out.write("            transform: translate(-50%, -52%);\r\n");
      out.write("            width: 340px; height: 340px;\r\n");
      out.write("            background-image: url('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/images/logo-jabatan-air-sabah.png');\r\n");
      out.write("            background-size: contain; background-repeat: no-repeat; background-position: center;\r\n");
      out.write("            opacity: 0.09; pointer-events: none;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* ── header ── */\r\n");
      out.write("        .cert-header { text-align: center; margin-bottom: 22px; }\r\n");
      out.write("        .cert-header img { width: 90px; height: 90px; object-fit: contain; display: block; margin: 0 auto 8px; }\r\n");
      out.write("        .cert-org   { font-size: 16px; font-weight: bold; letter-spacing: 0.5px; margin-bottom: 3px; }\r\n");
      out.write("        .cert-sub   { font-size: 13px; font-weight: normal; }\r\n");
      out.write("\r\n");
      out.write("        /* ── fields ── */\r\n");
      out.write("        .field-table { width: 100%; border-collapse: collapse; margin-top: 20px; }\r\n");
      out.write("        .field-table tr td { padding: 8px 0 2px; vertical-align: bottom; font-size: 11.5pt; }\r\n");
      out.write("        .field-table .lbl { width: 33%; font-weight: bold; padding-left: 2px; }\r\n");
      out.write("        .field-table .colon { width: 4%; }\r\n");
      out.write("        .field-table .val {\r\n");
      out.write("            border-bottom: 1px solid #111;\r\n");
      out.write("            padding-bottom: 3px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* ── product table ── */\r\n");
      out.write("        .prod-wrap { margin-top: 22px; }\r\n");
      out.write("        .prod-table { width: 100%; border-collapse: collapse; }\r\n");
      out.write("        .prod-table th, .prod-table td {\r\n");
      out.write("            border: 1px solid #111;\r\n");
      out.write("            padding: 0 8px;\r\n");
      out.write("            font-size: 11pt;\r\n");
      out.write("            text-align: left;\r\n");
      out.write("        }\r\n");
      out.write("        .prod-table th { font-weight: bold; text-align: center; padding: 8px 4px; }\r\n");
      out.write("        .prod-table td { height: 50px; vertical-align: top; padding-top: 6px; }\r\n");
      out.write("\r\n");
      out.write("        /* ── print ── */\r\n");
      out.write("        @media print {\r\n");
      out.write("            body { background: #fff; }\r\n");
      out.write("            .screen-bar, .btn-row { display: none !important; }\r\n");
      out.write("            .page-wrap { margin: 0; padding: 0; max-width: 100%; }\r\n");
      out.write("            .cert-page { border-color: #1b2a52; outline-color: #1b2a52; box-shadow: none; min-height: auto; }\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");

    Map<String, Object> certApp = (Map<String, Object>) request.getAttribute("certApp");
    List<Map<String, String>> certProducts = (List<Map<String, String>>) certApp.get("certificate_products");

    String certNumber   = formatCertificateNumber(certApp.get("certificate_number"));
    int    appId        = ((Number) certApp.get("id")).intValue();

    String supplierNm   = certApp.get("supplier_name")       != null ? String.valueOf(certApp.get("supplier_name"))       : "";
    String mfrNm        = certApp.get("manufacturer_name")   != null ? String.valueOf(certApp.get("manufacturer_name"))   : "";
    String principalNm  = certApp.get("principal_name")      != null ? String.valueOf(certApp.get("principal_name"))      : "";
    String productName  = String.valueOf(certApp.get("product_name"));
    String productCat   = String.valueOf(certApp.get("product_category"));
    String stdName      = certApp.get("standard_name")       != null ? String.valueOf(certApp.get("standard_name"))       : "";

    DateTimeFormatter fmtMs = DateTimeFormatter.ofPattern("dd MMMM yyyy", new java.util.Locale("ms", "MY"));
    java.sql.Date issuedAtSql   = (java.sql.Date) certApp.get("issued_at");
    java.sql.Date validUntilSql = (java.sql.Date) certApp.get("valid_until");
    LocalDate issuedAt   = issuedAtSql  != null ? issuedAtSql.toLocalDate()  : LocalDate.now();
    LocalDate validUntil = validUntilSql != null ? validUntilSql.toLocalDate() : LocalDate.now().plusYears(2);
    String issuedStr = issuedAt.format(fmtMs);
    String validStr  = validUntil.format(fmtMs);

      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"screen-bar\">\r\n");
      out.write("    <span style=\"font-weight:bold;\">Perakuan Pendaftaran Produk Air Jabatan Air Sabah</span>\r\n");
      out.write("    <div>\r\n");
      out.write("        <a href=\"#\" onclick=\"goBackOrDashboard(event)\">&#8592; Kembali</a>\r\n");
      out.write("        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/dashboard\" title=\"Dashboard\" aria-label=\"Dashboard\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/icon/dashboard.png\" alt=\"Dashboard\" style=\"width:18px;height:18px;object-fit:contain;vertical-align:middle;\"></a>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"btn-row\">\r\n");
      out.write("    <button class=\"btn btn-print\" onclick=\"window.print()\">&#128438; Cetak</button>\r\n");
      out.write("    <a class=\"btn btn-pdf\" href=\"");
      out.print( request.getContextPath() );
      out.write("/certificate/pdf?id=");
      out.print( appId );
      out.write("\" download>\r\n");
      out.write("        &#128229; Muat Turun PDF\r\n");
      out.write("    </a>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"page-wrap\">\r\n");
      out.write("<div class=\"cert-page\">\r\n");
      out.write("\r\n");
      out.write("    <!-- header -->\r\n");
      out.write("    <div class=\"cert-header\">\r\n");
      out.write("        <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/images/logo-jabatan-air-sabah.png\"\r\n");
      out.write("             alt=\"Logo JANS\">\r\n");
      out.write("        <div class=\"cert-org\">JABATAN AIR SABAH</div>\r\n");
      out.write("        <div class=\"cert-sub\">Butiran Pendaftaran</div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- field list -->\r\n");
      out.write("    <table class=\"field-table\">\r\n");
      out.write("        <tr>\r\n");
      out.write("            <td class=\"lbl\">No Sijil</td>\r\n");
      out.write("            <td class=\"colon\">:</td>\r\n");
      out.write("            <td class=\"val\">");
      out.print( certNumber );
      out.write("</td>\r\n");
      out.write("        </tr>\r\n");
      out.write("        <tr>\r\n");
      out.write("            <td class=\"lbl\">Nama Pembekal</td>\r\n");
      out.write("            <td class=\"colon\">:</td>\r\n");
      out.write("            <td class=\"val\">");
      out.print( supplierNm );
      out.write("</td>\r\n");
      out.write("        </tr>\r\n");
      out.write("        <tr>\r\n");
      out.write("            <td class=\"lbl\">Nama Pengilang</td>\r\n");
      out.write("            <td class=\"colon\">:</td>\r\n");
      out.write("            <td class=\"val\">");
      out.print( mfrNm );
      out.write("</td>\r\n");
      out.write("        </tr>\r\n");
      out.write("        <tr>\r\n");
      out.write("            <td class=\"lbl\">Nama Prinsipal / Pemilik</td>\r\n");
      out.write("            <td class=\"colon\">:</td>\r\n");
      out.write("            <td class=\"val\">");
      out.print( principalNm );
      out.write("</td>\r\n");
      out.write("        </tr>\r\n");
      out.write("        <tr>\r\n");
      out.write("            <td class=\"lbl\">Nama Produk</td>\r\n");
      out.write("            <td class=\"colon\">:</td>\r\n");
      out.write("            <td class=\"val\">");
      out.print( productName );
      out.write("</td>\r\n");
      out.write("        </tr>\r\n");
      out.write("        <tr>\r\n");
      out.write("            <td class=\"lbl\">Kategori</td>\r\n");
      out.write("            <td class=\"colon\">:</td>\r\n");
      out.write("            <td class=\"val\">");
      out.print( productCat );
      out.write("</td>\r\n");
      out.write("        </tr>\r\n");
      out.write("        <tr>\r\n");
      out.write("            <td class=\"lbl\">Kelas/Saiz/Model</td>\r\n");
      out.write("            <td class=\"colon\">:</td>\r\n");
      out.write("            <td class=\"val\">&nbsp;</td>\r\n");
      out.write("        </tr>\r\n");
      out.write("        <tr>\r\n");
      out.write("            <td class=\"lbl\">Jenama</td>\r\n");
      out.write("            <td class=\"colon\">:</td>\r\n");
      out.write("            <td class=\"val\">&nbsp;</td>\r\n");
      out.write("        </tr>\r\n");
      out.write("        <tr>\r\n");
      out.write("            <td class=\"lbl\">Piawaian</td>\r\n");
      out.write("            <td class=\"colon\">:</td>\r\n");
      out.write("            <td class=\"val\">");
      out.print( stdName );
      out.write("</td>\r\n");
      out.write("        </tr>\r\n");
      out.write("        <tr>\r\n");
      out.write("            <td class=\"lbl\">Tarikh Dikeluarkan</td>\r\n");
      out.write("            <td class=\"colon\">:</td>\r\n");
      out.write("            <td class=\"val\">");
      out.print( issuedStr );
      out.write("</td>\r\n");
      out.write("        </tr>\r\n");
      out.write("        <tr>\r\n");
      out.write("            <td class=\"lbl\">Sah Sehingga</td>\r\n");
      out.write("            <td class=\"colon\">:</td>\r\n");
      out.write("            <td class=\"val\">");
      out.print( validStr );
      out.write("</td>\r\n");
      out.write("        </tr>\r\n");
      out.write("        <tr>\r\n");
      out.write("            <td class=\"lbl\">Perihal Produk</td>\r\n");
      out.write("            <td class=\"colon\">:</td>    \r\n");
      out.write("            <td class=\"val\">&nbsp;</td>\r\n");
      out.write("        </tr>\r\n");
      out.write("    </table>\r\n");
      out.write("\r\n");
      out.write("    <!-- product table -->\r\n");
      out.write("    <div class=\"prod-wrap\">\r\n");
      out.write("        <table class=\"prod-table\">\r\n");
      out.write("            <thead>\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <th style=\"width:28%\">NAMA PRODUK</th>\r\n");
      out.write("                    <th style=\"width:23%\">MODEL</th>\r\n");
      out.write("                    <th style=\"width:16%\">SIRI</th>\r\n");
      out.write("                    <th style=\"width:33%\">PERIHAL/CLASS/SAIZ</th>\r\n");
      out.write("                </tr>\r\n");
      out.write("            </thead>\r\n");
      out.write("            <tbody>\r\n");
      out.write("                ");
 for (Map<String, String> productRow : certProducts) { 
      out.write("\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td>");
      out.print( productRow.get("name") );
      out.write("</td>\r\n");
      out.write("                    <td>");
      out.print( productRow.get("model") );
      out.write("</td>\r\n");
      out.write("                    <td>");
      out.print( productRow.get("series") );
      out.write("</td>\r\n");
      out.write("                    <td>");
      out.print( productRow.get("description") );
      out.write("</td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                ");
 } 
      out.write("\r\n");
      out.write("            </tbody>\r\n");
      out.write("        </table>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("</div><!-- /cert-page -->\r\n");
      out.write("</div><!-- /page-wrap -->\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("    function goBackOrDashboard(event) {\r\n");
      out.write("        event.preventDefault();\r\n");
      out.write("        if (window.history.length > 1) {\r\n");
      out.write("            window.history.back();\r\n");
      out.write("            return;\r\n");
      out.write("        }\r\n");
      out.write("        window.location.href = '");
      out.print( request.getContextPath() );
      out.write("/dashboard';\r\n");
      out.write("    }\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
