/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/11.0.18
 * Generated at: 2026-06-10 03:48:39 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class forgot_002dpassword_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ms\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Lupa Kata Laluan - SPPPA</title>\r\n");
      out.write("    <style>\r\n");
      out.write("        :root {\r\n");
      out.write("            --brand-blue: #2A9D8F;\r\n");
      out.write("            --brand-navy: #0F6BAE;\r\n");
      out.write("            --brand-green: #6DBE45;\r\n");
      out.write("            --brand-lime: #CDE11D;\r\n");
      out.write("            --brand-yellow: #F2F72E;\r\n");
      out.write("        }\r\n");
      out.write("        * { box-sizing: border-box; }\r\n");
      out.write("        body { margin: 0; font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; min-height: 100vh; display: grid; place-items: center; padding: 24px; background: linear-gradient(135deg, var(--brand-navy) 0%, var(--brand-blue) 30%, var(--brand-green) 58%, var(--brand-lime) 80%, var(--brand-yellow) 100%); }\r\n");
      out.write("        .card { width: 100%; max-width: 520px; background: #fff; border-radius: 18px; box-shadow: 0 22px 60px rgba(6, 52, 79, 0.25); padding: 28px; }\r\n");
      out.write("        h1 { margin: 0 0 8px; color: #173040; }\r\n");
      out.write("        .subtitle { margin: 0 0 20px; color: #60798b; }\r\n");
      out.write("        .field { margin-bottom: 14px; }\r\n");
      out.write("        .field label { display: block; margin-bottom: 6px; font-size: 13px; font-weight: 700; color: #173040; }\r\n");
      out.write("        .field input { width: 100%; padding: 12px; border-radius: 12px; border: 1px solid #d7e7ef; }\r\n");
      out.write("        .actions { display: flex; gap: 10px; margin-top: 8px; }\r\n");
      out.write("        .btn { border: 1px solid #fff; border-radius: 12px; padding: 12px 16px; font-weight: 700; cursor: pointer; text-decoration: none; display: inline-flex; align-items: center; justify-content: center; }\r\n");
      out.write("        .btn-primary { background: linear-gradient(135deg, var(--brand-navy), var(--brand-blue), var(--brand-green)); color: #fff; }\r\n");
      out.write("        .btn-secondary { background: #e5f2f9; color: #0F6BAE; }\r\n");
      out.write("        .error { padding: 11px 12px; border-radius: 10px; background: #ffe9e9; color: #b42318; margin-bottom: 14px; }\r\n");
      out.write("                        .contact-box { margin-top: 16px; border: 1px solid #d7e7ef; border-radius: 12px; padding: 12px; background: #f8fcff; }\r\n");
      out.write("                        .contact-box strong { display: block; margin-bottom: 6px; color: #173040; }\r\n");
      out.write("                        .contact-box p { margin: 3px 0; color: #60798b; font-size: 13px; }\r\n");
      out.write("                        .floating-home-btn { position: fixed; right: 16px; top: 16px; z-index: 20; display: inline-flex; align-items: center; justify-content: center; width: 38px; height: 38px; border-radius: 999px; border: 1px solid #fff; background: rgba(255,255,255,0.18); }\r\n");
      out.write("                        .floating-home-btn img { width: 18px; height: 18px; object-fit: contain; }\r\n");
      out.write("                    /* Enforce visible white border on all clickable buttons */\r\n");
      out.write("        button,\r\n");
      out.write("        input[type=\"submit\"],\r\n");
      out.write("        input[type=\"button\"],\r\n");
      out.write("        .btn,\r\n");
      out.write("        .login-btn,\r\n");
      out.write("        .modal-close,\r\n");
      out.write("        .btn-attachment,\r\n");
      out.write("        .attachment-list button,\r\n");
      out.write("        a.btn {\r\n");
      out.write("            border: 1px solid #fff !important;\r\n");
      out.write("            box-shadow: inset 0 0 0 1px #fff, 0 1px 2px rgba(0, 0, 0, 0.18) !important;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        button:hover,\r\n");
      out.write("        input[type=\"submit\"]:hover,\r\n");
      out.write("        input[type=\"button\"]:hover,\r\n");
      out.write("        .btn:hover,\r\n");
      out.write("        .login-btn:hover,\r\n");
      out.write("        .modal-close:hover,\r\n");
      out.write("        .btn-attachment:hover,\r\n");
      out.write("        .attachment-list button:hover,\r\n");
      out.write("        a.btn:hover,\r\n");
      out.write("        button:focus,\r\n");
      out.write("        input[type=\"submit\"]:focus,\r\n");
      out.write("        input[type=\"button\"]:focus,\r\n");
      out.write("        .btn:focus,\r\n");
      out.write("        .login-btn:focus,\r\n");
      out.write("        .modal-close:focus,\r\n");
      out.write("        .btn-attachment:focus,\r\n");
      out.write("        .attachment-list button:focus,\r\n");
      out.write("        a.btn:focus {\r\n");
      out.write("            border: 1px solid #fff !important;\r\n");
      out.write("            box-shadow: inset 0 0 0 1px #fff, 0 0 0 2px rgba(255, 255, 255, 0.35), 0 1px 2px rgba(0, 0, 0, 0.18) !important;\r\n");
      out.write("        }\r\n");
      out.write("        .jans-contact-section { margin-top: 10px; border: 1px solid #d6e5ef; border-radius: 14px; background: #f8fcff; padding: 12px; }\r\n");
      out.write("        .jans-contact-section h3 { margin: 0 0 10px; color: #0f6bae; font-size: 16px; font-weight: 700; letter-spacing: 0; }\r\n");
      out.write("        .jans-contact-section .contact-line { display: flex; align-items: flex-start; gap: 8px; margin: 7px 0; color: #4e6a7c; font-size: 13px; line-height: 1.45; min-width: 0; }\r\n");
      out.write("        .jans-contact-section .contact-icon { display: inline-block; width: 10px; height: 10px; background: #0f6bae; border-radius: 2px; flex-shrink: 0; margin-top: 2px; }\r\n");
      out.write("        .jans-contact-section .contact-line span { line-height: 1.45; }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <a class=\"floating-home-btn\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/\" aria-label=\"Laman utama\" title=\"Laman utama\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/images/icon-home.png\" alt=\"Laman utama\"></a>\r\n");
      out.write("    <div class=\"card\">\r\n");
      out.write("        <h1>Lupa Kata Laluan</h1>\r\n");
      out.write("        <p class=\"subtitle\">Masukkan maklumat akaun berdaftar anda untuk tetapkan kata laluan baharu.</p>\r\n");
      out.write("\r\n");
      out.write("        ");
 if (request.getAttribute("error") != null) { 
      out.write("\r\n");
      out.write("            <div class=\"error\">");
      out.print( request.getAttribute("error") );
      out.write("</div>\r\n");
      out.write("        ");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <form method=\"post\" action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/forgot-password\">\r\n");
      out.write("            <input type=\"hidden\" name=\"_csrf\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${csrf_token}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("            <div class=\"field\">\r\n");
      out.write("                <label for=\"username\">Nama Pengguna</label>\r\n");
      out.write("                <input id=\"username\" name=\"username\" type=\"text\" required value=\"");
      out.print( request.getAttribute("username") == null ? "" : request.getAttribute("username") );
      out.write("\">\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"field\">\r\n");
      out.write("                <label for=\"full_name\">Nama Penuh</label>\r\n");
      out.write("                <input id=\"full_name\" name=\"full_name\" type=\"text\" required placeholder=\"Seperti dalam kad pengenalan\" value=\"");
      out.print( request.getAttribute("full_name") == null ? "" : request.getAttribute("full_name") );
      out.write("\">\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"field\">\r\n");
      out.write("                <label for=\"email\">Email Berdaftar</label>\r\n");
      out.write("                <input id=\"email\" name=\"email\" type=\"email\" required value=\"");
      out.print( request.getAttribute("email") == null ? "" : request.getAttribute("email") );
      out.write("\">\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"field\">\r\n");
      out.write("                <label for=\"new_password\">Kata Laluan Baharu</label>\r\n");
      out.write("                <input id=\"new_password\" name=\"new_password\" type=\"password\" required oninput=\"checkStrength(this.value)\">\r\n");
      out.write("                <div id=\"pw-strength\" style=\"margin-top:6px;font-size:12px;color:#60798b;\"></div>\r\n");
      out.write("                <ul style=\"margin:4px 0 0 16px;padding:0;font-size:12px;color:#60798b;\">\r\n");
      out.write("                    <li>Sekurang-kurangnya 8 aksara</li>\r\n");
      out.write("                    <li>Sekurang-kurangnya satu nombor (0-9)</li>\r\n");
      out.write("                    <li>Sekurang-kurangnya satu aksara khas (contoh: !@#$%)</li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"field\">\r\n");
      out.write("                <label for=\"confirm_password\">Sahkan Kata Laluan Baharu</label>\r\n");
      out.write("                <input id=\"confirm_password\" name=\"confirm_password\" type=\"password\" required>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"actions\">\r\n");
      out.write("                <button class=\"btn btn-primary\" type=\"submit\">Set Semula Kata Laluan</button>\r\n");
      out.write("                <a class=\"btn btn-secondary\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/login\">Kembali Login</a>\r\n");
      out.write("            </div>\r\n");
      out.write("        </form>\r\n");
      out.write("        <script>\r\n");
      out.write("        function checkStrength(pw) {\r\n");
      out.write("            var el = document.getElementById('pw-strength');\r\n");
      out.write("            if (!pw) { el.textContent = ''; return; }\r\n");
      out.write("            var issues = [];\r\n");
      out.write("            if (pw.length < 8) issues.push('terlalu pendek');\r\n");
      out.write("            if (!/\\d/.test(pw)) issues.push('tiada nombor');\r\n");
      out.write("            if (!/[!@#$%^&*()\\-_=+\\[\\]{};':\"\\\\|,.<>\\/?]/.test(pw)) issues.push('tiada aksara khas');\r\n");
      out.write("            if (issues.length === 0) {\r\n");
      out.write("                el.textContent = 'Kata laluan kukuh';\r\n");
      out.write("                el.style.color = '#0a7c2e';\r\n");
      out.write("            } else {\r\n");
      out.write("                el.textContent = 'Lemah: ' + issues.join(', ');\r\n");
      out.write("                el.style.color = '#b42318';\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("        </script>\r\n");
      out.write("        <div class=\"container\" style=\"padding-top:0;\">\r\n");
      out.write("            <div class=\"jans-contact-section\">\r\n");
      out.write("                <h3>Hubungi JANS</h3>\n");
      out.write("                <p class=\"contact-line\"><a class=\"contact-address-link\" href=\"https://www.google.com/maps/place/Jabatan+Air+Negeri+Sabah/data=!4m7!3m6!1s0x323b69b770552161:0x46ddcd3e362b7115!8m2!3d5.9610727!4d116.0687216!16s%2Fg%2F1pzrm3yct!19sChIJYSFVcLdpOzIRFXErNj7N3UY?authuser=0&hl=en&rclk=1\" target=\"_blank\" rel=\"noopener noreferrer\">SABAH WATER DEPARTMENT</a></p>\n");
      out.write("                <p class=\"contact-line\"><a class=\"contact-address-link\" href=\"https://www.google.com/maps/place/Jabatan+Air+Negeri+Sabah/data=!4m7!3m6!1s0x323b69b770552161:0x46ddcd3e362b7115!8m2!3d5.9610727!4d116.0687216!16s%2Fg%2F1pzrm3yct!19sChIJYSFVcLdpOzIRFXErNj7N3UY?authuser=0&hl=en&rclk=1\" target=\"_blank\" rel=\"noopener noreferrer\">Tingkat 6, Blok A, Wisma MUIS, Beg Berkunci No. 210, 88825</a></p>\n");
      out.write("                <p class=\"contact-line\"><a class=\"contact-address-link\" href=\"https://www.google.com/maps/place/Jabatan+Air+Negeri+Sabah/data=!4m7!3m6!1s0x323b69b770552161:0x46ddcd3e362b7115!8m2!3d5.9610727!4d116.0687216!16s%2Fg%2F1pzrm3yct!19sChIJYSFVcLdpOzIRFXErNj7N3UY?authuser=0&hl=en&rclk=1\" target=\"_blank\" rel=\"noopener noreferrer\">Kota Kinabalu, Sabah, Malaysia</a></p>\n");
      out.write("                <p class=\"contact-line\"><span>Tel: +60-88-232364 (HQ) , Fax: +60-88-232396</span></p>\n");
      out.write("                <p class=\"contact-line\"><span>Email: jans.hq@sabah.gov.my</span></p></div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
