/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/11.0.18
 * Generated at: 2026-06-10 03:48:39 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.util.List;
import java.util.Map;
import java.util.Collections;
import com.sistemppa.config.DatabaseConfig;
import com.sistemppa.service.DashboardDataService;
import java.sql.Connection;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {


    private String escapeHtml(String value) {
        if (value == null) {
            return "";
        }
        return value
                .replace("&", "&amp;")
                .replace("<", "&lt;")
                .replace(">", "&gt;")
                .replace("\"", "&quot;")
                .replace("'", "&#39;");
    }

    private String buildImageSrc(String contextPath, Object imageUrlValue) {
        if (imageUrlValue == null) {
            return "";
        }

        String raw = String.valueOf(imageUrlValue).trim().replace('\\', '/');
        if (raw.isEmpty()) {
            return "";
        }

        int assetsIndex = raw.indexOf("/assets/");
        if (assetsIndex > 0) {
            raw = raw.substring(assetsIndex);
        } else {
            int assetsRelativeIndex = raw.indexOf("assets/");
            if (assetsRelativeIndex > 0) {
                raw = "/" + raw.substring(assetsRelativeIndex);
            }
        }

        while (raw.contains("//") && !raw.startsWith("//")) {
            raw = raw.replace("//", "/");
        }

        int managedAnnouncementIndex = raw.indexOf("/announcement-images/");
        if (managedAnnouncementIndex >= 0) {
            raw = raw.substring(managedAnnouncementIndex);
        }

        int uploadManagedIndex = raw.toLowerCase(java.util.Locale.ROOT).indexOf("/uploads/sistemppa/announcements/");
        if (uploadManagedIndex >= 0) {
            String fileName = raw.substring(uploadManagedIndex + "/uploads/sistemppa/announcements/".length());
            int slashPos = fileName.indexOf('/');
            if (slashPos >= 0) {
                fileName = fileName.substring(0, slashPos);
            }
            if (!fileName.isBlank()) {
                raw = "/announcement-images/" + fileName;
            }
        }

        int uploadRelativeIndex = raw.toLowerCase(java.util.Locale.ROOT).indexOf("uploads/sistemppa/announcements/");
        if (uploadRelativeIndex >= 0) {
            String fileName = raw.substring(uploadRelativeIndex + "uploads/sistemppa/announcements/".length());
            int slashPos = fileName.indexOf('/');
            if (slashPos >= 0) {
                fileName = fileName.substring(0, slashPos);
            }
            if (!fileName.isBlank()) {
                raw = "/announcement-images/" + fileName;
            }
        }

        int legacyAnnouncementIndex = raw.indexOf("/assets/images/announcements/");
        if (legacyAnnouncementIndex >= 0) {
            String fileName = raw.substring(legacyAnnouncementIndex + "/assets/images/announcements/".length());
            int slashPos = fileName.indexOf('/');
            if (slashPos >= 0) {
                fileName = fileName.substring(0, slashPos);
            }
            if (!fileName.isBlank()) {
                raw = "/announcement-images/" + fileName;
            }
        }

        String lower = raw.toLowerCase(java.util.Locale.ROOT);
        if (lower.startsWith("http://") || lower.startsWith("https://") || lower.startsWith("data:") || raw.startsWith("//")) {
            return raw;
        }

        String safeContextPath = contextPath == null ? "" : contextPath.trim();
        if (safeContextPath.isEmpty() || "/".equals(safeContextPath)) {
            safeContextPath = "";
        }

        if (raw.startsWith("/")) {
            if (!safeContextPath.isEmpty() && raw.startsWith(safeContextPath + "/")) {
                return raw;
            }
            return safeContextPath + raw;
        }

        return safeContextPath + "/" + raw;
    }

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(8);
    _jspx_imports_classes.add("com.sistemppa.service.DashboardDataService");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("java.sql.Connection");
    _jspx_imports_classes.add("java.util.Map");
    _jspx_imports_classes.add("com.sistemppa.config.DatabaseConfig");
    _jspx_imports_classes.add("java.util.Collections");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write('\r');
      out.write('\n');

    List<Map<String, Object>> homepageAnnouncements = Collections.emptyList();
    boolean maintenanceMode = Boolean.TRUE.equals(application.getAttribute("maintenanceMode"));
    try (Connection conn = DatabaseConfig.getConnection()) {
        homepageAnnouncements = DashboardDataService.loadActiveAnnouncements(conn, 5);
    } catch (Exception ignored) {
        homepageAnnouncements = Collections.emptyList();
    }

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ms\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Sistem Pendaftaran Pembekal dan Produk Air (SPPPA)</title>\r\n");
      out.write("    <meta name=\"description\" content=\"Portal rasmi Sistem Pendaftaran Pembekal dan Produk Air Jabatan Air Negeri Sabah untuk pendaftaran produk air, pengumuman, dan semakan status permohonan.\">\r\n");
      out.write("    <style>\r\n");
      out.write("        @import url('https://fonts.googleapis.com/css2?family=Source+Sans+3:wght@400;600;700;800&display=swap');\r\n");
      out.write("\r\n");
      out.write("        :root {\r\n");
      out.write("            --brand-blue: #1e88e5;\r\n");
      out.write("            --brand-navy: #0F6BAE;\r\n");
      out.write("            --brand-sky: #edf4fb;\r\n");
      out.write("            --surface: #ffffff;\r\n");
      out.write("            --surface-soft: #f3f8fc;\r\n");
      out.write("            --text: #1a3040;\r\n");
      out.write("            --muted: #5d7484;\r\n");
      out.write("            --ring: rgba(15, 107, 174, 0.22);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        * { margin: 0; padding: 0; box-sizing: border-box; }\r\n");
      out.write("\r\n");
      out.write("        body {\r\n");
      out.write("            font-family: 'Source Sans 3', 'Trebuchet MS', sans-serif;\r\n");
      out.write("            line-height: 1.6;\r\n");
      out.write("            color: var(--text);\r\n");
      out.write("            background: #eef5fb;\r\n");
      out.write("            min-height: 100vh;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .navbar {\r\n");
      out.write("            position: sticky;\r\n");
      out.write("            top: 0;\r\n");
      out.write("            z-index: 30;\r\n");
      out.write("            background: #0f6bae;\r\n");
      out.write("            color: white;\r\n");
      out.write("            padding: 14px 26px;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            justify-content: space-between;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            border-bottom: 3px solid #65aeea;\r\n");
      out.write("            box-shadow: 0 12px 28px rgba(8, 51, 77, 0.2);\r\n");
      out.write("        }\r\n");
      out.write("        .brand { display: flex; align-items: center; gap: 14px; }\r\n");
      out.write("        .brand-logos { display: flex; align-items: center; gap: 10px; }\r\n");
      out.write("        .brand-logo { width: 48px; height: 48px; object-fit: contain; }\r\n");
      out.write("        .brand-text strong { display: block; font-size: 18px; line-height: 1.1; }\r\n");
      out.write("        .brand-text span { font-size: 12px; opacity: 0.88; }\r\n");
      out.write("\r\n");
      out.write("        .nav-actions { display: flex; gap: 10px; }\r\n");
      out.write("        .nav-link {\r\n");
      out.write("            color: #ffffff;\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            font-weight: 700;\r\n");
      out.write("            padding: 9px 13px;\r\n");
      out.write("            border-radius: 8px;\r\n");
      out.write("            border: 1px solid rgba(255,255,255,0.2);\r\n");
      out.write("            transition: 0.2s ease;\r\n");
      out.write("        }\r\n");
      out.write("        .nav-link:hover, .nav-link:focus { background: rgba(255, 255, 255, 0.12); }\r\n");
      out.write("        .nav-link.primary {\r\n");
      out.write("            background: #1e88e5;\r\n");
      out.write("            border-color: rgba(255,255,255,0.35);\r\n");
      out.write("            color: #ffffff;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .hero {\r\n");
      out.write("            position: relative;\r\n");
      out.write("            height: auto;\r\n");
      out.write("            min-height: 260px;\r\n");
      out.write("            overflow: hidden;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            padding: 72px 28px 72px 12px;\r\n");
      out.write("            background: #1579cc;\r\n");
      out.write("            color: white;\r\n");
      out.write("            border-bottom-left-radius: 28px;\r\n");
      out.write("            border-bottom-right-radius: 28px;\r\n");
      out.write("            box-shadow: 0 16px 42px rgba(6, 47, 72, 0.22);\r\n");
      out.write("        }\r\n");
      out.write("        /* Shared blob base */\r\n");
      out.write("        .hero::before,\r\n");
      out.write("        .hero::after {\r\n");
      out.write("            content: \"\";\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            border-radius: 50%;\r\n");
      out.write("            filter: blur(120px);\r\n");
      out.write("            opacity: 0.7;\r\n");
      out.write("            z-index: 1;\r\n");
      out.write("        }\r\n");
      out.write("        /* Left big soft blob */\r\n");
      out.write("        .hero::before {\r\n");
      out.write("            width: 500px;\r\n");
      out.write("            height: 500px;\r\n");
      out.write("            background: #4ca6f2;\r\n");
      out.write("            top: 50px;\r\n");
      out.write("            left: -100px;\r\n");
      out.write("        }\r\n");
      out.write("        /* Right glow */\r\n");
      out.write("        .hero::after {\r\n");
      out.write("            width: 600px;\r\n");
      out.write("            height: 600px;\r\n");
      out.write("            background: #1e88e5;\r\n");
      out.write("            top: 0;\r\n");
      out.write("            right: -150px;\r\n");
      out.write("        }\r\n");
      out.write("        .hero-circle {\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            border-radius: 50%;\r\n");
      out.write("            background: rgba(255,255,255,0.2);\r\n");
      out.write("            backdrop-filter: blur(5px);\r\n");
      out.write("            z-index: 2;\r\n");
      out.write("        }\r\n");
      out.write("        .hero-circle.small  { width: 40px;  height: 40px;  }\r\n");
      out.write("        .hero-circle.medium { width: 80px;  height: 80px;  }\r\n");
      out.write("        .hero-circle1 { top: 80px;    left: 200px;  }\r\n");
      out.write("        .hero-circle2 { top: 150px;   right: 300px; }\r\n");
      out.write("        .hero-circle3 { bottom: 60px; left: 300px;  }\r\n");
      out.write("        .hero-watermark {\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            inset: 0;\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            height: 100%;\r\n");
      out.write("            object-fit: contain;\r\n");
      out.write("            object-position: center;\r\n");
      out.write("            opacity: 0.16;\r\n");
      out.write("            pointer-events: none;\r\n");
      out.write("            z-index: 0;\r\n");
      out.write("            padding: 44px;\r\n");
      out.write("            filter: brightness(1.12);\r\n");
      out.write("        }\r\n");
      out.write("        .hero-inner {\r\n");
      out.write("            max-width: 1020px;\r\n");
      out.write("            margin: 0;\r\n");
      out.write("            position: relative;\r\n");
      out.write("            z-index: 10;\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            text-align: left;\r\n");
      out.write("        }\r\n");
      out.write("        .hero h1 {\r\n");
      out.write("            position: relative;\r\n");
      out.write("            z-index: 11;\r\n");
      out.write("            font-size: clamp(30px, 4vw, 52px);\r\n");
      out.write("            line-height: 1.14;\r\n");
      out.write("            margin-bottom: 14px;\r\n");
      out.write("            max-width: 760px;\r\n");
      out.write("            letter-spacing: -0.02em;\r\n");
      out.write("            animation: riseIn .55s ease-out;\r\n");
      out.write("        }\r\n");
      out.write("        .hero p { font-size: 17px; margin-bottom: 20px; max-width: 720px; color: rgba(255,255,255,0.95); animation: riseIn .72s ease-out; }\r\n");
      out.write("        .hero-badges { display: flex; flex-wrap: wrap; gap: 10px; margin-bottom: 16px; justify-content: flex-start; }\r\n");
      out.write("        .hero-badge {\r\n");
      out.write("            display: inline-flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            padding: 8px 12px;\r\n");
      out.write("            border-radius: 999px;\r\n");
      out.write("            font-size: 12px;\r\n");
      out.write("            font-weight: 700;\r\n");
      out.write("            border: 1px solid rgba(255,255,255,0.38);\r\n");
      out.write("            background: rgba(255,255,255,0.12);\r\n");
      out.write("        }\r\n");
      out.write("        .hero-actions { display: flex; flex-wrap: wrap; gap: 12px; }\r\n");
      out.write("        .hero-btn {\r\n");
      out.write("            display: inline-block;\r\n");
      out.write("            padding: 12px 24px;\r\n");
      out.write("            color: #fff;\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            border-radius: 999px;\r\n");
      out.write("            font-weight: 800;\r\n");
      out.write("            border: 1px solid rgba(255,255,255,0.55);\r\n");
      out.write("            background: rgba(255, 255, 255, 0.1);\r\n");
      out.write("            transition: transform 0.18s ease, background-color 0.2s ease;\r\n");
      out.write("            box-shadow: 0 12px 22px rgba(6, 47, 72, 0.2);\r\n");
      out.write("        }\r\n");
      out.write("        .hero-btn:hover, .hero-btn:focus { transform: translateY(-1px); background: rgba(255, 255, 255, 0.22); }\r\n");
      out.write("        .hero-btn.accent { background: #ffffff; color: #0a5f8b; border-color: #ffffff; }\r\n");
      out.write("        .hero-btn.accent:hover, .hero-btn.accent:focus { background: #f0f9ff; }\r\n");
      out.write("\r\n");
      out.write("        .role-choice-wrap {\r\n");
      out.write("            max-width: 1020px;\r\n");
      out.write("            margin: -28px auto 26px;\r\n");
      out.write("            padding: 0 20px;\r\n");
      out.write("            position: relative;\r\n");
      out.write("            z-index: 2;\r\n");
      out.write("        }\r\n");
      out.write("        .role-choice-grid {\r\n");
      out.write("            display: grid;\r\n");
      out.write("            grid-template-columns: repeat(2, minmax(0, 1fr));\r\n");
      out.write("            gap: 16px;\r\n");
      out.write("        }\r\n");
      out.write("        .role-card {\r\n");
      out.write("            background: rgba(255, 255, 255, 0.76);\r\n");
      out.write("            backdrop-filter: blur(8px);\r\n");
      out.write("            border: 1px solid rgba(255, 255, 255, 0.65);\r\n");
      out.write("            border-radius: 20px;\r\n");
      out.write("            box-shadow: 0 16px 30px rgba(6, 47, 72, 0.14);\r\n");
      out.write("            padding: 18px;\r\n");
      out.write("            min-height: 190px;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            flex-direction: column;\r\n");
      out.write("            justify-content: space-between;\r\n");
      out.write("            transition: transform 0.2s ease, box-shadow 0.2s ease, border-color 0.2s ease, background-color 0.2s ease;\r\n");
      out.write("        }\r\n");
      out.write("        .role-card:hover,\r\n");
      out.write("        .role-card:focus-within {\r\n");
      out.write("            transform: translateY(-5px);\r\n");
      out.write("            box-shadow: 0 22px 40px rgba(6, 47, 72, 0.2);\r\n");
      out.write("            border-color: rgba(15, 107, 174, 0.45);\r\n");
      out.write("            background: rgba(255, 255, 255, 0.9);\r\n");
      out.write("        }\r\n");
      out.write("        .role-card h3 {\r\n");
      out.write("            margin: 0 0 6px;\r\n");
      out.write("            font-size: 22px;\r\n");
      out.write("            color: #0d4568;\r\n");
      out.write("        }\r\n");
      out.write("        .role-card-head {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            align-items: flex-start;\r\n");
      out.write("            gap: 12px;\r\n");
      out.write("        }\r\n");
      out.write("        .role-card-icon {\r\n");
      out.write("            width: 46px;\r\n");
      out.write("            height: 46px;\r\n");
      out.write("            object-fit: contain;\r\n");
      out.write("            flex: 0 0 46px;\r\n");
      out.write("            margin-top: 2px;\r\n");
      out.write("        }\r\n");
      out.write("        .role-card p {\r\n");
      out.write("            margin: 0;\r\n");
      out.write("            color: #2d556d;\r\n");
      out.write("            font-size: 15px;\r\n");
      out.write("        }\r\n");
      out.write("        .role-card .role-login-btn {\r\n");
      out.write("            margin-top: 14px;\r\n");
      out.write("            align-self: center;\r\n");
      out.write("            width: min(260px, 100%);\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            padding: 10px 16px;\r\n");
      out.write("            border-radius: 999px;\r\n");
      out.write("            font-weight: 800;\r\n");
      out.write("            color: #ffffff;\r\n");
      out.write("            border: 1px solid rgba(255, 255, 255, 0.85);\r\n");
      out.write("            background: #1e88e5;\r\n");
      out.write("            transition: transform 0.18s ease, box-shadow 0.18s ease, filter 0.18s ease;\r\n");
      out.write("            box-shadow: 0 10px 20px rgba(6, 47, 72, 0.18);\r\n");
      out.write("        }\r\n");
      out.write("        .role-card .role-login-btn:hover,\r\n");
      out.write("        .role-card .role-login-btn:focus {\r\n");
      out.write("            transform: translateY(-2px);\r\n");
      out.write("            box-shadow: 0 14px 24px rgba(6, 47, 72, 0.24);\r\n");
      out.write("            filter: brightness(1.03);\r\n");
      out.write("        }\r\n");
      out.write("        .first-signin-wrap {\r\n");
      out.write("            margin-top: 14px;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            justify-content: center;\r\n");
      out.write("        }\r\n");
      out.write("        .first-signin-btn {\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            display: inline-block;\r\n");
      out.write("            padding: 11px 24px;\r\n");
      out.write("            border-radius: 999px;\r\n");
      out.write("            border: 1px solid #d4e7f4;\r\n");
      out.write("            background: rgba(255, 255, 255, 0.88);\r\n");
      out.write("            color: #0f5d88;\r\n");
      out.write("            font-weight: 800;\r\n");
      out.write("            box-shadow: 0 8px 18px rgba(6, 47, 72, 0.12);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .container { max-width: 1200px; margin: 0 auto; padding: 42px 20px 56px; }\r\n");
      out.write("\r\n");
      out.write("        .quick-grid {\r\n");
      out.write("            display: grid;\r\n");
      out.write("            grid-template-columns: repeat(3, minmax(0, 1fr));\r\n");
      out.write("            gap: 14px;\r\n");
      out.write("            margin-bottom: 26px;\r\n");
      out.write("        }\r\n");
      out.write("        .quick-card {\r\n");
      out.write("            background: var(--surface);\r\n");
      out.write("            border: 1px solid #dbeaf4;\r\n");
      out.write("            border-radius: 18px;\r\n");
      out.write("            padding: 16px;\r\n");
      out.write("            box-shadow: 0 10px 24px rgba(6, 47, 72, 0.07);\r\n");
      out.write("        }\r\n");
      out.write("        .quick-card h4 { margin-bottom: 6px; font-size: 16px; color: var(--brand-navy); }\r\n");
      out.write("        .quick-card p { margin: 0; color: var(--muted); font-size: 14px; }\r\n");
      out.write("\r\n");
      out.write("        .section-title { margin-bottom: 10px; font-size: 24px; letter-spacing: -0.01em; }\r\n");
      out.write("        .section-subtitle { margin-bottom: 16px; color: var(--muted); }\r\n");
      out.write("\r\n");
      out.write("        .announcement-section {\r\n");
      out.write("            margin-bottom: 24px;\r\n");
      out.write("            border: 1px solid #d9e7f1;\r\n");
      out.write("            border-radius: 20px;\r\n");
      out.write("            background: var(--surface);\r\n");
      out.write("            box-shadow: 0 14px 30px rgba(6, 47, 72, 0.08);\r\n");
      out.write("            overflow: hidden;\r\n");
      out.write("        }\r\n");
      out.write("        .maintenance-overlay {\r\n");
      out.write("            position: fixed;\r\n");
      out.write("            top: 0;\r\n");
      out.write("            left: 0;\r\n");
      out.write("            right: 0;\r\n");
      out.write("            bottom: 0;\r\n");
      out.write("            background: rgba(5, 29, 45, 0.35);\r\n");
      out.write("            display: flex;\r\n");
      out.write("            align-items: flex-start;\r\n");
      out.write("            justify-content: center;\r\n");
      out.write("            padding: 14px 12px;\r\n");
      out.write("            z-index: 1300;\r\n");
      out.write("            pointer-events: none;\r\n");
      out.write("        }\r\n");
      out.write("        .maintenance-banner {\r\n");
      out.write("            width: min(980px, calc(100vw - 24px));\r\n");
      out.write("            margin: 0;\r\n");
      out.write("            padding: 12px 16px;\r\n");
      out.write("            border: 1px solid #f2c18b;\r\n");
      out.write("            border-radius: 14px;\r\n");
      out.write("            background: #ffffff;\r\n");
      out.write("            box-shadow: 0 10px 24px rgba(93, 60, 7, 0.14);\r\n");
      out.write("            display: flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            gap: 12px;\r\n");
      out.write("            pointer-events: auto;\r\n");
      out.write("        }\r\n");
      out.write("        .admin-access-card { position: relative; z-index: 1310; }\r\n");
      out.write("        .admin-access-card .role-login-btn { position: relative; z-index: 1311; }\r\n");
      out.write("        .maintenance-banner img {\r\n");
      out.write("            width: 88px;\r\n");
      out.write("            height: 60px;\r\n");
      out.write("            object-fit: contain;\r\n");
      out.write("            flex: 0 0 auto;\r\n");
      out.write("        }\r\n");
      out.write("        .maintenance-banner strong {\r\n");
      out.write("            display: block;\r\n");
      out.write("            margin-bottom: 3px;\r\n");
      out.write("            color: #7b3f00;\r\n");
      out.write("            font-size: 18px;\r\n");
      out.write("        }\r\n");
      out.write("        .maintenance-banner p {\r\n");
      out.write("            margin: 0;\r\n");
      out.write("            color: #7a4e1f;\r\n");
      out.write("            font-size: 14px;\r\n");
      out.write("            line-height: 1.45;\r\n");
      out.write("        }\r\n");
      out.write("        .announcement-header {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            gap: 10px;\r\n");
      out.write("            padding: 16px 18px;\r\n");
      out.write("            background: #eaf4ff;\r\n");
      out.write("            border-bottom: 1px solid #d9e7f1;\r\n");
      out.write("        }\r\n");
      out.write("        .icon-badge {\r\n");
      out.write("            width: 24px;\r\n");
      out.write("            height: 24px;\r\n");
      out.write("            display: inline-flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            justify-content: center;\r\n");
      out.write("            color: var(--brand-blue);\r\n");
      out.write("        }\r\n");
      out.write("        .icon-badge svg {\r\n");
      out.write("            width: 22px;\r\n");
      out.write("            height: 22px;\r\n");
      out.write("            display: block;\r\n");
      out.write("        }\r\n");
      out.write("        .icon-badge img {\r\n");
      out.write("            width: 22px;\r\n");
      out.write("            height: 22px;\r\n");
      out.write("            display: block;\r\n");
      out.write("            object-fit: contain;\r\n");
      out.write("        }\r\n");
      out.write("        .announcement-header h3 { margin: 0; font-size: 16px; color: var(--brand-navy); }\r\n");
      out.write("        .announcement-list { padding: 0 18px 10px; }\r\n");
      out.write("        .announcement-item { padding: 14px 0; border-bottom: 1px dashed #dce9f2; }\r\n");
      out.write("        .announcement-item:last-child { border-bottom: 0; }\r\n");
      out.write("        .announcement-item h4 { margin: 0 0 6px; font-size: 17px; color: var(--brand-navy); }\r\n");
      out.write("        .announcement-item img { width: 100%; max-width: 360px; height: auto; border: 1px solid #dce8f2; border-radius: 10px; margin: 6px 0 8px; }\r\n");
      out.write("        .announcement-item p { margin: 0; color: var(--text); white-space: pre-wrap; }\r\n");
      out.write("        .announcement-empty { padding: 14px 0; color: var(--muted); }\r\n");
      out.write("\r\n");
      out.write("        .hero-contact {\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            border-radius: 14px;\r\n");
      out.write("            border: 1px solid #d6e5ef;\r\n");
      out.write("            background: #f8fcff;\r\n");
      out.write("            padding: 12px;\r\n");
      out.write("            box-shadow: 0 8px 24px rgba(6, 47, 72, 0.07);\r\n");
      out.write("            margin-top: 10px;\r\n");
      out.write("        }\r\n");
      out.write("        .hero-contact h3 { margin: 0 0 10px; font-size: 16px; color: #0f6bae; font-weight: 700; letter-spacing: 0; }\r\n");
      out.write("        .hero-contact p { margin: 7px 0; font-size: 13px; color: #4e6a7c; line-height: 1.45; }\r\n");
      out.write("        .contact-line {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            align-items: flex-start;\r\n");
      out.write("            gap: 8px;\r\n");
      out.write("        }\r\n");
      out.write("        .contact-line .contact-icon {\r\n");
      out.write("            display: inline-block;\r\n");
      out.write("            width: 10px;\r\n");
      out.write("            height: 10px;\r\n");
      out.write("            background: #0f6bae;\r\n");
      out.write("            border-radius: 2px;\r\n");
      out.write("            flex-shrink: 0;\r\n");
      out.write("            margin-top: 2px;\r\n");
      out.write("        }\r\n");
      out.write("        .hero-contact .contact-line span { line-height: 1.45; }\r\n");
      out.write("\r\n");
      out.write("        footer {\r\n");
      out.write("            background: #072d43;\r\n");
      out.write("            color: white;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            padding: 30px;\r\n");
      out.write("            border-top-left-radius: 20px;\r\n");
      out.write("            border-top-right-radius: 20px;\r\n");
      out.write("        }\r\n");
      out.write("        footer .footer-links {\r\n");
      out.write("            margin-top: 8px;\r\n");
      out.write("            font-size: 13px;\r\n");
      out.write("            color: rgba(255,255,255,0.85);\r\n");
      out.write("        }\r\n");
      out.write("        footer .footer-links a {\r\n");
      out.write("            color: #d3efff;\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            margin: 0 8px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .floating-home-btn {\r\n");
      out.write("            position: static;\r\n");
      out.write("            display: inline-flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            justify-content: center;\r\n");
      out.write("            width: 32px;\r\n");
      out.write("            height: 32px;\r\n");
      out.write("            margin-left: 12px;\r\n");
      out.write("            border-radius: 999px;\r\n");
      out.write("            border: 1px solid #fff;\r\n");
      out.write("            background: rgba(255, 255, 255, 0.12);\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            vertical-align: middle;\r\n");
      out.write("        }\r\n");
      out.write("        .floating-home-btn img {\r\n");
      out.write("            width: 16px;\r\n");
      out.write("            height: 16px;\r\n");
      out.write("            object-fit: contain;\r\n");
      out.write("        }\r\n");
      out.write("        .floating-home-btn svg {\r\n");
      out.write("            width: 16px;\r\n");
      out.write("            height: 16px;\r\n");
      out.write("            display: block;\r\n");
      out.write("            color: #ffffff;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        @keyframes riseIn {\r\n");
      out.write("            from { opacity: 0; transform: translateY(8px); }\r\n");
      out.write("            to { opacity: 1; transform: translateY(0); }\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        @media (max-width: 980px) {\r\n");
      out.write("            .quick-grid { grid-template-columns: 1fr; }\r\n");
      out.write("            .navbar { flex-direction: column; align-items: flex-start; gap: 12px; }\r\n");
      out.write("            .nav-actions { width: 100%; }\r\n");
      out.write("            .nav-link { flex: 1; text-align: center; }\r\n");
      out.write("            .role-choice-grid { grid-template-columns: 1fr; }\r\n");
      out.write("            .role-choice-wrap { margin-top: -18px; }\r\n");
      out.write("            .role-card-icon { width: 42px; height: 42px; flex-basis: 42px; }\r\n");
      out.write("        }\r\n");
      out.write("        </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    ");
 if (maintenanceMode) { 
      out.write("\r\n");
      out.write("    <div class=\"maintenance-overlay\" aria-hidden=\"true\">\r\n");
      out.write("        <div class=\"maintenance-banner\" role=\"status\" aria-live=\"polite\" aria-atomic=\"true\">\r\n");
      out.write("            <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/icon/under-maintenance.gif\" alt=\"Sistem dalam penyelenggaraan\">\r\n");
      out.write("            <div>\r\n");
      out.write("                <strong>Sistem Sedang Dalam Penyelenggaraan</strong>\r\n");
      out.write("                <p>Sila cuba semula selepas penyelenggaraan selesai.</p>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    ");
 } 
      out.write("\r\n");
      out.write("    <div class=\"navbar\">\r\n");
      out.write("        <div class=\"brand\">\r\n");
      out.write("            <div class=\"brand-logos\">\r\n");
      out.write("                <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/images/sabah-logo.png\" class=\"brand-logo\" alt=\"Logo Sabah\">\r\n");
      out.write("                <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/images/logo-jabatan-air-sabah.png?v=4\" class=\"brand-logo\" alt=\"Logo Jabatan Air Sabah\">\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"brand-text\">\r\n");
      out.write("                <strong>Sistem Pendaftaran Pembekal dan Produk Air</strong>\r\n");
      out.write("                <span>Jabatan Air Negeri Sabah</span>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"nav-actions\">\r\n");
      out.write("            <a class=\"nav-link\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/login\">Log Masuk</a>\r\n");
      out.write("            <a class=\"nav-link primary\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/register\">Daftar Pemohon</a>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"hero\">\r\n");
      out.write("        <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/images/Logo JAS.png\" class=\"hero-watermark\" alt=\"\" aria-hidden=\"true\">\r\n");
      out.write("        <div class=\"hero-circle small  hero-circle1\" aria-hidden=\"true\"></div>\r\n");
      out.write("        <div class=\"hero-circle medium hero-circle2\" aria-hidden=\"true\"></div>\r\n");
      out.write("        <div class=\"hero-circle small  hero-circle3\" aria-hidden=\"true\"></div>\r\n");
      out.write("        <div class=\"hero-inner\">\r\n");
      out.write("            <div>\r\n");
      out.write("                <h1>Selamat Datang ke Sistem Pendaftaran Pembekal dan Produk Air</h1>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <section class=\"role-choice-wrap\" aria-label=\"Pilih peranan log masuk\">\r\n");
      out.write("        <div class=\"role-choice-grid\">\r\n");
      out.write("            <article class=\"role-card admin-access-card\">\r\n");
      out.write("                <div class=\"role-card-head\">\r\n");
      out.write("                    <img class=\"role-card-icon\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/images/admin.png\" alt=\"Ikon portal pentadbir\">\r\n");
      out.write("                    <div>\r\n");
      out.write("                        <h3>Portal Pentadbir</h3>\r\n");
      out.write("                        <p>Untuk pengurusan aplikasi, semakan pengguna, dan pemantauan Sistem Pendaftaran Pembekal dan Produk Air.</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <a class=\"role-login-btn\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/login?role=ADMIN\">Log Masuk Sebagai Admin</a>\r\n");
      out.write("            </article>\r\n");
      out.write("            <article class=\"role-card\">\r\n");
      out.write("                <div class=\"role-card-head\">\r\n");
      out.write("                    <img class=\"role-card-icon\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/images/users.png\" alt=\"Ikon portal pemohon\">\r\n");
      out.write("                    <div>\r\n");
      out.write("                        <h3>Portal Pemohon</h3>\r\n");
      out.write("                        <p>Untuk pendaftaran produk air, kemas kini maklumat, dan semakan status permohonan.</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <a class=\"role-login-btn\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/login?role=USER\">Log Masuk Sebagai Pemohon</a>\r\n");
      out.write("            </article>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"first-signin-wrap\">\r\n");
      out.write("            <a class=\"first-signin-btn\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/register\">Daftar akaun baharu</a>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"announcement-section\" aria-label=\"Pengumuman dan info semasa\">\r\n");
      out.write("            <div class=\"announcement-header\">\r\n");
      out.write("                <span class=\"icon-badge\" aria-hidden=\"true\">\r\n");
      out.write("                    <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/images/icon-announcement.png\" alt=\"Ikon pengumuman\">\r\n");
      out.write("                </span>\r\n");
      out.write("                <h3>Pengumuman / Info Terkini</h3>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"announcement-list\">\r\n");
      out.write("                ");
 if (homepageAnnouncements == null || homepageAnnouncements.isEmpty()) { 
      out.write("\r\n");
      out.write("                    <div class=\"announcement-empty\">Tiada pengumuman buat masa ini.</div>\r\n");
      out.write("                ");
 } else {
                    for (Map<String, Object> ann : homepageAnnouncements) {
                        String announcementImageSrc = buildImageSrc(request.getContextPath(), ann.get("image_url"));
                
      out.write("\r\n");
      out.write("                    <div class=\"announcement-item\">\r\n");
      out.write("                        <h4>");
      out.print( escapeHtml(String.valueOf(ann.get("title"))) );
      out.write("</h4>\r\n");
      out.write("                        ");
 if (!announcementImageSrc.isBlank()) { 
      out.write("\r\n");
      out.write("                            <img src=\"");
      out.print( escapeHtml(announcementImageSrc) );
      out.write("\" alt=\"Gambar pengumuman\" onerror=\"this.style.display='none';\">\r\n");
      out.write("                        ");
 } 
      out.write("\r\n");
      out.write("                        <p>");
      out.print( escapeHtml(String.valueOf(ann.get("content"))) );
      out.write("</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                ");
  }
                } 
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"container\" style=\"padding-top:0;\">\r\n");
      out.write("            <div class=\"jans-contact-section\">\r\n");
      out.write("                <h3>Hubungi JANS</h3>\r\n");
      out.write("                <p class=\"contact-line\"><a class=\"contact-address-link\" href=\"https://www.google.com/maps/place/Jabatan+Air+Negeri+Sabah/data=!4m7!3m6!1s0x323b69b770552161:0x46ddcd3e362b7115!8m2!3d5.9610727!4d116.0687216!16s%2Fg%2F1pzrm3yct!19sChIJYSFVcLdpOzIRFXErNj7N3UY?authuser=0&hl=en&rclk=1\" target=\"_blank\" rel=\"noopener noreferrer\">SABAH WATER DEPARTMENT</a></p>\r\n");
      out.write("                <p class=\"contact-line\"><a class=\"contact-address-link\" href=\"https://www.google.com/maps/place/Jabatan+Air+Negeri+Sabah/data=!4m7!3m6!1s0x323b69b770552161:0x46ddcd3e362b7115!8m2!3d5.9610727!4d116.0687216!16s%2Fg%2F1pzrm3yct!19sChIJYSFVcLdpOzIRFXErNj7N3UY?authuser=0&hl=en&rclk=1\" target=\"_blank\" rel=\"noopener noreferrer\">Tingkat 6, Blok A, Wisma MUIS, Beg Berkunci No. 210, 88825</a></p>\r\n");
      out.write("                <p class=\"contact-line\"><a class=\"contact-address-link\" href=\"https://www.google.com/maps/place/Jabatan+Air+Negeri+Sabah/data=!4m7!3m6!1s0x323b69b770552161:0x46ddcd3e362b7115!8m2!3d5.9610727!4d116.0687216!16s%2Fg%2F1pzrm3yct!19sChIJYSFVcLdpOzIRFXErNj7N3UY?authuser=0&hl=en&rclk=1\" target=\"_blank\" rel=\"noopener noreferrer\">Kota Kinabalu, Sabah, Malaysia</a></p>\r\n");
      out.write("                <p class=\"contact-line\"><span>Tel: +60-88-232364 (HQ) , Fax: +60-88-232396</span></p>\r\n");
      out.write("                <p class=\"contact-line\"><span>Email: jans.hq@sabah.gov.my</span></p></div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <footer>\r\n");
      out.write("        <p>&copy; 2026 Sistem Pendaftaran Pembekal dan Produk Air (SPPPA). Semua hak terpelihara.</p>\r\n");
      out.write("        <p>Jabatan Air Negeri Sabah</p>\r\n");
      out.write("        <p class=\"footer-links\">\r\n");
      out.write("            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/privacy-policy\">Dasar Privasi</a>\r\n");
      out.write("            |\r\n");
      out.write("            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/terms\">Terma Penggunaan</a>\r\n");
      out.write("        </p>\r\n");
      out.write("    </footer>\r\n");
      out.write("    <a class=\"floating-home-btn\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/\" aria-label=\"Laman utama\" title=\"Laman utama\">\r\n");
      out.write("        <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/images/icon-home.png\" alt=\"Laman utama\" style=\"width:18px;height:18px;object-fit:contain;\">\r\n");
      out.write("    </a>\r\n");
      out.write("<script>\r\n");
      out.write("(function() {\r\n");
      out.write("    var homeBtn = document.querySelector('.floating-home-btn');\r\n");
      out.write("    if (homeBtn) return;\r\n");
      out.write("\r\n");
      out.write("    var navContainer =document.querySelector('.nav-action > div:last-child');\r\n");
      out.write("    if (!navContainer) navContainer = document.querySelector('.nav-actions');\r\n");
      out.write("    if (!navContainer) return;\r\n");
      out.write("\r\n");
      out.write("    if (homeBtn.parentElement !== navContainer) {\r\n");
      out.write("        navContainer.appendChild(homeBtn);\r\n");
      out.write("    }\r\n");
      out.write("})();\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
