/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/11.0.18
 * Generated at: 2026-03-24 04:36:07 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ms\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Sistem Pendaftaran Produk Air (SPPA)</title>\r\n");
      out.write("    <style>\r\n");
      out.write("        :root {\r\n");
      out.write("            --brand-blue: #0097d9;\r\n");
      out.write("            --brand-navy: #06344f;\r\n");
      out.write("            --brand-yellow: #fff212;\r\n");
      out.write("            --text: #173040;\r\n");
      out.write("            --muted: #64808f;\r\n");
      out.write("        }\r\n");
      out.write("        * { margin: 0; padding: 0; box-sizing: border-box; }\r\n");
      out.write("        body { font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; line-height: 1.6; color: var(--text); background: #f8fbfd; }\r\n");
      out.write("        .navbar { background: linear-gradient(130deg, var(--brand-navy) 0%, var(--brand-blue) 74%, var(--brand-yellow) 190%); color: white; padding: 16px 30px; display: flex; justify-content: space-between; align-items: center; }\r\n");
      out.write("        .brand { display: flex; align-items: center; gap: 14px; }\r\n");
      out.write("        .brand-logos { display: flex; align-items: center; gap: 10px; }\r\n");
      out.write("        .brand-logo { width: 52px; height: 52px; border-radius: 16px; object-fit: contain; padding: 4px; }\r\n");
      out.write("        .brand-text strong { display: block; font-size: 18px; }\r\n");
      out.write("        .brand-text span { font-size: 12px; opacity: 0.88; }\r\n");
      out.write("        .navbar a { color: white; text-decoration: none; margin-left: 20px; font-weight: 600; }\r\n");
      out.write("        .hero { position: relative; overflow: hidden; background: linear-gradient(135deg, #06344f 0%, #0097d9 62%, #fff4a5 180%); color: white; padding: 72px 30px; }\r\n");
      out.write("        .hero::after { content: \"\"; position: absolute; right: -40px; top: -30px; width: 220px; height: 220px; border-radius: 50%; background: rgba(255, 242, 18, 0.24); }\r\n");
      out.write("        .hero-watermark { position: absolute; inset: 0; width: 100%; height: 100%; object-fit: contain; object-position: center; opacity: 0.08; pointer-events: none; z-index: 0; padding: 40px; }\r\n");
      out.write("        .hero-inner { max-width: 1200px; margin: 0 auto; display: grid; grid-template-columns: 1.5fr 1fr; gap: 24px; align-items: center; }\r\n");
      out.write("        .hero h1 { font-size: 44px; margin-bottom: 14px; max-width: 760px; }\r\n");
      out.write("        .hero p { font-size: 18px; margin-bottom: 26px; max-width: 700px; }\r\n");
      out.write("        .hero-btn { display: inline-block; padding: 12px 28px; color: #fff; text-decoration: none; border-radius: 999px; font-weight: 700; margin: 10px 10px 0 0; border: 2px solid #fff; background: rgba(255, 255, 255, 0.08); box-shadow: inset 0 0 0 1px rgba(255, 255, 255, 0.5); }\r\n");
      out.write("        .hero-btn:hover, .hero-btn:focus { background: rgba(255, 255, 255, 0.16); border-color: #fff; color: #fff; }\r\n");
      out.write("        .hero-side { background: rgba(255, 255, 255, 0.14); backdrop-filter: blur(8px); border: 1px solid rgba(255,255,255,0.24); border-radius: 22px; padding: 18px; }\r\n");
      out.write("        .hero-contact { width: 100%; border-radius: 16px; border: 1px solid rgba(255,255,255,0.28); background: rgba(6, 52, 79, 0.35); padding: 16px; }\r\n");
      out.write("        .hero-contact h3 { margin: 0 0 10px; font-size: 16px; }\r\n");
      out.write("        .hero-contact p { margin: 6px 0; font-size: 14px; }\r\n");
      out.write("        .container { max-width: 1200px; margin: 0 auto; padding: 44px 20px; }\r\n");
      out.write("        footer { background: #072d43; color: white; text-align: center; padding: 30px; }\r\n");
      out.write("        @media (max-width: 960px) { .hero-inner { grid-template-columns: 1fr; } .navbar { flex-direction: column; align-items: flex-start; gap: 12px; } .navbar a { margin-left: 0; margin-right: 16px; } }\r\n");
      out.write("                    /* Enforce visible white border on all clickable buttons */\r\n");
      out.write("        button,\r\n");
      out.write("        input[type=\"submit\"],\r\n");
      out.write("        input[type=\"button\"],\r\n");
      out.write("        .btn,\r\n");
      out.write("        .login-btn,\r\n");
      out.write("        .modal-close,\r\n");
      out.write("        .btn-attachment,\r\n");
      out.write("        .attachment-list button,\r\n");
      out.write("        a.btn {\r\n");
      out.write("            border: 1px solid #fff !important;\r\n");
      out.write("            box-shadow: inset 0 0 0 1px #fff, 0 1px 2px rgba(0, 0, 0, 0.18) !important;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        button:hover,\r\n");
      out.write("        input[type=\"submit\"]:hover,\r\n");
      out.write("        input[type=\"button\"]:hover,\r\n");
      out.write("        .btn:hover,\r\n");
      out.write("        .login-btn:hover,\r\n");
      out.write("        .modal-close:hover,\r\n");
      out.write("        .btn-attachment:hover,\r\n");
      out.write("        .attachment-list button:hover,\r\n");
      out.write("        a.btn:hover,\r\n");
      out.write("        button:focus,\r\n");
      out.write("        input[type=\"submit\"]:focus,\r\n");
      out.write("        input[type=\"button\"]:focus,\r\n");
      out.write("        .btn:focus,\r\n");
      out.write("        .login-btn:focus,\r\n");
      out.write("        .modal-close:focus,\r\n");
      out.write("        .btn-attachment:focus,\r\n");
      out.write("        .attachment-list button:focus,\r\n");
      out.write("        a.btn:focus {\r\n");
      out.write("            border: 1px solid #fff !important;\r\n");
      out.write("            box-shadow: inset 0 0 0 1px #fff, 0 0 0 2px rgba(255, 255, 255, 0.35), 0 1px 2px rgba(0, 0, 0, 0.18) !important;\r\n");
      out.write("        }</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <div class=\"navbar\">\r\n");
      out.write("        <div class=\"brand\">\r\n");
      out.write("            <div class=\"brand-logos\">\r\n");
      out.write("                <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/images/logo-sabah-2025.png?v=3\" class=\"brand-logo\" alt=\"Logo Sabah\">\r\n");
      out.write("                <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/images/logo-jabatan-air-sabah.png?v=4\" class=\"brand-logo\" alt=\"Logo Jabatan Air Sabah\">\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"brand-text\">\r\n");
      out.write("                <strong>SPPA</strong>\r\n");
      out.write("                <span>Jabatan Air Negeri Sabah</span>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div>\r\n");
      out.write("            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/login\">Log Masuk</a>\r\n");
      out.write("            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/register\">Daftar Pemohon</a>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"hero\">\r\n");
      out.write("        <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/images/jabatan-air-sabah-bg.png\" class=\"hero-watermark\" alt=\"\" aria-hidden=\"true\">\r\n");
      out.write("        <div class=\"hero-inner\" style=\"position:relative;z-index:1;\">\r\n");
      out.write("            <div>\r\n");
      out.write("                <h1>Selamat datang ke Sistem Pendaftaran Produk Air</h1>\r\n");
      out.write("                <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/login\" class=\"hero-btn\">Log Masuk</a>\r\n");
      out.write("                <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/register\" class=\"hero-btn\">Buka Akaun Pemohon</a>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"hero-side\">\r\n");
      out.write("                <div class=\"hero-contact\" aria-label=\"Maklumat hubungan Jabatan Air Sabah\">\r\n");
      out.write("                    <h3>Hubungi JANS</h3>\r\n");
      out.write("                    <p>Telefon: 088-326888</p>\r\n");
      out.write("                    <p>Email: info@jwater.gov.my</p>\r\n");
      out.write("                    <p>Alamat: Kota Kinabalu, Sabah</p>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <footer>\r\n");
      out.write("        <p>&copy; 2026 Sistem Pendaftaran Produk Air (SPPA). Semua hak terpelihara.</p>\r\n");
      out.write("        <p>Jabatan Air Negeri Sabah</p>\r\n");
      out.write("    </footer>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
