/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/11.0.18
 * Generated at: 2026-06-10 06:54:47 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.lang.String;
import java.util.Map;

public final class kpp_002dguest_002dform_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {


    private String escapeJs(String value) {
        if (value == null) {
            return "";
        }
        return value
                .replace("\\", "\\\\")
                .replace("\"", "\\\"")
                .replace("\r", "\\r")
                .replace("\n", "\\n");
    }

    private String safePrefill(Map<String, String> data, String key) {
        if (data == null || key == null) {
            return "";
        }
        String value = data.get(key);
        return value == null ? "" : value;
    }

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(3);
    _jspx_imports_classes.add("java.util.Map");
    _jspx_imports_classes.add("java.lang.String");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ms\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Borang Digital KPP Guest</title>\r\n");
      out.write("    <style>\r\n");
      out.write("        * { box-sizing: border-box; }\r\n");
      out.write("        body {\r\n");
      out.write("            margin: 0;\r\n");
      out.write("            font-family: \"Segoe UI\", Arial, sans-serif;\r\n");
      out.write("            background: #eef4f8;\r\n");
      out.write("            color: #0f172a;\r\n");
      out.write("        }\r\n");
      out.write("        .top {\r\n");
      out.write("            background: #123b64;\r\n");
      out.write("            color: #fff;\r\n");
      out.write("            padding: 12px 18px;\r\n");
      out.write("            font-weight: 700;\r\n");
      out.write("        }\r\n");
      out.write("        .wrap {\r\n");
      out.write("            max-width: 980px;\r\n");
      out.write("            margin: 18px auto 34px;\r\n");
      out.write("            padding: 0 14px;\r\n");
      out.write("        }\r\n");
      out.write("        .card {\r\n");
      out.write("            background: #fff;\r\n");
      out.write("            border: 1px solid #d2deea;\r\n");
      out.write("            border-radius: 12px;\r\n");
      out.write("            box-shadow: 0 14px 30px rgba(2, 44, 74, 0.1);\r\n");
      out.write("            padding: 18px;\r\n");
      out.write("        }\r\n");
      out.write("        .meta {\r\n");
      out.write("            background: #f8fbff;\r\n");
      out.write("            border: 1px solid #d8e7f7;\r\n");
      out.write("            border-radius: 10px;\r\n");
      out.write("            padding: 10px 12px;\r\n");
      out.write("            margin-bottom: 12px;\r\n");
      out.write("            font-size: 0.95rem;\r\n");
      out.write("            color: #334155;\r\n");
      out.write("        }\r\n");
      out.write("        .ok {\r\n");
      out.write("            background: #ecfdf3;\r\n");
      out.write("            border: 1px solid #86efac;\r\n");
      out.write("            color: #166534;\r\n");
      out.write("            border-radius: 10px;\r\n");
      out.write("            padding: 10px 12px;\r\n");
      out.write("            margin-bottom: 12px;\r\n");
      out.write("            font-size: 0.93rem;\r\n");
      out.write("        }\r\n");
      out.write("        .section {\r\n");
      out.write("            border: 1px solid #e2e8f0;\r\n");
      out.write("            border-radius: 10px;\r\n");
      out.write("            padding: 14px;\r\n");
      out.write("            margin-bottom: 12px;\r\n");
      out.write("        }\r\n");
      out.write("        .section h2 {\r\n");
      out.write("            margin: 0 0 10px;\r\n");
      out.write("            font-size: 1.02rem;\r\n");
      out.write("            color: #0b3e6f;\r\n");
      out.write("        }\r\n");
      out.write("        .section h3 {\r\n");
      out.write("            margin: 8px 0 10px;\r\n");
      out.write("            font-size: 0.95rem;\r\n");
      out.write("            color: #0f172a;\r\n");
      out.write("        }\r\n");
      out.write("        .grid {\r\n");
      out.write("            display: grid;\r\n");
      out.write("            grid-template-columns: 1fr 1fr;\r\n");
      out.write("            gap: 10px;\r\n");
      out.write("        }\r\n");
      out.write("        .field {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            flex-direction: column;\r\n");
      out.write("            gap: 6px;\r\n");
      out.write("        }\r\n");
      out.write("        .field-full { grid-column: 1 / -1; }\r\n");
      out.write("        label {\r\n");
      out.write("            font-size: 0.88rem;\r\n");
      out.write("            color: #334155;\r\n");
      out.write("            font-weight: 600;\r\n");
      out.write("        }\r\n");
      out.write("        input, select, textarea {\r\n");
      out.write("            border: 1px solid #c9d7e5;\r\n");
      out.write("            border-radius: 9px;\r\n");
      out.write("            padding: 10px;\r\n");
      out.write("            font-size: 0.93rem;\r\n");
      out.write("            font-family: inherit;\r\n");
      out.write("            width: 100%;\r\n");
      out.write("        }\r\n");
      out.write("        textarea { min-height: 90px; resize: vertical; }\r\n");
      out.write("        [data-locked-field=\"1\"] {\r\n");
      out.write("            background: #f3f7fb;\r\n");
      out.write("            color: #496073;\r\n");
      out.write("        }\r\n");
      out.write("        .checklist {\r\n");
      out.write("            display: grid;\r\n");
      out.write("            gap: 8px;\r\n");
      out.write("        }\r\n");
      out.write("        .check-item {\r\n");
      out.write("            border: 1px solid #dbe5ef;\r\n");
      out.write("            border-radius: 8px;\r\n");
      out.write("            padding: 10px;\r\n");
      out.write("            background: #f9fcff;\r\n");
      out.write("        }\r\n");
      out.write("        .check-item p {\r\n");
      out.write("            margin: 0 0 8px;\r\n");
      out.write("            font-size: 0.9rem;\r\n");
      out.write("            font-weight: 600;\r\n");
      out.write("            color: #1e293b;\r\n");
      out.write("        }\r\n");
      out.write("        .check-grid {\r\n");
      out.write("            display: grid;\r\n");
      out.write("            grid-template-columns: 220px 1fr;\r\n");
      out.write("            gap: 8px;\r\n");
      out.write("        }\r\n");
      out.write("        .radio-row {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            flex-wrap: wrap;\r\n");
      out.write("            gap: 10px;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            min-height: 40px;\r\n");
      out.write("        }\r\n");
      out.write("        .radio-row label {\r\n");
      out.write("            display: inline-flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            gap: 5px;\r\n");
      out.write("            font-weight: 500;\r\n");
      out.write("            font-size: 0.88rem;\r\n");
      out.write("            color: #1f2937;\r\n");
      out.write("        }\r\n");
      out.write("        .radio-row input[type=\"radio\"] {\r\n");
      out.write("            width: auto;\r\n");
      out.write("            margin: 0;\r\n");
      out.write("            padding: 0;\r\n");
      out.write("        }\r\n");
      out.write("        .submit-row {\r\n");
      out.write("            margin-top: 10px;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            justify-content: flex-end;\r\n");
      out.write("        }\r\n");
      out.write("        button {\r\n");
      out.write("            border: 0;\r\n");
      out.write("            border-radius: 10px;\r\n");
      out.write("            background: #0b5cab;\r\n");
      out.write("            color: #fff;\r\n");
      out.write("            font-size: 0.95rem;\r\n");
      out.write("            font-weight: 700;\r\n");
      out.write("            padding: 11px 16px;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("        }\r\n");
      out.write("        @media (max-width: 760px) {\r\n");
      out.write("            .grid { grid-template-columns: 1fr; }\r\n");
      out.write("            .check-grid { grid-template-columns: 1fr; }\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");

    String actionType = request.getAttribute("kppActionType") == null ? "" : String.valueOf(request.getAttribute("kppActionType"));
    String applicationRef = request.getAttribute("kppApplicationRef") == null ? "" : String.valueOf(request.getAttribute("kppApplicationRef"));
    String token = request.getAttribute("kppToken") == null ? "" : String.valueOf(request.getAttribute("kppToken"));
    boolean formSaved = Boolean.TRUE.equals(request.getAttribute("kppFormSaved"));
    boolean showKspp = "KSPP".equals(actionType) || "KSPP_UJPPP".equals(actionType);
    boolean showUjppp = "UJPPP".equals(actionType) || "KSPP_UJPPP".equals(actionType);
    Map<String, String> prefillData = (Map<String, String>) request.getAttribute("kppPrefillData");
    if (prefillData == null) {
        prefillData = java.util.Collections.emptyMap();
    }

      out.write("\r\n");
      out.write("<div class=\"top\">SPPPA GUEST</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"wrap\">\r\n");
      out.write("    <div class=\"card\" id=\"kppGuestForm\" data-storage-key=\"kpp-guest-");
      out.print( token.hashCode() );
      out.write("\" data-show-kspp=\"");
      out.print( showKspp );
      out.write("\" data-show-ujppp=\"");
      out.print( showUjppp );
      out.write("\">\r\n");
      out.write("        ");
 if (formSaved) { 
      out.write("\r\n");
      out.write("        <div class=\"ok\">Borang digital berjaya dihantar. Data telah disimpan oleh sistem SPPPA.</div>\r\n");
      out.write("        ");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <form method=\"post\" action=\"");
      out.print( request.getContextPath() );
      out.write("/kpp/guest-access\">\r\n");
      out.write("            <input type=\"hidden\" name=\"flow_action\" value=\"save_form\">\r\n");
      out.write("            <input type=\"hidden\" name=\"token\" value=\"");
      out.print( token );
      out.write("\">\r\n");
      out.write("            <input type=\"hidden\" name=\"_csrf\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${csrf_token}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("            <input type=\"hidden\" name=\"f_application_ref\" value=\"");
      out.print( applicationRef );
      out.write("\">\r\n");
      out.write("\r\n");
      out.write("            ");
 if (!applicationRef.isBlank()) { 
      out.write("\r\n");
      out.write("            <div class=\"meta\">Borang Permohonan Dirujuk: <strong>");
      out.print( applicationRef );
      out.write("</strong></div>\r\n");
      out.write("            ");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("            <div class=\"section\">\r\n");
      out.write("                <h2>Bahagian A: Maklumat Responden</h2>\r\n");
      out.write("                <div class=\"grid\">\r\n");
      out.write("                    <div class=\"field\"><label>Nama Penuh</label><input name=\"f_respondent_name\" data-field=\"f_respondent_name\" required></div>\r\n");
      out.write("                    <div class=\"field\"><label>Cawangan / Jabatan Air Daerah</label><input name=\"f_respondent_branch\" data-field=\"f_respondent_branch\"></div>\r\n");
      out.write("                    <div class=\"field\"><label>Jawatan Hakiki &amp; Gred</label><input name=\"f_respondent_position_grade\" data-field=\"f_respondent_position_grade\"></div>\r\n");
      out.write("                    <div class=\"field\"><label>Gelaran Jawatan</label><input name=\"f_respondent_title\" data-field=\"f_respondent_title\"></div>\r\n");
      out.write("                    <div class=\"field\"><label>No. Telefon</label><input name=\"f_phone\" data-field=\"f_phone\"></div>\r\n");
      out.write("                    <div class=\"field\"><label>Emel Rasmi Kerajaan</label><input type=\"email\" name=\"f_respondent_official_email\" data-field=\"f_respondent_official_email\"></div>\r\n");
      out.write("                    <div class=\"field\"><label>Tempoh Berkhidmat</label><input name=\"f_respondent_service_period\" data-field=\"f_respondent_service_period\"></div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            ");
 if (showKspp) { 
      out.write("\r\n");
      out.write("            <div class=\"section\">\r\n");
      out.write("                <h2>Borang Kaji Selidik Prestasi Pembekal dan Produk Bekalan Air (KSPP)</h2>\r\n");
      out.write("                <h3>Bahagian B: Maklumat Produk</h3>\r\n");
      out.write("                <div class=\"grid\">\r\n");
      out.write("                    <div class=\"field\"><label>Nama Produk</label><input name=\"f_kspp_product_name\" data-field=\"f_kspp_product_name\"></div>\r\n");
      out.write("                    <div class=\"field\"><label>Jenama</label><input name=\"f_kspp_brand\" data-field=\"f_kspp_brand\"></div>\r\n");
      out.write("                    <div class=\"field field-full\"><label>Perihal Produk (Model/Kelas/Saiz)</label><textarea name=\"f_kspp_product_desc\" data-field=\"f_kspp_product_desc\"></textarea></div>\r\n");
      out.write("                    <div class=\"field\"><label>Tarikh Mula &amp; Siap</label><input name=\"f_kspp_start_end_date\" data-field=\"f_kspp_start_end_date\"></div>\r\n");
      out.write("                    <div class=\"field\"><label>% Siap</label><input name=\"f_kspp_completion_percent\" data-field=\"f_kspp_completion_percent\"></div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <h3>Bahagian C: Maklumat Pembekal dan Produk</h3>\r\n");
      out.write("                <div class=\"grid\">\r\n");
      out.write("                    <div class=\"field\"><label>Nama Pembekal</label><input name=\"f_kspp_supplier_name\" data-field=\"f_kspp_supplier_name\"></div>\r\n");
      out.write("                    <div class=\"field\"><label>Nama Produk</label><input name=\"f_kspp_supplier_product_name\" data-field=\"f_kspp_supplier_product_name\"></div>\r\n");
      out.write("                    <div class=\"field\"><label>Jenama</label><input name=\"f_kspp_supplier_brand\" data-field=\"f_kspp_supplier_brand\"></div>\r\n");
      out.write("                    <div class=\"field field-full\"><label>Perihal Produk (Model/Kelas/Saiz/dll)</label><textarea name=\"f_kspp_supplier_product_desc\" data-field=\"f_kspp_supplier_product_desc\"></textarea></div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <h3>Bahagian D: Prestasi Pembekal dan Produk</h3>\r\n");
      out.write("                <div class=\"checklist\">\r\n");
      out.write("                    <div class=\"check-item\"><p>1. Adakah Perakuan Pendaftaran Pembekal dan Produk JA Sabah masih sah?</p><div class=\"check-grid\"><div class=\"radio-row\"><label><input type=\"radio\" name=\"f_kspp_q1\" value=\"Ya\" data-field=\"f_kspp_q1\">Ya</label><label><input type=\"radio\" name=\"f_kspp_q1\" value=\"Tidak\" data-field=\"f_kspp_q1\">Tidak</label><label><input type=\"radio\" name=\"f_kspp_q1\" value=\"Tidak Berkenaan\" data-field=\"f_kspp_q1\">Tidak Berkenaan</label></div><input name=\"f_kspp_q1_note\" data-field=\"f_kspp_q1_note\" placeholder=\"Catatan\"></div></div>\r\n");
      out.write("                    <div class=\"check-item\"><p>2. Adakah Surat Pelantikan Pembekal Produk dari syarikat prinsipal/pemilik produk masih sah?</p><div class=\"check-grid\"><div class=\"radio-row\"><label><input type=\"radio\" name=\"f_kspp_q2\" value=\"Ya\" data-field=\"f_kspp_q2\">Ya</label><label><input type=\"radio\" name=\"f_kspp_q2\" value=\"Tidak\" data-field=\"f_kspp_q2\">Tidak</label><label><input type=\"radio\" name=\"f_kspp_q2\" value=\"Tidak Berkenaan\" data-field=\"f_kspp_q2\">Tidak Berkenaan</label></div><input name=\"f_kspp_q2_note\" data-field=\"f_kspp_q2_note\" placeholder=\"Catatan\"></div></div>\r\n");
      out.write("                    <div class=\"check-item\"><p>3. Adakah dokumen jaminan produk masih sah?</p><div class=\"check-grid\"><div class=\"radio-row\"><label><input type=\"radio\" name=\"f_kspp_q3\" value=\"Ya\" data-field=\"f_kspp_q3\">Ya</label><label><input type=\"radio\" name=\"f_kspp_q3\" value=\"Tidak\" data-field=\"f_kspp_q3\">Tidak</label><label><input type=\"radio\" name=\"f_kspp_q3\" value=\"Tidak Berkenaan\" data-field=\"f_kspp_q3\">Tidak Berkenaan</label></div><input name=\"f_kspp_q3_note\" data-field=\"f_kspp_q3_note\" placeholder=\"Catatan\"></div></div>\r\n");
      out.write("                    <div class=\"check-item\"><p>4. Adakah sokongan teknikal (perkhidmatan selepas jualan) tersedia di Sabah?</p><div class=\"check-grid\"><div class=\"radio-row\"><label><input type=\"radio\" name=\"f_kspp_q4\" value=\"Ya\" data-field=\"f_kspp_q4\">Ya</label><label><input type=\"radio\" name=\"f_kspp_q4\" value=\"Tidak\" data-field=\"f_kspp_q4\">Tidak</label><label><input type=\"radio\" name=\"f_kspp_q4\" value=\"Tidak Berkenaan\" data-field=\"f_kspp_q4\">Tidak Berkenaan</label></div><input name=\"f_kspp_q4_note\" data-field=\"f_kspp_q4_note\" placeholder=\"Catatan\"></div></div>\r\n");
      out.write("                    <div class=\"check-item\"><p>5. Adakah mudah dihubungi pada bila-bila masa?</p><div class=\"check-grid\"><div class=\"radio-row\"><label><input type=\"radio\" name=\"f_kspp_q5\" value=\"Ya\" data-field=\"f_kspp_q5\">Ya</label><label><input type=\"radio\" name=\"f_kspp_q5\" value=\"Tidak\" data-field=\"f_kspp_q5\">Tidak</label><label><input type=\"radio\" name=\"f_kspp_q5\" value=\"Tidak Berkenaan\" data-field=\"f_kspp_q5\">Tidak Berkenaan</label></div><input name=\"f_kspp_q5_note\" data-field=\"f_kspp_q5_note\" placeholder=\"Catatan\"></div></div>\r\n");
      out.write("                    <div class=\"check-item\"><p>6. Adakah jadual penghantaran produk ke lokasi dipatuhi?</p><div class=\"check-grid\"><div class=\"radio-row\"><label><input type=\"radio\" name=\"f_kspp_q6\" value=\"Ya\" data-field=\"f_kspp_q6\">Ya</label><label><input type=\"radio\" name=\"f_kspp_q6\" value=\"Tidak\" data-field=\"f_kspp_q6\">Tidak</label><label><input type=\"radio\" name=\"f_kspp_q6\" value=\"Tidak Berkenaan\" data-field=\"f_kspp_q6\">Tidak Berkenaan</label></div><input name=\"f_kspp_q6_note\" data-field=\"f_kspp_q6_note\" placeholder=\"Catatan\"></div></div>\r\n");
      out.write("                    <div class=\"check-item\"><p>7. Adakah Prosedur Operasi Standard (SOP) untuk penghantaran dan pengendalian produk dari kilang ke lokasi tapak bina dipatuhi?</p><div class=\"check-grid\"><div class=\"radio-row\"><label><input type=\"radio\" name=\"f_kspp_q7\" value=\"Ya\" data-field=\"f_kspp_q7\">Ya</label><label><input type=\"radio\" name=\"f_kspp_q7\" value=\"Tidak\" data-field=\"f_kspp_q7\">Tidak</label><label><input type=\"radio\" name=\"f_kspp_q7\" value=\"Tidak Berkenaan\" data-field=\"f_kspp_q7\">Tidak Berkenaan</label></div><input name=\"f_kspp_q7_note\" data-field=\"f_kspp_q7_note\" placeholder=\"Catatan\"></div></div>\r\n");
      out.write("                    <div class=\"check-item\"><p>8. Adakah produk disimpan di lokasi yang sesuai dan tempat selamat seperti yang diarahkan?</p><div class=\"check-grid\"><div class=\"radio-row\"><label><input type=\"radio\" name=\"f_kspp_q8\" value=\"Ya\" data-field=\"f_kspp_q8\">Ya</label><label><input type=\"radio\" name=\"f_kspp_q8\" value=\"Tidak\" data-field=\"f_kspp_q8\">Tidak</label><label><input type=\"radio\" name=\"f_kspp_q8\" value=\"Tidak Berkenaan\" data-field=\"f_kspp_q8\">Tidak Berkenaan</label></div><input name=\"f_kspp_q8_note\" data-field=\"f_kspp_q8_note\" placeholder=\"Catatan\"></div></div>\r\n");
      out.write("                    <div class=\"check-item\"><p>9. Adakah undang-undang dan peraturan yang terpakai, berkelakuan beretika dan berintegriti dipatuhi?</p><div class=\"check-grid\"><div class=\"radio-row\"><label><input type=\"radio\" name=\"f_kspp_q9\" value=\"Ya\" data-field=\"f_kspp_q9\">Ya</label><label><input type=\"radio\" name=\"f_kspp_q9\" value=\"Tidak\" data-field=\"f_kspp_q9\">Tidak</label><label><input type=\"radio\" name=\"f_kspp_q9\" value=\"Tidak Berkenaan\" data-field=\"f_kspp_q9\">Tidak Berkenaan</label></div><input name=\"f_kspp_q9_note\" data-field=\"f_kspp_q9_note\" placeholder=\"Catatan\"></div></div>\r\n");
      out.write("                    <div class=\"check-item\"><p>10. Adakah amalan pelaksanaan kerja mengurangkan kesan/impak negatif terhadap alam sekitar dipatuhi?</p><div class=\"check-grid\"><div class=\"radio-row\"><label><input type=\"radio\" name=\"f_kspp_q10\" value=\"Ya\" data-field=\"f_kspp_q10\">Ya</label><label><input type=\"radio\" name=\"f_kspp_q10\" value=\"Tidak\" data-field=\"f_kspp_q10\">Tidak</label><label><input type=\"radio\" name=\"f_kspp_q10\" value=\"Tidak Berkenaan\" data-field=\"f_kspp_q10\">Tidak Berkenaan</label></div><input name=\"f_kspp_q10_note\" data-field=\"f_kspp_q10_note\" placeholder=\"Catatan\"></div></div>\r\n");
      out.write("                    <div class=\"check-item\"><p>11. Adakah aspek keselamatan dan kesihatan pekerjaan dipatuhi?</p><div class=\"check-grid\"><div class=\"radio-row\"><label><input type=\"radio\" name=\"f_kspp_q11\" value=\"Ya\" data-field=\"f_kspp_q11\">Ya</label><label><input type=\"radio\" name=\"f_kspp_q11\" value=\"Tidak\" data-field=\"f_kspp_q11\">Tidak</label><label><input type=\"radio\" name=\"f_kspp_q11\" value=\"Tidak Berkenaan\" data-field=\"f_kspp_q11\">Tidak Berkenaan</label></div><input name=\"f_kspp_q11_note\" data-field=\"f_kspp_q11_note\" placeholder=\"Catatan\"></div></div>\r\n");
      out.write("                    <div class=\"check-item\"><p>12. Adakah pemasangan produk dieselia/dipantau sehingga selesai?</p><div class=\"check-grid\"><div class=\"radio-row\"><label><input type=\"radio\" name=\"f_kspp_q12\" value=\"Ya\" data-field=\"f_kspp_q12\">Ya</label><label><input type=\"radio\" name=\"f_kspp_q12\" value=\"Tidak\" data-field=\"f_kspp_q12\">Tidak</label><label><input type=\"radio\" name=\"f_kspp_q12\" value=\"Tidak Berkenaan\" data-field=\"f_kspp_q12\">Tidak Berkenaan</label></div><input name=\"f_kspp_q12_note\" data-field=\"f_kspp_q12_note\" placeholder=\"Catatan\"></div></div>\r\n");
      out.write("                    <div class=\"check-item\"><p>13. Adakah pengujian dan pentauliahan produk diasakna sehingga selesai?</p><div class=\"check-grid\"><div class=\"radio-row\"><label><input type=\"radio\" name=\"f_kspp_q13\" value=\"Ya\" data-field=\"f_kspp_q13\">Ya</label><label><input type=\"radio\" name=\"f_kspp_q13\" value=\"Tidak\" data-field=\"f_kspp_q13\">Tidak</label><label><input type=\"radio\" name=\"f_kspp_q13\" value=\"Tidak Berkenaan\" data-field=\"f_kspp_q13\">Tidak Berkenaan</label></div><input name=\"f_kspp_q13_note\" data-field=\"f_kspp_q13_note\" placeholder=\"Catatan\"></div></div>\r\n");
      out.write("                    <div class=\"check-item\"><p>14. Adakah produk yang rosak diganti ataupun dibaiki dengan segera?</p><div class=\"check-grid\"><div class=\"radio-row\"><label><input type=\"radio\" name=\"f_kspp_q14\" value=\"Ya\" data-field=\"f_kspp_q14\">Ya</label><label><input type=\"radio\" name=\"f_kspp_q14\" value=\"Tidak\" data-field=\"f_kspp_q14\">Tidak</label><label><input type=\"radio\" name=\"f_kspp_q14\" value=\"Tidak Berkenaan\" data-field=\"f_kspp_q14\">Tidak Berkenaan</label></div><input name=\"f_kspp_q14_note\" data-field=\"f_kspp_q14_note\" placeholder=\"Catatan\"></div></div>\r\n");
      out.write("                    <div class=\"check-item\"><p>15. Adakah Manual Operasi diberikan?</p><div class=\"check-grid\"><div class=\"radio-row\"><label><input type=\"radio\" name=\"f_kspp_q15\" value=\"Ya\" data-field=\"f_kspp_q15\">Ya</label><label><input type=\"radio\" name=\"f_kspp_q15\" value=\"Tidak\" data-field=\"f_kspp_q15\">Tidak</label><label><input type=\"radio\" name=\"f_kspp_q15\" value=\"Tidak Berkenaan\" data-field=\"f_kspp_q15\">Tidak Berkenaan</label></div><input name=\"f_kspp_q15_note\" data-field=\"f_kspp_q15_note\" placeholder=\"Catatan\"></div></div>\r\n");
      out.write("                    <div class=\"check-item\"><p>16. Adakah latihan operasi dan senggara produk diberikan?</p><div class=\"check-grid\"><div class=\"radio-row\"><label><input type=\"radio\" name=\"f_kspp_q16\" value=\"Ya\" data-field=\"f_kspp_q16\">Ya</label><label><input type=\"radio\" name=\"f_kspp_q16\" value=\"Tidak\" data-field=\"f_kspp_q16\">Tidak</label><label><input type=\"radio\" name=\"f_kspp_q16\" value=\"Tidak Berkenaan\" data-field=\"f_kspp_q16\">Tidak Berkenaan</label></div><input name=\"f_kspp_q16_note\" data-field=\"f_kspp_q16_note\" placeholder=\"Catatan\"></div></div>\r\n");
      out.write("                    <div class=\"check-item\"><p>17. Adakah produk yang dibekalkan memenuhi spesifikasi yang dititikrafkan, berfungsi dengan baik dan tidak ada kecacatan?</p><div class=\"check-grid\"><div class=\"radio-row\"><label><input type=\"radio\" name=\"f_kspp_q17\" value=\"Ya\" data-field=\"f_kspp_q17\">Ya</label><label><input type=\"radio\" name=\"f_kspp_q17\" value=\"Tidak\" data-field=\"f_kspp_q17\">Tidak</label><label><input type=\"radio\" name=\"f_kspp_q17\" value=\"Tidak Berkenaan\" data-field=\"f_kspp_q17\">Tidak Berkenaan</label></div><input name=\"f_kspp_q17_note\" data-field=\"f_kspp_q17_note\" placeholder=\"Catatan\"></div></div>\r\n");
      out.write("                    <div class=\"check-item\"><p>18. Adakah Sijil Penentukuran (Calibration) masih sah? (jika berkenaan)</p><div class=\"check-grid\"><div class=\"radio-row\"><label><input type=\"radio\" name=\"f_kspp_q18\" value=\"Ya\" data-field=\"f_kspp_q18\">Ya</label><label><input type=\"radio\" name=\"f_kspp_q18\" value=\"Tidak\" data-field=\"f_kspp_q18\">Tidak</label><label><input type=\"radio\" name=\"f_kspp_q18\" value=\"Tidak Berkenaan\" data-field=\"f_kspp_q18\">Tidak Berkenaan</label></div><input name=\"f_kspp_q18_note\" data-field=\"f_kspp_q18_note\" placeholder=\"Catatan\"></div></div>\r\n");
      out.write("                    <div class=\"check-item\"><p>19. Adakah produk mempunyai rekod prestasi yang tidak memuaskan/rosak dalam tempoh tanggungan kecacatan?</p><div class=\"check-grid\"><div class=\"radio-row\"><label><input type=\"radio\" name=\"f_kspp_q19\" value=\"Ya\" data-field=\"f_kspp_q19\">Ya</label><label><input type=\"radio\" name=\"f_kspp_q19\" value=\"Tidak\" data-field=\"f_kspp_q19\">Tidak</label><label><input type=\"radio\" name=\"f_kspp_q19\" value=\"Tidak Berkenaan\" data-field=\"f_kspp_q19\">Tidak Berkenaan</label></div><input name=\"f_kspp_q19_note\" data-field=\"f_kspp_q19_note\" placeholder=\"Catatan\"></div></div>\r\n");
      out.write("                    <div class=\"check-item\"><p>20. Adakah produk mempunyai rekod prestasi dalam tempoh lima (5) tahun selepas dipasang? Jika ya, sila sertakan.</p><div class=\"check-grid\"><div class=\"radio-row\"><label><input type=\"radio\" name=\"f_kspp_q20\" value=\"Ya\" data-field=\"f_kspp_q20\">Ya</label><label><input type=\"radio\" name=\"f_kspp_q20\" value=\"Tidak\" data-field=\"f_kspp_q20\">Tidak</label><label><input type=\"radio\" name=\"f_kspp_q20\" value=\"Tidak Berkenaan\" data-field=\"f_kspp_q20\">Tidak Berkenaan</label></div><input name=\"f_kspp_q20_note\" data-field=\"f_kspp_q20_note\" placeholder=\"Catatan\"></div></div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <h3>Bahagian E: Ulasan Terhadap Pembaharuan Perakuan</h3>\r\n");
      out.write("                <div class=\"grid\">\r\n");
      out.write("                    <div class=\"field\">\r\n");
      out.write("                        <label>Keputusan Ulasan</label>\r\n");
      out.write("                        <select name=\"f_kspp_review_decision\" data-field=\"f_kspp_review_decision\">\r\n");
      out.write("                            <option value=\"\">-- Pilih --</option>\r\n");
      out.write("                            <option value=\"Bersetuju\">Bersetuju</option>\r\n");
      out.write("                            <option value=\"Tidak Bersetuju\">Tidak Bersetuju</option>\r\n");
      out.write("                        </select>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"field\"><label>Tarikh</label><input type=\"date\" name=\"f_kspp_review_date\" data-field=\"f_kspp_review_date\"></div>\r\n");
      out.write("                    <div class=\"field field-full\"><label>Ulasan</label><textarea name=\"f_kspp_review_note\" data-field=\"f_kspp_review_note\"></textarea></div>\r\n");
      out.write("                    <div class=\"field\"><label>Nama</label><input name=\"f_kspp_sign_name\" data-field=\"f_kspp_sign_name\"></div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            ");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("            ");
 if (showUjppp) { 
      out.write("\r\n");
      out.write("            <div class=\"section\">\r\n");
      out.write("                <h2>Borang Ulasan Jawatankuasa Pendaftaran Pembekal dan Produk Bekalan Air (UJPPP)</h2>\r\n");
      out.write("                <h3>Bahagian A: Maklumat Pembekal / Pembuat / Prinsipal</h3>\r\n");
      out.write("                <div class=\"grid\">\r\n");
      out.write("                    <div class=\"field\"><label>Jenis Permohonan (Baharu / Pembaharuan)</label><input name=\"f_ujppp_application_type\" data-field=\"f_ujppp_application_type\"></div>\r\n");
      out.write("                    <div class=\"field field-full\"><label>Nama Syarikat Pembekal, Alamat Pejabat &amp; No. Telefon</label><textarea name=\"f_ujppp_supplier_company_info\" data-field=\"f_ujppp_supplier_company_info\"></textarea></div>\r\n");
      out.write("                    <div class=\"field field-full\"><label>Nama Syarikat Pembuat / Pengilang, Alamat Pejabat &amp; No. Telefon</label><textarea name=\"f_ujppp_manufacturer_company_info\" data-field=\"f_ujppp_manufacturer_company_info\"></textarea></div>\r\n");
      out.write("                    <div class=\"field field-full\"><label>Nama Syarikat Prinsipal / Pemilik Produk, Alamat Pejabat &amp; No. Telefon</label><textarea name=\"f_ujppp_principal_company_info\" data-field=\"f_ujppp_principal_company_info\"></textarea></div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <h3>Bahagian B: Maklumat Produk</h3>\r\n");
      out.write("                <div class=\"grid\">\r\n");
      out.write("                    <div class=\"field\"><label>Kategori</label><input name=\"f_ujppp_category\" data-field=\"f_ujppp_category\"></div>\r\n");
      out.write("                    <div class=\"field\"><label>Nama Produk</label><input name=\"f_ujppp_product_name\" data-field=\"f_ujppp_product_name\"></div>\r\n");
      out.write("                    <div class=\"field\"><label>Jenama</label><input name=\"f_ujppp_brand\" data-field=\"f_ujppp_brand\"></div>\r\n");
      out.write("                    <div class=\"field\"><label>Piawaian / Standard</label><input name=\"f_ujppp_standard\" data-field=\"f_ujppp_standard\"></div>\r\n");
      out.write("                    <div class=\"field field-full\"><label>Badan Persijilan &amp; No. Lesen Persijilan Barangan (Sah sehingga)</label><textarea name=\"f_ujppp_certification_body\" data-field=\"f_ujppp_certification_body\"></textarea></div>\r\n");
      out.write("                    <div class=\"field field-full\"><label>Badan Persijilan &amp; No. Laporan Pengujian (Tarikh dikeluarkan)</label><textarea name=\"f_ujppp_test_report\" data-field=\"f_ujppp_test_report\"></textarea></div>\r\n");
      out.write("                    <div class=\"field field-full\"><label>Perihal Produk (Model / Siri / Deskripsi)</label><textarea name=\"f_ujppp_product_desc\" data-field=\"f_ujppp_product_desc\"></textarea></div>\r\n");
      out.write("                    <div class=\"field\"><label>Tempoh Jaminan Produk (Tahun)</label><input name=\"f_ujppp_warranty_year\" data-field=\"f_ujppp_warranty_year\"></div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <h3>Bahagian C: Ulasan Jawatankuasa Pendaftaran Pembekal dan Produk Selaku Pengguna Produk</h3>\r\n");
      out.write("                <div class=\"grid\">\r\n");
      out.write("                    <div class=\"field\"><label>Tarikh</label><input type=\"date\" name=\"f_ujppp_review_date\" data-field=\"f_ujppp_review_date\"></div>\r\n");
      out.write("                    <div class=\"field field-full\"><label>Syor (diterima/ditolak/digantung/dibatal)</label><select name=\"f_ujppp_review_recommendation\" data-field=\"f_ujppp_review_recommendation\"><option value=\"\">-- Pilih --</option><option value=\"diterima\">diterima</option><option value=\"ditolak\">ditolak</option><option value=\"digantung\">digantung</option><option value=\"dibatal\">dibatal</option></select></div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            ");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("            <div class=\"submit-row\">\r\n");
      out.write("                <button type=\"submit\">Hantar</button>\r\n");
      out.write("            </div>\r\n");
      out.write("        </form>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("(function () {\r\n");
      out.write("    const box = document.getElementById('kppGuestForm');\r\n");
      out.write("    if (!box) return;\r\n");
      out.write("\r\n");
      out.write("    const storageKey = box.dataset.storageKey;\r\n");
      out.write("    const shouldLockKspp = box.dataset.showKspp === 'true';\r\n");
      out.write("    const shouldLockUjppp = box.dataset.showUjppp === 'true';\r\n");
      out.write("    const fields = Array.from(box.querySelectorAll('[data-field]'));\r\n");
      out.write("    const lockedPrefillData = {\r\n");
      out.write("        f_respondent_name: `");
      out.print( escapeJs(safePrefill(prefillData, "f_respondent_name")) );
      out.write("`,\r\n");
      out.write("        f_respondent_branch: `");
      out.print( escapeJs(safePrefill(prefillData, "f_respondent_branch")) );
      out.write("`,\r\n");
      out.write("        f_respondent_position_grade: `");
      out.print( escapeJs(safePrefill(prefillData, "f_respondent_position_grade")) );
      out.write("`,\r\n");
      out.write("        f_respondent_title: `");
      out.print( escapeJs(safePrefill(prefillData, "f_respondent_title")) );
      out.write("`,\r\n");
      out.write("        f_respondent_official_email: `");
      out.print( escapeJs(safePrefill(prefillData, "f_respondent_official_email")) );
      out.write("`,\r\n");
      out.write("        f_kspp_product_name: `");
      out.print( escapeJs(safePrefill(prefillData, "f_kspp_product_name")) );
      out.write("`,\r\n");
      out.write("        f_kspp_brand: `");
      out.print( escapeJs(safePrefill(prefillData, "f_kspp_brand")) );
      out.write("`,\r\n");
      out.write("        f_kspp_product_desc: `");
      out.print( escapeJs(safePrefill(prefillData, "f_kspp_product_desc")) );
      out.write("`,\r\n");
      out.write("        f_kspp_start_end_date: `");
      out.print( escapeJs(safePrefill(prefillData, "f_kspp_start_end_date")) );
      out.write("`,\r\n");
      out.write("        f_kspp_completion_percent: `");
      out.print( escapeJs(safePrefill(prefillData, "f_kspp_completion_percent")) );
      out.write("`,\r\n");
      out.write("        f_kspp_supplier_name: `");
      out.print( escapeJs(safePrefill(prefillData, "f_kspp_supplier_name")) );
      out.write("`,\r\n");
      out.write("        f_kspp_supplier_product_name: `");
      out.print( escapeJs(safePrefill(prefillData, "f_kspp_supplier_product_name")) );
      out.write("`,\r\n");
      out.write("        f_kspp_supplier_brand: `");
      out.print( escapeJs(safePrefill(prefillData, "f_kspp_supplier_brand")) );
      out.write("`,\r\n");
      out.write("        f_kspp_supplier_product_desc: `");
      out.print( escapeJs(safePrefill(prefillData, "f_kspp_supplier_product_desc")) );
      out.write("`,\r\n");
      out.write("        f_ujppp_application_type: `");
      out.print( escapeJs(safePrefill(prefillData, "f_ujppp_application_type")) );
      out.write("`,\r\n");
      out.write("        f_ujppp_supplier_company_info: `");
      out.print( escapeJs(safePrefill(prefillData, "f_ujppp_supplier_company_info")) );
      out.write("`,\r\n");
      out.write("        f_ujppp_manufacturer_company_info: `");
      out.print( escapeJs(safePrefill(prefillData, "f_ujppp_manufacturer_company_info")) );
      out.write("`,\r\n");
      out.write("        f_ujppp_principal_company_info: `");
      out.print( escapeJs(safePrefill(prefillData, "f_ujppp_principal_company_info")) );
      out.write("`,\r\n");
      out.write("        f_ujppp_category: `");
      out.print( escapeJs(safePrefill(prefillData, "f_ujppp_category")) );
      out.write("`,\r\n");
      out.write("        f_ujppp_product_name: `");
      out.print( escapeJs(safePrefill(prefillData, "f_ujppp_product_name")) );
      out.write("`,\r\n");
      out.write("        f_ujppp_brand: `");
      out.print( escapeJs(safePrefill(prefillData, "f_ujppp_brand")) );
      out.write("`,\r\n");
      out.write("        f_ujppp_standard: `");
      out.print( escapeJs(safePrefill(prefillData, "f_ujppp_standard")) );
      out.write("`,\r\n");
      out.write("        f_ujppp_certification_body: `");
      out.print( escapeJs(safePrefill(prefillData, "f_ujppp_certification_body")) );
      out.write("`,\r\n");
      out.write("        f_ujppp_test_report: `");
      out.print( escapeJs(safePrefill(prefillData, "f_ujppp_test_report")) );
      out.write("`,\r\n");
      out.write("        f_ujppp_product_desc: `");
      out.print( escapeJs(safePrefill(prefillData, "f_ujppp_product_desc")) );
      out.write("`,\r\n");
      out.write("        f_ujppp_warranty_year: `");
      out.print( escapeJs(safePrefill(prefillData, "f_ujppp_warranty_year")) );
      out.write("`\r\n");
      out.write("    };\r\n");
      out.write("    const ksppLockedFields = [\r\n");
      out.write("        'f_respondent_name',\r\n");
      out.write("        'f_respondent_branch',\r\n");
      out.write("        'f_respondent_position_grade',\r\n");
      out.write("        'f_respondent_title',\r\n");
      out.write("        'f_respondent_official_email',\r\n");
      out.write("        'f_kspp_product_name',\r\n");
      out.write("        'f_kspp_brand',\r\n");
      out.write("        'f_kspp_product_desc',\r\n");
      out.write("        'f_kspp_start_end_date',\r\n");
      out.write("        'f_kspp_completion_percent',\r\n");
      out.write("        'f_kspp_supplier_name',\r\n");
      out.write("        'f_kspp_supplier_product_name',\r\n");
      out.write("        'f_kspp_supplier_brand',\r\n");
      out.write("        'f_kspp_supplier_product_desc'\r\n");
      out.write("    ];\r\n");
      out.write("    const ujpppLockedFields = [\r\n");
      out.write("        'f_ujppp_application_type',\r\n");
      out.write("        'f_ujppp_supplier_company_info',\r\n");
      out.write("        'f_ujppp_manufacturer_company_info',\r\n");
      out.write("        'f_ujppp_principal_company_info',\r\n");
      out.write("        'f_ujppp_category',\r\n");
      out.write("        'f_ujppp_product_name',\r\n");
      out.write("        'f_ujppp_brand',\r\n");
      out.write("        'f_ujppp_standard',\r\n");
      out.write("        'f_ujppp_certification_body',\r\n");
      out.write("        'f_ujppp_test_report',\r\n");
      out.write("        'f_ujppp_product_desc',\r\n");
      out.write("        'f_ujppp_warranty_year'\r\n");
      out.write("    ];\r\n");
      out.write("    const activeLockedFields = [];\r\n");
      out.write("    if (shouldLockKspp) {\r\n");
      out.write("        ksppLockedFields.forEach((name) => activeLockedFields.push(name));\r\n");
      out.write("    }\r\n");
      out.write("    if (shouldLockUjppp) {\r\n");
      out.write("        ujpppLockedFields.forEach((name) => activeLockedFields.push(name));\r\n");
      out.write("    }\r\n");
      out.write("    const lockedFieldNames = new Set(activeLockedFields);\r\n");
      out.write("\r\n");
      out.write("    function isLockedField(field) {\r\n");
      out.write("        return !!field && lockedFieldNames.has(field.name || '');\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    function applyLockedPrefill() {\r\n");
      out.write("        activeLockedFields.forEach((fieldName) => {\r\n");
      out.write("            const fieldNodes = Array.from(box.querySelectorAll('[name=\"' + fieldName + '\"]'));\r\n");
      out.write("            fieldNodes.forEach((field) => {\r\n");
      out.write("                const value = Object.prototype.hasOwnProperty.call(lockedPrefillData, fieldName)\r\n");
      out.write("                    ? (lockedPrefillData[fieldName] || '')\r\n");
      out.write("                    : '';\r\n");
      out.write("                field.setAttribute('data-locked-field', '1');\r\n");
      out.write("                if (typeof field.readOnly !== 'undefined') {\r\n");
      out.write("                    field.readOnly = true;\r\n");
      out.write("                }\r\n");
      out.write("                if (field.tagName === 'INPUT' || field.tagName === 'TEXTAREA') {\r\n");
      out.write("                    field.value = value;\r\n");
      out.write("                }\r\n");
      out.write("            });\r\n");
      out.write("        });\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    function save() {\r\n");
      out.write("        const data = {};\r\n");
      out.write("        fields.forEach((field) => {\r\n");
      out.write("            const key = field.dataset.field;\r\n");
      out.write("            if (!key || isLockedField(field)) {\r\n");
      out.write("                return;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            if (field.type === 'radio') {\r\n");
      out.write("                if (field.checked) {\r\n");
      out.write("                    data[key] = field.value || '';\r\n");
      out.write("                } else if (!Object.prototype.hasOwnProperty.call(data, key)) {\r\n");
      out.write("                    data[key] = '';\r\n");
      out.write("                }\r\n");
      out.write("                return;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            data[key] = field.value || '';\r\n");
      out.write("        });\r\n");
      out.write("        try {\r\n");
      out.write("            localStorage.setItem(storageKey, JSON.stringify(data));\r\n");
      out.write("        } catch (error) {\r\n");
      out.write("            console.warn('Gagal simpan cache borang guest:', error);\r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    function load() {\r\n");
      out.write("        try {\r\n");
      out.write("            const raw = localStorage.getItem(storageKey);\r\n");
      out.write("            if (!raw) return;\r\n");
      out.write("            const data = JSON.parse(raw);\r\n");
      out.write("            fields.forEach((field) => {\r\n");
      out.write("                const key = field.dataset.field;\r\n");
      out.write("                if (isLockedField(field) || !Object.prototype.hasOwnProperty.call(data, key)) {\r\n");
      out.write("                    return;\r\n");
      out.write("                }\r\n");
      out.write("\r\n");
      out.write("                if (field.type === 'radio') {\r\n");
      out.write("                    field.checked = field.value === data[key];\r\n");
      out.write("                    return;\r\n");
      out.write("                }\r\n");
      out.write("\r\n");
      out.write("                field.value = data[key];\r\n");
      out.write("            });\r\n");
      out.write("        } catch (error) {\r\n");
      out.write("            console.warn('Gagal muat cache borang guest:', error);\r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    fields.forEach((field) => {\r\n");
      out.write("        if (isLockedField(field)) {\r\n");
      out.write("            return;\r\n");
      out.write("        }\r\n");
      out.write("        field.addEventListener('input', save);\r\n");
      out.write("        field.addEventListener('change', save);\r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("    applyLockedPrefill();\r\n");
      out.write("    load();\r\n");
      out.write("    applyLockedPrefill();\r\n");
      out.write("})();\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
