/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/11.0.18
 * Generated at: 2026-03-24 04:37:02 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.util.List;
import java.util.Map;
import java.util.ArrayList;
import java.util.Date;
import java.text.SimpleDateFormat;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

public final class products_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {


    private String escapeHtml(String input) {
        if (input == null) {
            return "";
        }
        return input.replace("&", "&amp;")
                .replace("<", "&lt;")
                .replace(">", "&gt;")
                .replace("\"", "&quot;")
                .replace("'", "&#39;");
    }

    private List<String> extractUrls(String input) {
        List<String> urls = new ArrayList<>();
        if (input == null || input.isBlank()) {
            return urls;
        }

        Pattern pattern = Pattern.compile("https?://[^\\s\\\"|]+", Pattern.CASE_INSENSITIVE);
        Matcher matcher = pattern.matcher(input);
        while (matcher.find()) {
            String url = matcher.group().trim();
            if (!urls.contains(url)) {
                urls.add(url);
            }
        }
        return urls;
    }

    private String safeText(Object value) {
        if (value == null) {
            return "-";
        }
        String text = String.valueOf(value).trim();
        if (text.isEmpty() || "null".equalsIgnoreCase(text)) {
            return "-";
        }
        return text;
    }

    private String formatValidDate(Object value) {
        if (value == null) {
            return "-";
        }
        if (value instanceof Date) {
            return new SimpleDateFormat("dd-MM-yyyy").format((Date) value);
        }
        String raw = String.valueOf(value).trim();
        if (raw.isEmpty() || "null".equalsIgnoreCase(raw)) {
            return "-";
        }
        return raw;
    }

    private String[] splitSupplierInfo(String supplierAgent) {
        if (supplierAgent == null || supplierAgent.isBlank()) {
            return new String[]{"-", "-"};
        }
        String cleaned = supplierAgent.trim().replaceAll("\\s+", " ");
        int comma = cleaned.indexOf(',');
        if (comma > 0 && comma < cleaned.length() - 1) {
            return new String[]{cleaned.substring(0, comma).trim(), cleaned.substring(comma + 1).trim()};
        }
        return new String[]{cleaned, cleaned};
    }

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(10);
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("java.util.regex.Matcher");
    _jspx_imports_classes.add("java.util.Date");
    _jspx_imports_classes.add("java.util.Map");
    _jspx_imports_classes.add("java.text.SimpleDateFormat");
    _jspx_imports_classes.add("java.util.regex.Pattern");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ms\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Senarai Produk Berdaftar - SPPA</title>\r\n");
      out.write("    <style>\r\n");
      out.write("        :root {\r\n");
      out.write("            --brand-blue: #0097d9;\r\n");
      out.write("            --brand-navy: #06344f;\r\n");
      out.write("            --brand-sky: #e8f7ff;\r\n");
      out.write("            --brand-yellow: #fff212;\r\n");
      out.write("            --text: #183244;\r\n");
      out.write("            --muted: #5f7686;\r\n");
      out.write("            --panel: #ffffff;\r\n");
      out.write("            --line: #d6e7f2;\r\n");
      out.write("        }\r\n");
      out.write("        * { box-sizing: border-box; }\r\n");
      out.write("        body { margin: 0; font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; background: linear-gradient(180deg, #eff9ff 0%, #f8fbfd 100%); color: var(--text); }\r\n");
      out.write("        .navbar { background: linear-gradient(130deg, var(--brand-navy) 0%, var(--brand-blue) 72%, var(--brand-yellow) 180%); color: white; padding: 16px 28px; display: flex; justify-content: space-between; align-items: center; gap: 20px; }\r\n");
      out.write("        .brand { display: flex; align-items: center; gap: 14px; }\r\n");
      out.write("        .brand-logo { width: 52px; height: 52px; border-radius: 14px; object-fit: contain; padding: 4px; }\r\n");
      out.write("        .brand h1 { margin: 0; font-size: 20px; }\r\n");
      out.write("        .brand p { margin: 2px 0 0; font-size: 12px; opacity: 0.88; }\r\n");
      out.write("        .nav-links a { color: white; text-decoration: none; margin-left: 16px; font-weight: 600; }\r\n");
      out.write("        .container { max-width: 1280px; margin: 26px auto; padding: 0 20px 32px; }\r\n");
      out.write("        .hero { display: grid; grid-template-columns: 2fr 1fr; gap: 20px; margin-bottom: 20px; }\r\n");
      out.write("        .panel { background: var(--panel); border: 1px solid var(--line); border-radius: 18px; box-shadow: 0 18px 44px rgba(6, 52, 79, 0.08); padding: 22px; }\r\n");
      out.write("        .hero h2 { margin-top: 0; font-size: 30px; }\r\n");
      out.write("        .hero p { color: var(--muted); line-height: 1.7; }\r\n");
      out.write("        .metric { display: inline-flex; align-items: center; gap: 8px; padding: 8px 12px; background: var(--brand-sky); border-radius: 999px; font-weight: 700; }\r\n");
      out.write("        .contact-image { width: 100%; border-radius: 14px; border: 1px solid var(--line); padding: 14px; background: #f7fbff; }\r\n");
      out.write("        .contact-image strong { display: block; margin-bottom: 8px; color: var(--brand-navy); }\r\n");
      out.write("        .contact-image p { margin: 4px 0; color: var(--muted); font-size: 14px; }\r\n");
      out.write("        .filters { display: grid; grid-template-columns: 2fr 1fr auto; gap: 12px; align-items: end; margin-bottom: 18px; }\r\n");
      out.write("        .field label { display: block; margin-bottom: 6px; font-size: 13px; font-weight: 700; color: var(--muted); }\r\n");
      out.write("        .field input, .field select { width: 100%; padding: 11px 12px; border-radius: 12px; border: 1px solid var(--line); }\r\n");
      out.write("        .btn { padding: 12px 16px; border-radius: 12px; border: 1px solid #fff; cursor: pointer; text-decoration: none; font-weight: 700; }\r\n");
      out.write("        .btn-primary { background: var(--brand-blue); color: white; }\r\n");
      out.write("        .btn-secondary { background: #dcecf6; color: var(--brand-navy); }\r\n");
      out.write("        .btn-attachment { background: #e7f4fb; color: #0b4d71; border: 1px solid #b9dcee; padding: 7px 10px; border-radius: 10px; font-weight: 700; cursor: pointer; }\r\n");
      out.write("        .table-wrap { width: 100%; overflow-x: auto; border-radius: 16px; }\r\n");
      out.write("        table { width: 100%; min-width: 1120px; border-collapse: collapse; table-layout: fixed; }\r\n");
      out.write("        th, td { padding: 13px 12px; border-bottom: 1px solid #e5f0f6; text-align: left; vertical-align: top; word-break: break-word; overflow-wrap: anywhere; }\r\n");
      out.write("        th { font-size: 13px; text-transform: uppercase; letter-spacing: 0.04em; color: var(--muted); }\r\n");
      out.write("        tr:hover { background: #f7fcff; }\r\n");
      out.write("        .tag { display: inline-block; padding: 4px 10px; border-radius: 999px; background: #eef7fb; color: var(--brand-navy); font-size: 12px; font-weight: 700; }\r\n");
      out.write("        .source-link { color: var(--brand-blue); font-weight: 700; text-decoration: none; }\r\n");
      out.write("        .supplier-name { display: block; font-weight: 700; margin-bottom: 5px; }\r\n");
      out.write("        .supplier-address { color: var(--muted); font-size: 13px; line-height: 1.5; }\r\n");
      out.write("        .cell-tight { white-space: normal; line-height: 1.5; }\r\n");
      out.write("        .import-note { margin-top: 10px; color: var(--muted); font-size: 13px; }\r\n");
      out.write("        .modal-overlay { display: none; position: fixed; inset: 0; background: rgba(4, 24, 38, 0.72); z-index: 9999; align-items: center; justify-content: center; padding: 16px; }\r\n");
      out.write("        .modal-overlay.open { display: flex; }\r\n");
      out.write("        .modal-card { width: min(1000px, 96vw); height: min(88vh, 760px); background: #fff; border-radius: 16px; overflow: hidden; display: grid; grid-template-rows: auto 1fr; }\r\n");
      out.write("        .modal-header { display: flex; justify-content: space-between; align-items: center; padding: 12px 14px; border-bottom: 1px solid #e5f0f6; }\r\n");
      out.write("        .modal-title { font-size: 15px; font-weight: 700; }\r\n");
      out.write("        .modal-close { border: 1px solid #fff; background: #eff4f8; border-radius: 10px; padding: 7px 10px; font-weight: 700; cursor: pointer; }\r\n");
      out.write("        .modal-body { display: grid; grid-template-columns: 240px 1fr; min-height: 0; }\r\n");
      out.write("        .attachment-list { border-right: 1px solid #e5f0f6; padding: 10px; overflow: auto; }\r\n");
      out.write("        .attachment-list button { width: 100%; margin-bottom: 8px; text-align: left; border: 1px solid #d6e7f2; background: #f8fbfe; border-radius: 9px; padding: 9px; cursor: pointer; }\r\n");
      out.write("        .attachment-list button.active { background: #e8f7ff; border-color: #8acde9; }\r\n");
      out.write("        .viewer { min-height: 0; display: grid; grid-template-rows: 1fr auto; }\r\n");
      out.write("        .viewer iframe { width: 100%; height: 100%; min-height: 420px; border: 0; }\r\n");
      out.write("        .viewer-empty { display: flex; align-items: center; justify-content: center; height: 100%; color: var(--muted); }\r\n");
      out.write("        @media (max-width: 980px) { .hero, .filters { grid-template-columns: 1fr; } .navbar { flex-direction: column; align-items: flex-start; } .nav-links a { margin-left: 0; margin-right: 16px; } }\r\n");
      out.write("        @media (max-width: 780px) { .modal-body { grid-template-columns: 1fr; } .attachment-list { border-right: 0; border-bottom: 1px solid #e5f0f6; max-height: 180px; } }\r\n");
      out.write("                    /* Enforce visible white border on all clickable buttons */\r\n");
      out.write("        button,\r\n");
      out.write("        input[type=\"submit\"],\r\n");
      out.write("        input[type=\"button\"],\r\n");
      out.write("        .btn,\r\n");
      out.write("        .login-btn,\r\n");
      out.write("        .modal-close,\r\n");
      out.write("        .btn-attachment,\r\n");
      out.write("        .attachment-list button,\r\n");
      out.write("        a.btn {\r\n");
      out.write("            border: 1px solid #fff !important;\r\n");
      out.write("            box-shadow: inset 0 0 0 1px #fff, 0 1px 2px rgba(0, 0, 0, 0.18) !important;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        button:hover,\r\n");
      out.write("        input[type=\"submit\"]:hover,\r\n");
      out.write("        input[type=\"button\"]:hover,\r\n");
      out.write("        .btn:hover,\r\n");
      out.write("        .login-btn:hover,\r\n");
      out.write("        .modal-close:hover,\r\n");
      out.write("        .btn-attachment:hover,\r\n");
      out.write("        .attachment-list button:hover,\r\n");
      out.write("        a.btn:hover,\r\n");
      out.write("        button:focus,\r\n");
      out.write("        input[type=\"submit\"]:focus,\r\n");
      out.write("        input[type=\"button\"]:focus,\r\n");
      out.write("        .btn:focus,\r\n");
      out.write("        .login-btn:focus,\r\n");
      out.write("        .modal-close:focus,\r\n");
      out.write("        .btn-attachment:focus,\r\n");
      out.write("        .attachment-list button:focus,\r\n");
      out.write("        a.btn:focus {\r\n");
      out.write("            border: 1px solid #fff !important;\r\n");
      out.write("            box-shadow: inset 0 0 0 1px #fff, 0 0 0 2px rgba(255, 255, 255, 0.35), 0 1px 2px rgba(0, 0, 0, 0.18) !important;\r\n");
      out.write("        }</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <div class=\"navbar\">\r\n");
      out.write("        <div class=\"brand\">\r\n");
      out.write("            <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/images/logo-jabatan-air-sabah.png?v=4\" class=\"brand-logo\" alt=\"Logo Jabatan Air Sabah\">\r\n");
      out.write("            <div>\r\n");
      out.write("                <h1>Senarai Produk Berdaftar</h1>\r\n");
      out.write("                <p>Sistem Pendaftaran Produk Air â€¢ Jabatan Air Negeri Sabah</p>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"nav-links\">\r\n");
      out.write("            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/dashboard\">Dashboard</a>\r\n");
      out.write("            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/logout\">Log Keluar</a>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <div class=\"hero\">\r\n");
      out.write("            <div class=\"panel\">\r\n");
      out.write("                <div class=\"metric\"><span>");
      out.print( request.getAttribute("product_total") );
      out.write("</span> produk ditemui</div>\r\n");
      out.write("                <h2>Rujukan produk air yang telah berdaftar</h2>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"panel\">\r\n");
      out.write("                <div class=\"contact-image\" aria-label=\"Maklumat hubungan Jabatan Air Sabah\">\r\n");
      out.write("                    <strong>Hubungi JANS</strong>\r\n");
      out.write("                    <p>Telefon: 088-326888</p>\r\n");
      out.write("                    <p>Email: info@jwater.gov.my</p>\r\n");
      out.write("                    <p>Kota Kinabalu, Sabah</p>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"panel\">\r\n");
      out.write("            <form method=\"get\" action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/products\" class=\"filters\">\r\n");
      out.write("                <div class=\"field\">\r\n");
      out.write("                    <label for=\"q\">Carian</label>\r\n");
      out.write("                    <input id=\"q\" name=\"q\" type=\"text\" value=\"");
      out.print( request.getAttribute("search_query") );
      out.write("\" placeholder=\"Cari supplier/ejen, jenama, produk/material, atau tarikh sah (contoh 21-01-2028)\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"field\">\r\n");
      out.write("                    <label for=\"type\">Jenis / Kumpulan</label>\r\n");
      out.write("                    <select id=\"type\" name=\"type\">\r\n");
      out.write("                        <option value=\"\">Semua jenis</option>\r\n");
      out.write("                        ");

                            List<String> productTypes = (List<String>) request.getAttribute("product_types");
                            String selectedType = String.valueOf(request.getAttribute("selected_type"));
                            if (productTypes != null) {
                                for (String type : productTypes) {
                        
      out.write("\r\n");
      out.write("                        <option value=\"");
      out.print( type );
      out.write('"');
      out.write(' ');
      out.print( type.equals(selectedType) ? "selected" : "" );
      out.write('>');
      out.print( type );
      out.write("</option>\r\n");
      out.write("                        ");
      }
                            }
                        
      out.write("\r\n");
      out.write("                    </select>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div>\r\n");
      out.write("                    <button class=\"btn btn-primary\" type=\"submit\">Cari Produk</button>\r\n");
      out.write("                </div>\r\n");
      out.write("            </form>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"table-wrap\">\r\n");
      out.write("            <table>\r\n");
      out.write("                <thead>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <th style=\"width:70px;\">No.</th>\r\n");
      out.write("                        <th style=\"width:250px;\">Supplier Name &amp; Address</th>\r\n");
      out.write("                        <th style=\"width:220px;\">Product / Materials</th>\r\n");
      out.write("                        <th style=\"width:160px;\">Category</th>\r\n");
      out.write("                        <th style=\"width:150px;\">Type</th>\r\n");
      out.write("                        <th style=\"width:120px;\">Brand</th>\r\n");
      out.write("                        <th style=\"width:120px;\">Valid Date</th>\r\n");
      out.write("                        <th style=\"width:150px;\">Attachment</th>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                </thead>\r\n");
      out.write("                <tbody>\r\n");
      out.write("                    ");

                        List<Map<String, Object>> products = (List<Map<String, Object>>) request.getAttribute("products");
                        if (products == null || products.isEmpty()) {
                    
      out.write("\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td colspan=\"8\" style=\"text-align:center;color:#5f7686;padding:32px;\">Tiada produk ditemui untuk carian ini.</td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    ");
 } else {
                        for (Map<String, Object> product : products) {
                            String[] supplierInfo = splitSupplierInfo(String.valueOf(product.get("supplier_agent")));
                            String productMaterials = safeText(product.get("product_materials"));
                            String category = safeText(product.get("product_type"));
                            String itemType = safeText(product.get("classification"));
                            String brand = safeText(product.get("brand"));
                            String validDate = formatValidDate(product.get("supplier_valid_until"));
                            List<String> attachments = extractUrls(String.valueOf(product.get("attachment_urls")));
                            String attachmentPayload = escapeHtml(String.join("||", attachments));
                    
      out.write("\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td><strong>");
      out.print( product.get("no") );
      out.write("</strong></td>\r\n");
      out.write("                        <td class=\"cell-tight\">\r\n");
      out.write("                            <span class=\"supplier-name\">");
      out.print( escapeHtml(supplierInfo[0]) );
      out.write("</span>\r\n");
      out.write("                            <span class=\"supplier-address\">");
      out.print( escapeHtml(supplierInfo[1]) );
      out.write("</span>\r\n");
      out.write("                        </td>\r\n");
      out.write("                        <td class=\"cell-tight\">");
      out.print( escapeHtml(productMaterials) );
      out.write("</td>\r\n");
      out.write("                        <td><span class=\"tag\">");
      out.print( escapeHtml(category) );
      out.write("</span></td>\r\n");
      out.write("                        <td class=\"cell-tight\">");
      out.print( escapeHtml(itemType) );
      out.write("</td>\r\n");
      out.write("                        <td class=\"cell-tight\">");
      out.print( escapeHtml(brand) );
      out.write("</td>\r\n");
      out.write("                        <td>");
      out.print( escapeHtml(validDate) );
      out.write("</td>\r\n");
      out.write("                        <td>\r\n");
      out.write("                            ");
 if (attachments.isEmpty()) { 
      out.write("\r\n");
      out.write("                                -\r\n");
      out.write("                            ");
 } else { 
      out.write("\r\n");
      out.write("                                <button type=\"button\" class=\"btn-attachment open-attachment\" data-attachments=\"");
      out.print( attachmentPayload );
      out.write("\">Lihat Lampiran (");
      out.print( attachments.size() );
      out.write(")</button>\r\n");
      out.write("                            ");
 } 
      out.write("\r\n");
      out.write("                        </td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    ");
  }
                       }
                    
      out.write("\r\n");
      out.write("                </tbody>\r\n");
      out.write("            </table>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div id=\"attachmentModal\" class=\"modal-overlay\" aria-hidden=\"true\">\r\n");
      out.write("        <div class=\"modal-card\" role=\"dialog\" aria-modal=\"true\" aria-label=\"Lampiran Produk\">\r\n");
      out.write("            <div class=\"modal-header\">\r\n");
      out.write("                <div class=\"modal-title\">Lampiran Produk</div>\r\n");
      out.write("                <button type=\"button\" id=\"closeAttachmentModal\" class=\"modal-close\">Tutup</button>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"modal-body\">\r\n");
      out.write("                <div class=\"attachment-list\" id=\"attachmentList\"></div>\r\n");
      out.write("                <div class=\"viewer\" id=\"attachmentViewer\">\r\n");
      out.write("                    <div class=\"viewer-empty\">Tiada lampiran dipilih.</div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <script>\r\n");
      out.write("        (function () {\r\n");
      out.write("            const modal = document.getElementById('attachmentModal');\r\n");
      out.write("            const closeBtn = document.getElementById('closeAttachmentModal');\r\n");
      out.write("            const attachmentList = document.getElementById('attachmentList');\r\n");
      out.write("            const attachmentViewer = document.getElementById('attachmentViewer');\r\n");
      out.write("            const openButtons = document.querySelectorAll('.open-attachment');\r\n");
      out.write("\r\n");
      out.write("            function escapeHtml(text) {\r\n");
      out.write("                return String(text)\r\n");
      out.write("                    .replace(/&/g, '&amp;')\r\n");
      out.write("                    .replace(/</g, '&lt;')\r\n");
      out.write("                    .replace(/>/g, '&gt;')\r\n");
      out.write("                    .replace(/\\\"/g, '&quot;')\r\n");
      out.write("                    .replace(/'/g, '&#39;');\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            function buildProxyUrl(url) {\r\n");
      out.write("                return '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/product-attachments/view?url=' + encodeURIComponent(url);\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            function showViewer(url) {\r\n");
      out.write("                const proxyUrl = buildProxyUrl(url);\r\n");
      out.write("                attachmentViewer.innerHTML = ''\r\n");
      out.write("                    + '<iframe title=\"Lampiran Produk\" src=\"' + escapeHtml(proxyUrl) + '\"></iframe>'\r\n");
      out.write("                    + '<div style=\"padding:12px 14px;border-top:1px solid #e5f0f6;background:#f8fbfe;display:flex;gap:10px;flex-wrap:wrap;\">'\r\n");
      out.write("                    + '<a class=\"source-link\" href=\"' + escapeHtml(proxyUrl) + '\" target=\"_blank\" rel=\"noopener noreferrer\">Buka lampiran</a>'\r\n");
      out.write("                    + '<a class=\"source-link\" href=\"' + escapeHtml(url) + '\" target=\"_blank\" rel=\"noopener noreferrer\">Sumber asal</a>'\r\n");
      out.write("                    + '</div>';\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            function openModal(urls) {\r\n");
      out.write("                attachmentList.innerHTML = '';\r\n");
      out.write("                attachmentViewer.innerHTML = '<div class=\"viewer-empty\">Memuat lampiran...</div>';\r\n");
      out.write("\r\n");
      out.write("                urls.forEach(function (url, index) {\r\n");
      out.write("                    const btn = document.createElement('button');\r\n");
      out.write("                    btn.type = 'button';\r\n");
      out.write("                    btn.textContent = 'Lampiran ' + (index + 1);\r\n");
      out.write("                    btn.addEventListener('click', function () {\r\n");
      out.write("                        attachmentList.querySelectorAll('button').forEach(function (b) { b.classList.remove('active'); });\r\n");
      out.write("                        btn.classList.add('active');\r\n");
      out.write("                        showViewer(url);\r\n");
      out.write("                    });\r\n");
      out.write("                    attachmentList.appendChild(btn);\r\n");
      out.write("                });\r\n");
      out.write("\r\n");
      out.write("                const first = attachmentList.querySelector('button');\r\n");
      out.write("                if (first) {\r\n");
      out.write("                    first.classList.add('active');\r\n");
      out.write("                    showViewer(urls[0]);\r\n");
      out.write("                } else {\r\n");
      out.write("                    attachmentViewer.innerHTML = '<div class=\"viewer-empty\">Tiada lampiran dijumpai.</div>';\r\n");
      out.write("                }\r\n");
      out.write("\r\n");
      out.write("                modal.classList.add('open');\r\n");
      out.write("                modal.setAttribute('aria-hidden', 'false');\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            function closeModal() {\r\n");
      out.write("                modal.classList.remove('open');\r\n");
      out.write("                modal.setAttribute('aria-hidden', 'true');\r\n");
      out.write("                attachmentList.innerHTML = '';\r\n");
      out.write("                attachmentViewer.innerHTML = '<div class=\"viewer-empty\">Tiada lampiran dipilih.</div>';\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            openButtons.forEach(function (btn) {\r\n");
      out.write("                btn.addEventListener('click', function () {\r\n");
      out.write("                    const payload = btn.getAttribute('data-attachments') || '';\r\n");
      out.write("                    const urls = payload.split('||').map(function (x) { return x.trim(); }).filter(Boolean);\r\n");
      out.write("                    openModal(urls);\r\n");
      out.write("                });\r\n");
      out.write("            });\r\n");
      out.write("\r\n");
      out.write("            closeBtn.addEventListener('click', closeModal);\r\n");
      out.write("            modal.addEventListener('click', function (event) {\r\n");
      out.write("                if (event.target === modal) {\r\n");
      out.write("                    closeModal();\r\n");
      out.write("                }\r\n");
      out.write("            });\r\n");
      out.write("            document.addEventListener('keydown', function (event) {\r\n");
      out.write("                if (event.key === 'Escape' && modal.classList.contains('open')) {\r\n");
      out.write("                    closeModal();\r\n");
      out.write("                }\r\n");
      out.write("            });\r\n");
      out.write("        })();\r\n");
      out.write("    </script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
