/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/11.0.18
 * Generated at: 2026-06-10 03:48:39 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class register_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ms\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Daftar Pemohon - SPPPA</title>\r\n");
      out.write("    <style>\r\n");
      out.write("        :root {\r\n");
      out.write("            --brand-blue: #2A9D8F;\r\n");
      out.write("            --brand-navy: #0F6BAE;\r\n");
      out.write("            --brand-green: #6DBE45;\r\n");
      out.write("            --brand-lime: #CDE11D;\r\n");
      out.write("            --brand-yellow: #F2F72E;\r\n");
      out.write("        }\r\n");
      out.write("        * { margin: 0; padding: 0; box-sizing: border-box; }\r\n");
      out.write("        body { font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; background: url('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/images/login-register-bg.jpg') center/cover no-repeat fixed; min-height: 100vh; display: grid; place-items: center; padding: 24px; position: relative; }\r\n");
      out.write("        body::before { content: ''; position: fixed; inset: 0; background: rgba(255,255,255,0.45); z-index: 0; pointer-events: none; }\r\n");
      out.write("        .shell { position: relative; z-index: 1; }\r\n");
      out.write("        .shell { display: grid; grid-template-columns: 1fr 1fr; width: 100%; max-width: 1040px; border-radius: 24px; overflow: hidden; box-shadow: 0 22px 58px rgba(6, 52, 79, 0.2); }\r\n");
      out.write("        .info { background: linear-gradient(180deg, rgba(255,255,255,0.16) 0%, rgba(255,255,255,0.08) 100%); color: white; padding: 40px; }\r\n");
      out.write("        .info .logo { width: 78px; height: 78px; border-radius: 18px; margin-bottom: 18px; display: grid; place-items: center; color: var(--brand-navy); font-size: 22px; font-weight: 800; letter-spacing: 0.08em; }\r\n");
      out.write("        .info h1 { margin-bottom: 10px; font-size: 34px; color: #000000; }\r\n");
      out.write("        .info p { opacity: 0.94; margin-bottom: 20px; }\r\n");
      out.write("        .info .contact { width: 100%; border-radius: 18px; border: 1px solid rgba(255,255,255,0.25); padding: 14px; background: rgba(6, 52, 79, 0.28); }\r\n");
      out.write("        .info .contact strong { display: block; margin-bottom: 8px; }\r\n");
      out.write("        .info .contact p { margin: 4px 0; font-size: 13px; }\r\n");
      out.write("        .info .contact strong img { width: 22px; height: 22px; vertical-align: middle; margin-right: 8px; object-fit: contain; }\r\n");
      out.write("        .card { padding: 36px; background: rgba(255,255,255,0.95); }\r\n");
      out.write("        h2 { margin-bottom: 8px; color: #173040; }\r\n");
      out.write("        p.form-copy { color: #60798b; margin-bottom: 20px; }\r\n");
      out.write("        .field { margin-bottom: 16px; }\r\n");
      out.write("        label { display: block; margin-bottom: 6px; font-weight: 700; color: #173040; }\r\n");
      out.write("        input { width: 100%; padding: 12px; border: 1px solid #d7e7ef; border-radius: 12px; }\r\n");
      out.write("        .password-help { margin-top: 6px; font-size: 12px; color: #60798b; line-height: 1.5; }\r\n");
      out.write("        .error { margin-bottom: 14px; background: #fee2e2; color: #b91c1c; padding: 12px; border-radius: 10px; }\r\n");
      out.write("        .btn { width: 100%; border: 1px solid #fff; border-radius: 12px; padding: 13px; background: linear-gradient(135deg, var(--brand-navy) 0%, var(--brand-blue) 100%); color: white; font-weight: 700; cursor: pointer; }\r\n");
      out.write("        .btn:disabled { opacity: 0.6; cursor: not-allowed; }\r\n");
      out.write("        .privacy-consent-box { margin: 14px 0 16px; padding: 12px 14px; background: #f5f8fb; border: 1px solid #d7e7ef; border-radius: 12px; }\r\n");
      out.write("        .privacy-consent-label { display: flex; align-items: flex-start; gap: 10px; margin: 0; font-weight: 600; color: #173040; line-height: 1.5; font-size: 14px; }\r\n");
      out.write("        .privacy-consent-label input[type=\"checkbox\"] { width: 18px; height: 18px; margin-top: 2px; flex: 0 0 18px; }\r\n");
      out.write("        .privacy-consent-label span { display: block; text-align: justify; text-justify: inter-word; line-height: 1.65; letter-spacing: 0.01em; }\r\n");
      out.write("        .footer { margin-top: 18px; text-align: center; color: #64748b; }\r\n");
      out.write("        .footer a { color: var(--brand-blue); text-decoration: none; font-weight: 700; }\r\n");
      out.write("        @media (max-width: 920px) { .shell { grid-template-columns: 1fr; } .info { display: none; } }\r\n");
      out.write("        @media (max-width: 576px) { .privacy-consent-label { gap: 8px; font-size: 13px; } .privacy-consent-label span { text-align: left; line-height: 1.55; letter-spacing: 0; } }\r\n");
      out.write("                    \r\n");
      out.write("        button,\r\n");
      out.write("        input[type=\"submit\"],\r\n");
      out.write("        input[type=\"button\"],\r\n");
      out.write("        .btn,\r\n");
      out.write("        .login-btn,\r\n");
      out.write("        .modal-close,\r\n");
      out.write("        .btn-attachment,\r\n");
      out.write("        .attachment-list button,\r\n");
      out.write("        a.btn {\r\n");
      out.write("            border: 1px solid #fff !important;\r\n");
      out.write("            box-shadow: inset 0 0 0 1px #fff, 0 1px 2px rgba(0, 0, 0, 0.18) !important;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        button:hover,\r\n");
      out.write("        input[type=\"submit\"]:hover,\r\n");
      out.write("        input[type=\"button\"]:hover,\r\n");
      out.write("        .btn:hover,\r\n");
      out.write("        .login-btn:hover,\r\n");
      out.write("        .modal-close:hover,\r\n");
      out.write("        .btn-attachment:hover,\r\n");
      out.write("        .attachment-list button:hover,\r\n");
      out.write("        a.btn:hover,\r\n");
      out.write("        button:focus,\r\n");
      out.write("        input[type=\"submit\"]:focus,\r\n");
      out.write("        input[type=\"button\"]:focus,\r\n");
      out.write("        .btn:focus,\r\n");
      out.write("        .login-btn:focus,\r\n");
      out.write("        .modal-close:focus,\r\n");
      out.write("        .btn-attachment:focus,\r\n");
      out.write("        .attachment-list button:focus,\r\n");
      out.write("        a.btn:focus {\r\n");
      out.write("            border: 1px solid #fff !important;\r\n");
      out.write("            box-shadow: inset 0 0 0 1px #fff, 0 0 0 2px rgba(255, 255, 255, 0.35), 0 1px 2px rgba(0, 0, 0, 0.18) !important;\r\n");
      out.write("        }\r\n");
      out.write("        .floating-home-btn {\r\n");
      out.write("            position: static;\r\n");
      out.write("            display: inline-flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            justify-content: center;\r\n");
      out.write("            width: 32px;\r\n");
      out.write("            height: 32px;\r\n");
      out.write("            margin-left: 12px;\r\n");
      out.write("            border-radius: 999px;\r\n");
      out.write("            border: 1px solid #fff;\r\n");
      out.write("            background: rgba(255, 255, 255, 0.12);\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            vertical-align: middle;\r\n");
      out.write("        }\r\n");
      out.write("        .floating-home-btn img {\r\n");
      out.write("            width: 16px;\r\n");
      out.write("            height: 16px;\r\n");
      out.write("            object-fit: contain;\r\n");
      out.write("        }\r\n");
      out.write("        .jans-contact-section { margin-top: 10px; border: 1px solid #d6e5ef; border-radius: 14px; background: #f8fcff; padding: 12px; }\r\n");
      out.write("        .jans-contact-section h3 { margin: 0 0 10px; color: #0f6bae; font-size: 16px; font-weight: 700; letter-spacing: 0; }\r\n");
      out.write("        .jans-contact-section .contact-line { display: flex; align-items: flex-start; gap: 8px; margin: 7px 0; font-size: 13px; color: #4e6a7c; line-height: 1.45; }\r\n");
      out.write("        .jans-contact-section .contact-icon { display: inline-block; width: 10px; height: 10px; background: #0f6bae; border-radius: 2px; flex-shrink: 0; margin-top: 2px; }\r\n");
      out.write("        .jans-contact-section .contact-line span { line-height: 1.45; }\r\n");
      out.write("        </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <div class=\"shell\">\r\n");
      out.write("        <div class=\"info\">\r\n");
      out.write("            <h1>Daftar Akaun Sistem Pendaftaran Pembekal dan Produk Air</h1>\r\n");
      out.write("            <div class=\"container\" style=\"padding-top:0;\">\r\n");
      out.write("                <div class=\"jans-contact-section\">\r\n");
      out.write("                    <h3>Hubungi JANS</h3>\r\n");
      out.write("                <p class=\"contact-line\"><a class=\"contact-address-link\" href=\"https://www.google.com/maps/place/Jabatan+Air+Negeri+Sabah/data=!4m7!3m6!1s0x323b69b770552161:0x46ddcd3e362b7115!8m2!3d5.9610727!4d116.0687216!16s%2Fg%2F1pzrm3yct!19sChIJYSFVcLdpOzIRFXErNj7N3UY?authuser=0&hl=en&rclk=1\" target=\"_blank\" rel=\"noopener noreferrer\">SABAH WATER DEPARTMENT</a></p>\r\n");
      out.write("                <p class=\"contact-line\"><a class=\"contact-address-link\" href=\"https://www.google.com/maps/place/Jabatan+Air+Negeri+Sabah/data=!4m7!3m6!1s0x323b69b770552161:0x46ddcd3e362b7115!8m2!3d5.9610727!4d116.0687216!16s%2Fg%2F1pzrm3yct!19sChIJYSFVcLdpOzIRFXErNj7N3UY?authuser=0&hl=en&rclk=1\" target=\"_blank\" rel=\"noopener noreferrer\">Tingkat 6, Blok A, Wisma MUIS, Beg Berkunci No. 210, 88825</a></p>\r\n");
      out.write("                <p class=\"contact-line\"><a class=\"contact-address-link\" href=\"https://www.google.com/maps/place/Jabatan+Air+Negeri+Sabah/data=!4m7!3m6!1s0x323b69b770552161:0x46ddcd3e362b7115!8m2!3d5.9610727!4d116.0687216!16s%2Fg%2F1pzrm3yct!19sChIJYSFVcLdpOzIRFXErNj7N3UY?authuser=0&hl=en&rclk=1\" target=\"_blank\" rel=\"noopener noreferrer\">Kota Kinabalu, Sabah, Malaysia</a></p>\r\n");
      out.write("                <p class=\"contact-line\"><span>Tel: +60-88-232364 (HQ) , Fax: +60-88-232396</span></p>\r\n");
      out.write("                <p class=\"contact-line\"><span>Email: jans.hq@sabah.gov.my</span></p></div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"card\">\r\n");
      out.write("        <h2>Daftar Akaun Pemohon</h2>\r\n");
      out.write("        <p class=\"form-copy\">Cipta akaun untuk mengisi borang PPP1 secara online dan memantau status permohonan.</p>\r\n");
      out.write("\r\n");
      out.write("        ");
 if (request.getAttribute("error") != null) { 
      out.write("\r\n");
      out.write("            <div class=\"error\">");
      out.print( request.getAttribute("error") );
      out.write("</div>\r\n");
      out.write("        ");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <form method=\"post\" action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/register\">\r\n");
      out.write("            <input type=\"hidden\" name=\"_csrf\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${csrf_token}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("            <div class=\"field\">\r\n");
      out.write("                <label for=\"full_name\">Nama Penuh</label>\r\n");
      out.write("                <input id=\"full_name\" name=\"full_name\" type=\"text\" required>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"field\">\r\n");
      out.write("                <label for=\"username\">Nama Pengguna</label>\r\n");
      out.write("                <input id=\"username\" name=\"username\" type=\"text\" required>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"field\">\r\n");
      out.write("                <label for=\"phone_number\">Nombor Telefon</label>\r\n");
      out.write("                <input id=\"phone_number\" name=\"phone_number\" type=\"tel\" pattern=\"[0-9+()\\-\\s]{8,20}\" inputmode=\"tel\" required>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"field\">\r\n");
      out.write("                <label for=\"email\">Email</label>\r\n");
      out.write("                <input id=\"email\" name=\"email\" type=\"email\" required>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"field\">\r\n");
      out.write("                <label for=\"password\">Kata Laluan</label>\r\n");
      out.write("                <input id=\"password\" name=\"password\" type=\"password\" minlength=\"10\" pattern=\"(?=.*[a-z])(?=.*[A-Z])(?=.*\\d)(?=.*[^A-Za-z0-9]).{10,}\" autocomplete=\"new-password\" required>\r\n");
      out.write("                <div class=\"password-help\">Minimum 10 aksara, mesti ada huruf besar, huruf kecil, nombor dan simbol khas.</div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"field\">\r\n");
      out.write("                <label for=\"confirm_password\">Sahkan Kata Laluan</label>\r\n");
      out.write("                <input id=\"confirm_password\" name=\"confirm_password\" type=\"password\" minlength=\"10\" autocomplete=\"new-password\" required>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"privacy-consent-box\">\r\n");
      out.write("                <label for=\"privacy_consent\" class=\"privacy-consent-label\">\r\n");
      out.write("                    <input id=\"privacy_consent\" name=\"privacy_consent\" type=\"checkbox\" value=\"1\" required>\r\n");
      out.write("                    <span>Segala maklumat yang dikemukakan semasa pendaftaran akan digunakan hanya bagi tujuan pendaftaran akaun. Maklumat peribadi akan dirahsiakan dan tidak akan didedahkan atau dikongsi dengan mana-mana pihak ketiga.</span>\r\n");
      out.write("                </label>\r\n");
      out.write("            </div>\r\n");
      out.write("            <button id=\"registerSubmitBtn\" class=\"btn\" type=\"submit\" disabled>Daftar Akaun</button>\r\n");
      out.write("        </form>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"footer\">\r\n");
      out.write("                Sudah ada akaun? <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/login\">Log masuk di sini</a>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <a class=\"floating-home-btn\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/\" aria-label=\"Laman utama\" title=\"Laman utama\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/images/icon-home.png\" alt=\"Laman utama\"></a>\r\n");
      out.write("<script>\r\n");
      out.write("(function() {\r\n");
      out.write("    var form = document.querySelector('form[action$=\"/register\"]');\r\n");
      out.write("    var passwordInput = document.getElementById('password');\r\n");
      out.write("    var confirmInput = document.getElementById('confirm_password');\r\n");
      out.write("    var consentCheckbox = document.getElementById('privacy_consent');\r\n");
      out.write("    var submitBtn = document.getElementById('registerSubmitBtn');\r\n");
      out.write("\r\n");
      out.write("    function syncSubmitState() {\r\n");
      out.write("        if (!consentCheckbox || !submitBtn) return;\r\n");
      out.write("        submitBtn.disabled = !consentCheckbox.checked;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    if (form && passwordInput && confirmInput) {\r\n");
      out.write("        syncSubmitState();\r\n");
      out.write("        if (consentCheckbox) {\r\n");
      out.write("            consentCheckbox.addEventListener('change', syncSubmitState);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        form.addEventListener('submit', function (event) {\r\n");
      out.write("            var passwordValue = passwordInput.value || '';\r\n");
      out.write("            var rule = /^(?=.*[a-z])(?=.*[A-Z])(?=.*\\d)(?=.*[^A-Za-z0-9]).{10,}$/;\r\n");
      out.write("            if (!rule.test(passwordValue)) {\r\n");
      out.write("                event.preventDefault();\r\n");
      out.write("                alert('Kata laluan mesti minimum 10 aksara serta mengandungi huruf besar, huruf kecil, nombor dan simbol khas.');\r\n");
      out.write("                passwordInput.focus();\r\n");
      out.write("                return;\r\n");
      out.write("            }\r\n");
      out.write("            if (passwordValue !== (confirmInput.value || '')) {\r\n");
      out.write("                event.preventDefault();\r\n");
      out.write("                alert('Pengesahan kata laluan tidak sepadan.');\r\n");
      out.write("                confirmInput.focus();\r\n");
      out.write("                return;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            if (consentCheckbox && !consentCheckbox.checked) {\r\n");
      out.write("                event.preventDefault();\r\n");
      out.write("                alert('Sila tandakan persetujuan privasi sebelum daftar akaun.');\r\n");
      out.write("                consentCheckbox.focus();\r\n");
      out.write("            }\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("    }\r\n");
      out.write("})();\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
