/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/11.0.18
 * Generated at: 2026-06-10 07:15:29 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.util.List;
import java.util.Map;

public final class view_002dapplication_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {


    private String statusCssClass(String status) {
        if (status == null) {
            return "";
        }
        return status.trim().toLowerCase(java.util.Locale.ROOT).replace(' ', '_');
    }

    private String displayStatusLabel(String status) {
        if (status == null) {
            return "";
        }
        String normalized = status.trim().toUpperCase(java.util.Locale.ROOT);
        if ("APPROVED".equals(normalized) || "DILULUSKAN".equals(normalized)) {
            return "DILULUSKAN";
        }
        if ("REJECTED".equals(normalized) || "DITOLAK".equals(normalized)) {
            return "DITOLAK";
        }
        if ("SUSPENDED".equals(normalized) || "DIGANTUNG".equals(normalized)) {
            return "DIGANTUNG";
        }
        if ("DRAFT".equals(normalized) || "DRAF".equals(normalized)) {
            return "DRAF";
        }
        if ("ARCHIVED".equals(normalized) || "DIARKIB".equals(normalized)) {
            return "DIARKIB";
        }
        if ("UNDER_REVIEW".equals(normalized) || "DALAM_SEMAKAN".equals(normalized) || "DALAM SEMAKAN".equals(normalized)) {
            return "DALAM SEMAKAN";
        }
        if ("IN_PROGRESS".equals(normalized) || "DALAM_PROSES".equals(normalized) || "DALAM PROSES".equals(normalized)) {
            return "DALAM PROSES";
        }
        return status;
    }

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(3);
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("java.util.Map");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write('\r');
      out.write('\n');

    response.setHeader("Cache-Control", "no-cache, no-store, must-revalidate");
    response.setHeader("Pragma", "no-cache");
    response.setDateHeader("Expires", 0);

    Map<String, Object> app = (Map<String, Object>) request.getAttribute("application");
    List<Map<String, Object>> documents = (List<Map<String, Object>>) request.getAttribute("documents");
    Map<String, String> requiredDocuments = (Map<String, String>) request.getAttribute("requiredDocuments");

    String status = app.get("status") == null ? "" : String.valueOf(app.get("status"));
    String statusDisplay = displayStatusLabel(status);
    String certNum = app.get("certificate_number") == null ? null : String.valueOf(app.get("certificate_number"));
    int appId = (Integer) app.get("id");
    String appIdFormatted = String.format("PPP%03d", appId);
    boolean showUpdatedNotice = "1".equals(request.getParameter("updated"));

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ms\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Butiran Permohonan ");
      out.print( appIdFormatted );
      out.write(" - SPPPA</title>\r\n");
      out.write("    <style>\r\n");
      out.write("        @import url('https://fonts.googleapis.com/css2?family=Source+Sans+3:wght@400;600;700;800&display=swap');\r\n");
      out.write("        :root {\r\n");
      out.write("            --brand-blue: #2A9D8F;\r\n");
      out.write("            --brand-navy: #0F6BAE;\r\n");
      out.write("            --brand-green: #6DBE45;\r\n");
      out.write("            --brand-lime: #CDE11D;\r\n");
      out.write("            --brand-gold: #F2F72E;\r\n");
      out.write("            --surface: #ffffff;\r\n");
      out.write("            --line: #d4e1ec;\r\n");
      out.write("            --text: #1a3040;\r\n");
      out.write("            --muted: #5d7484;\r\n");
      out.write("        }\r\n");
      out.write("        * { box-sizing: border-box; }\r\n");
      out.write("        body { margin: 0; font-family: 'Source Sans 3', 'Trebuchet MS', sans-serif; background: linear-gradient(180deg, #eef3f8 0%, #f8fbfd 100%); color: var(--text); }\r\n");
      out.write("        .navbar { background: linear-gradient(135deg, var(--brand-navy) 0%, var(--brand-blue) 30%, var(--brand-green) 58%, var(--brand-lime) 80%, var(--brand-gold) 100%); border-bottom: 3px solid var(--brand-gold); color: white; padding: 14px 26px; display: flex; justify-content: space-between; align-items: center; gap: 20px; box-shadow: 0 12px 28px rgba(8,51,77,0.2); }\r\n");
      out.write("        .brand { display: flex; align-items: center; gap: 14px; }\r\n");
      out.write("        .brand-logo { width: 52px; height: 52px; object-fit: contain; }\r\n");
      out.write("        .brand h1 { margin: 0; font-size: 21px; letter-spacing: 0.02em; }\r\n");
      out.write("        .brand p { margin: 2px 0 0; font-size: 12px; opacity: 0.9; }\r\n");
      out.write("        .navbar a { color: white; text-decoration: none; margin-left: 10px; font-weight: 700; padding: 8px 11px; border-radius: 8px; transition: background 0.18s ease; }\r\n");
      out.write("        .navbar a:hover { background: rgba(255,255,255,0.14); }\r\n");
      out.write("        .icon-inline { width: 16px; height: 16px; object-fit: contain; vertical-align: middle; }\r\n");
      out.write("        .icon-link { width: 40px; height: 40px; display: inline-flex; align-items: center; justify-content: center; border-radius: 999px; background: rgba(255,255,255,0.15); border: 1px solid rgba(255,255,255,0.38); transition: transform 0.18s ease, background 0.18s ease; text-decoration: none; margin-left: 4px; }\r\n");
      out.write("        .icon-link img { width: 20px; height: 20px; object-fit: contain; }\r\n");
      out.write("        .icon-link:hover { transform: translateY(-1px) scale(1.03); background: rgba(255,255,255,0.26); }\r\n");
      out.write("        .container { max-width: 960px; margin: 28px auto; padding: 0 20px 40px; }\r\n");
      out.write("        .breadcrumb { font-size: 13px; color: var(--muted); margin-bottom: 16px; }\r\n");
      out.write("        .breadcrumb a { color: var(--brand-blue); text-decoration: none; }\r\n");
      out.write("        .breadcrumb a:hover { text-decoration: underline; }\r\n");
      out.write("        .card { background: var(--surface); border: 1px solid var(--line); border-radius: 14px; box-shadow: 0 8px 26px rgba(9,53,79,0.07); margin-bottom: 20px; }\r\n");
      out.write("        .card-header { padding: 16px 22px; border-bottom: 1px solid var(--line); display: flex; align-items: center; justify-content: space-between; }\r\n");
      out.write("        .card-header h2 { margin: 0; font-size: 16px; color: #0f405d; }\r\n");
      out.write("        .card-body { padding: 20px 22px; }\r\n");
      out.write("        .detail-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 14px 28px; }\r\n");
      out.write("        .detail-item label { display: block; font-size: 11px; font-weight: 700; text-transform: uppercase; letter-spacing: 0.06em; color: var(--muted); margin-bottom: 3px; }\r\n");
      out.write("        .detail-item .val { font-size: 15px; color: var(--text); word-break: break-word; }\r\n");
      out.write("        .detail-item .val-empty { color: #aab4bc; font-style: italic; }\r\n");
      out.write("        .detail-full { grid-column: 1 / -1; }\r\n");
      out.write("        .status-badge { display: inline-block; padding: 5px 14px; border-radius: 999px; font-size: 13px; font-weight: 700; }\r\n");
      out.write("        .status-new { background: #dbeafe; color: #1e40af; }\r\n");
      out.write("        .status-under_review { background: #e0f2fe; color: #0369a1; }\r\n");
      out.write("        .status-in_progress { background: #ede9fe; color: #7c3aed; }\r\n");
      out.write("        .status-approved { background: #dcfce7; color: #166534; }\r\n");
      out.write("        .status-rejected { background: #fee2e2; color: #b91c1c; }\r\n");
      out.write("        .status-suspended { background: #ffe4d6; color: #9a3412; }\r\n");
      out.write("        .status-draft { background: #e2e8f0; color: #334155; }\r\n");
      out.write("        .alert { padding: 13px 16px; border-radius: 12px; margin-bottom: 16px; font-size: 14px; }\r\n");
      out.write("        .alert-info { background: #ebf7ff; color: #16537a; border: 1px solid #cce5f5; }\r\n");
      out.write("        .alert-success { background: #dcfce7; color: #166534; border: 1px solid #bbf7d0; }\r\n");
      out.write("        .alert-warning { background: #fefce8; color: #854d0e; border: 1px solid #fde68a; }\r\n");
      out.write("        .alert-danger { background: #fee2e2; color: #b91c1c; border: 1px solid #fecaca; }\r\n");
      out.write("        .alert-icon {\r\n");
      out.write("            width: 20px;\r\n");
      out.write("            height: 20px;\r\n");
      out.write("            object-fit: contain;\r\n");
      out.write("            vertical-align: middle;\r\n");
      out.write("            margin-right: 8px;\r\n");
      out.write("        }\r\n");
      out.write("        .btn { display: inline-block; padding: 10px 18px; border-radius: 10px; font-weight: 700; font-size: 14px; text-decoration: none; cursor: pointer; border: 1px solid #fff !important; box-shadow: inset 0 0 0 1px #fff, 0 1px 2px rgba(0,0,0,0.18) !important; transition: transform 0.16s ease; }\r\n");
      out.write("        .btn:hover { transform: translateY(-1px); }\r\n");
      out.write("        .btn-primary { background: linear-gradient(180deg, var(--brand-navy) 0%, var(--brand-blue) 55%, var(--brand-green) 100%); color: white; }\r\n");
      out.write("        .btn-secondary { background: #e2edf5; color: var(--brand-navy); }\r\n");
      out.write("        .btn-green { background: linear-gradient(180deg,#16a34a 0%,#15803d 100%); color: white; }\r\n");
      out.write("        .doc-list { list-style: none; margin: 0; padding: 0; }\r\n");
      out.write("        .doc-item { display: flex; align-items: center; justify-content: space-between; padding: 9px 0; border-bottom: 1px solid #f0f5f9; font-size: 14px; }\r\n");
      out.write("        .doc-item:last-child { border-bottom: none; }\r\n");
      out.write("        .doc-name { color: var(--text); }\r\n");
      out.write("        .doc-meta { color: var(--muted); font-size: 12px; margin-top: 2px; }\r\n");
      out.write("        .doc-missing { color: #aab4bc; font-style: italic; }\r\n");
      out.write("        .page-title { font-size: 26px; font-weight: 800; color: var(--brand-navy); margin: 0 0 4px; }\r\n");
      out.write("        .page-sub { color: var(--muted); font-size: 14px; margin-bottom: 20px; }\r\n");
      out.write("        @media (max-width: 700px) { .detail-grid { grid-template-columns: 1fr; } .detail-full { grid-column: 1; } }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"navbar\">\r\n");
      out.write("    <div class=\"brand\">\r\n");
      out.write("        <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/images/sabah-logo.png\" class=\"brand-logo\" alt=\"Logo Sabah\">\r\n");
      out.write("        <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/images/logo-jabatan-air-sabah.png?v=4\" class=\"brand-logo\" alt=\"Logo JAS\">\r\n");
      out.write("        <div>\r\n");
      out.write("            <h1>Butiran Permohonan</h1>\r\n");
      out.write("            <p>Sistem Pendaftaran Pembekal dan Produk Air - Jabatan Air Negeri Sabah</p>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div style=\"display:flex;align-items:center;\">\r\n");
      out.write("        <a class=\"icon-link\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/dashboard\" title=\"Dashboard\" aria-label=\"Dashboard\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/icon/dashboard.png\" alt=\"Dashboard\"></a>\r\n");
      out.write("        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/profile\">Profil</a>\r\n");
      out.write("        <a class=\"icon-link\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/\" title=\"Laman Utama\" aria-label=\"Laman Utama\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/images/home.png\" alt=\"Home\"></a>\r\n");
      out.write("        <a class=\"icon-link\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/logout\" title=\"Log Keluar\" aria-label=\"Log Keluar\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/images/Logout.png\" alt=\"Log Keluar\"></a>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("    <div class=\"breadcrumb\">\r\n");
      out.write("        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/dashboard\">Dashboard</a> &rsaquo; Permohonan ");
      out.print( appIdFormatted );
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"page-title\">Permohonan ");
      out.print( appIdFormatted );
      out.write("</div>\r\n");
      out.write("    <div class=\"page-sub\">\r\n");
      out.write("        ");
      out.print( app.get("product_name") );
      out.write("\r\n");
      out.write("        &mdash;\r\n");
      out.write("        <span class=\"status-badge status-");
      out.print( statusCssClass(status) );
      out.write('"');
      out.write('>');
      out.print( statusDisplay );
      out.write("</span>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    ");
 if (showUpdatedNotice) { 
      out.write("\r\n");
      out.write("    <div class=\"alert alert-success\">\r\n");
      out.write("        <img class=\"alert-icon\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/images/success.png\" alt=\"Berjaya\">\r\n");
      out.write("        <strong>Permohonan berjaya dikemaskini.</strong>\r\n");
      out.write("    </div>\r\n");
      out.write("    ");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("    ");
 if ("APPROVED".equals(status) && certNum != null) { 
      out.write("\r\n");
      out.write("    <div class=\"alert alert-success\">\r\n");
      out.write("        Permohonan ini telah <strong>diluluskan</strong>. No. Perakuan: <strong>");
      out.print( certNum );
      out.write("</strong>.\r\n");
      out.write("        Sah sehingga: <strong>");
      out.print( app.get("valid_until") );
      out.write("</strong>.\r\n");
      out.write("        <a class=\"btn btn-green\" style=\"margin-left:12px;padding:6px 14px;font-size:13px;\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/certificate?id=");
      out.print( appId );
      out.write("\" target=\"_blank\">Lihat Perakuan</a>\r\n");
      out.write("    </div>\r\n");
      out.write("    ");
 } else if ("APPROVED".equals(status)) { 
      out.write("\r\n");
      out.write("    <div class=\"alert alert-success\">Permohonan ini telah <strong>diluluskan</strong>.</div>\r\n");
      out.write("    ");
 } else if ("REJECTED".equals(status)) { 
      out.write("\r\n");
      out.write("    <div class=\"alert alert-danger\">Permohonan ini telah <strong>ditolak</strong>.\r\n");
      out.write("        ");
 String notes = app.get("admin_notes") == null ? "" : String.valueOf(app.get("admin_notes")); if (!notes.isBlank()) { 
      out.write("\r\n");
      out.write("        Sebab: ");
      out.print( notes );
      out.write("\r\n");
      out.write("        ");
 } 
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("    ");
 } else if ("SUSPENDED".equals(status)) { 
      out.write("\r\n");
      out.write("        <div class=\"alert alert-warning\">Permohonan ini sedang <strong>digantung</strong>.</div>\r\n");
      out.write("    ");
 } else if ("NEW".equals(status)) { 
      out.write("\r\n");
      out.write("        <div class=\"alert alert-info\">Permohonan baru telah dihantar. Anda akan dimaklumkan apabila terdapat keputusan.</div>\r\n");
      out.write("    ");
 } else if ("UNDER_REVIEW".equals(status)) { 
      out.write("\r\n");
      out.write("        <div class=\"alert alert-info\">Permohonan sedang dalam <strong>semakan</strong>.</div>\r\n");
      out.write("    ");
 } else if ("IN_PROGRESS".equals(status)) { 
      out.write("\r\n");
      out.write("        <div class=\"alert alert-info\">Permohonan sedang <strong>diproses</strong>.</div>\r\n");
      out.write("    ");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("    <div class=\"card\">\r\n");
      out.write("        <div class=\"card-header\">\r\n");
      out.write("            <h2>Maklumat Permohonan</h2>\r\n");
      out.write("                <span style=\"font-size:13px;color:var(--muted);\">Dihantar: ");
      out.print( app.get("submitted_at") != null ? String.valueOf(app.get("submitted_at")).substring(0,19) : "Belum dihantar" );
      out.write("</span>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"card-body\">\r\n");
      out.write("            <div class=\"detail-grid\">\r\n");
      out.write("                <div class=\"detail-item\">\r\n");
      out.write("                    <label>Jenis Permohonan</label>\r\n");
      out.write("                    <div class=\"val\">");
      out.print( app.get("application_type") != null ? app.get("application_type") : "<span class='val-empty'>-</span>" );
      out.write("</div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"detail-item\">\r\n");
      out.write("                    <label>Nama Produk</label>\r\n");
      out.write("                    <div class=\"val\">");
      out.print( app.get("product_name") != null ? app.get("product_name") : "<span class='val-empty'>-</span>" );
      out.write("</div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"detail-item\">\r\n");
      out.write("                    <label>Kategori Produk</label>\r\n");
      out.write("                    <div class=\"val\">");
      out.print( app.get("product_category") != null ? app.get("product_category") : "<span class='val-empty'>-</span>" );
      out.write("</div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"detail-item\">\r\n");
      out.write("                    <label>Status</label>\r\n");
      out.write("                    <div class=\"val\"><span class=\"status-badge status-");
      out.print( statusCssClass(status) );
      out.write('"');
      out.write('>');
      out.print( statusDisplay );
      out.write("</span></div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"detail-item detail-full\">\r\n");
      out.write("                    <label>Perihal Produk / Ringkasan</label>\r\n");
      out.write("                    <div class=\"val\" style=\"white-space:pre-wrap;\">");
      out.print( app.get("product_description") != null ? app.get("product_description") : "<span class='val-empty'>-</span>" );
      out.write("</div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("    <div class=\"card\">\r\n");
      out.write("        <div class=\"card-header\"><h2>Maklumat Pembekal</h2></div>\r\n");
      out.write("        <div class=\"card-body\">\r\n");
      out.write("            <div class=\"detail-grid\">\r\n");
      out.write("                <div class=\"detail-item\">\r\n");
      out.write("                    <label>Nama Syarikat / Pembekal</label>\r\n");
      out.write("                    <div class=\"val\">");
      out.print( app.get("supplier_name") != null ? app.get("supplier_name") : (app.get("company_name") != null ? app.get("company_name") : "<span class='val-empty'>-</span>") );
      out.write("</div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"detail-item\">\r\n");
      out.write("                    <label>No. Telefon</label>\r\n");
      out.write("                    <div class=\"val\">");
      out.print( app.get("supplier_phone") != null ? app.get("supplier_phone") : (app.get("contact_number") != null ? app.get("contact_number") : "<span class='val-empty'>-</span>") );
      out.write("</div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"detail-item detail-full\">\r\n");
      out.write("                    <label>Alamat</label>\r\n");
      out.write("                    <div class=\"val\" style=\"white-space:pre-wrap;\">");
      out.print( app.get("supplier_address") != null ? app.get("supplier_address") : (app.get("company_address") != null ? app.get("company_address") : "<span class='val-empty'>-</span>") );
      out.write("</div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("    ");
 boolean hasMfr = app.get("manufacturer_name") != null && !String.valueOf(app.get("manufacturer_name")).isBlank(); 
      out.write("\r\n");
      out.write("    ");
 if (hasMfr) { 
      out.write("\r\n");
      out.write("    <div class=\"card\">\r\n");
      out.write("        <div class=\"card-header\"><h2>Maklumat Pengilang</h2></div>\r\n");
      out.write("        <div class=\"card-body\">\r\n");
      out.write("            <div class=\"detail-grid\">\r\n");
      out.write("                <div class=\"detail-item\">\r\n");
      out.write("                    <label>Nama Pengilang</label>\r\n");
      out.write("                    <div class=\"val\">");
      out.print( app.get("manufacturer_name") );
      out.write("</div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"detail-item\">\r\n");
      out.write("                    <label>No. Telefon</label>\r\n");
      out.write("                    <div class=\"val\">");
      out.print( app.get("manufacturer_phone") != null ? app.get("manufacturer_phone") : "<span class='val-empty'>-</span>" );
      out.write("</div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"detail-item detail-full\">\r\n");
      out.write("                    <label>Alamat Pengilang</label>\r\n");
      out.write("                    <div class=\"val\" style=\"white-space:pre-wrap;\">");
      out.print( app.get("manufacturer_address") != null ? app.get("manufacturer_address") : "<span class='val-empty'>-</span>" );
      out.write("</div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    ");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("    <div class=\"card\">\r\n");
      out.write("        <div class=\"card-header\"><h2>Persijilan &amp; Standard</h2></div>\r\n");
      out.write("        <div class=\"card-body\">\r\n");
      out.write("            <div class=\"detail-grid\">\r\n");
      out.write("                <div class=\"detail-item\">\r\n");
      out.write("                    <label>Nama Standard</label>\r\n");
      out.write("                    <div class=\"val\">");
      out.print( app.get("standard_name") != null ? app.get("standard_name") : "<span class='val-empty'>-</span>" );
      out.write("</div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"detail-item\">\r\n");
      out.write("                    <label>No. Lesen / Persijilan</label>\r\n");
      out.write("                    <div class=\"val\">");
      out.print( app.get("certification_license") != null ? app.get("certification_license") : "<span class='val-empty'>-</span>" );
      out.write("</div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"detail-item\">\r\n");
      out.write("                    <label>Tarikh Tamat Lesen</label>\r\n");
      out.write("                    <div class=\"val\">");
      out.print( app.get("certification_valid_until") != null ? app.get("certification_valid_until") : "<span class='val-empty'>-</span>" );
      out.write("</div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"detail-item\">\r\n");
      out.write("                    <label>Jaminan (Tahun)</label>\r\n");
      out.write("                    <div class=\"val\">");
      out.print( app.get("warranty_years") != null ? app.get("warranty_years") : "<span class='val-empty'>-</span>" );
      out.write("</div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"detail-item\">\r\n");
      out.write("                    <label>No. Rujukan Laporan Ujian</label>\r\n");
      out.write("                    <div class=\"val\">");
      out.print( app.get("test_report_reference") != null ? app.get("test_report_reference") : "<span class='val-empty'>-</span>" );
      out.write("</div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"detail-item\">\r\n");
      out.write("                    <label>Tarikh Laporan Ujian</label>\r\n");
      out.write("                    <div class=\"val\">");
      out.print( app.get("test_report_date") != null ? app.get("test_report_date") : "<span class='val-empty'>-</span>" );
      out.write("</div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("    ");
 boolean hasRep = app.get("sabah_rep_name") != null && !String.valueOf(app.get("sabah_rep_name")).isBlank(); 
      out.write("\r\n");
      out.write("    ");
 if (hasRep) { 
      out.write("\r\n");
      out.write("    <div class=\"card\">\r\n");
      out.write("        <div class=\"card-header\"><h2>Wakil di Sabah</h2></div>\r\n");
      out.write("        <div class=\"card-body\">\r\n");
      out.write("            <div class=\"detail-grid\">\r\n");
      out.write("                <div class=\"detail-item\">\r\n");
      out.write("                    <label>Nama Wakil</label>\r\n");
      out.write("                    <div class=\"val\">");
      out.print( app.get("sabah_rep_name") );
      out.write("</div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"detail-item\">\r\n");
      out.write("                    <label>No. Telefon</label>\r\n");
      out.write("                    <div class=\"val\">");
      out.print( app.get("sabah_rep_phone") != null ? app.get("sabah_rep_phone") : "<span class='val-empty'>-</span>" );
      out.write("</div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"detail-item detail-full\">\r\n");
      out.write("                    <label>Alamat</label>\r\n");
      out.write("                    <div class=\"val\" style=\"white-space:pre-wrap;\">");
      out.print( app.get("sabah_rep_address") != null ? app.get("sabah_rep_address") : "<span class='val-empty'>-</span>" );
      out.write("</div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    ");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("    <div class=\"card\">\r\n");
      out.write("        <div class=\"card-header\"><h2>Dokumen Dimuat Naik</h2></div>\r\n");
      out.write("        <div class=\"card-body\">\r\n");
      out.write("            ");
 if (documents == null || documents.isEmpty()) { 
      out.write("\r\n");
      out.write("                <p style=\"color:var(--muted);font-style:italic;\">Tiada dokumen dimuat naik.</p>\r\n");
      out.write("            ");
 } else { 
      out.write("\r\n");
      out.write("            <ul class=\"doc-list\">\r\n");
      out.write("                ");
 for (Map<String, Object> doc : documents) {
                    String docType = String.valueOf(doc.get("document_type"));
                    String label = requiredDocuments != null && requiredDocuments.containsKey(docType) ? requiredDocuments.get(docType) : docType;
                    long fileSize = (Long) doc.get("file_size");
                    String sizeStr = fileSize > 1024 * 1024 ? String.format("%.1f MB", fileSize / 1048576.0) : String.format("%.0f KB", fileSize / 1024.0);
                    int docId = (Integer) doc.get("id");
                
      out.write("\r\n");
      out.write("                <li class=\"doc-item\">\r\n");
      out.write("                    <div>\r\n");
      out.write("                        <div class=\"doc-name\">");
      out.print( label );
      out.write("</div>\r\n");
      out.write("                        <div class=\"doc-meta\">");
      out.print( doc.get("original_filename") );
      out.write(" &mdash; ");
      out.print( sizeStr );
      out.write("</div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/documents/download?id=");
      out.print( docId );
      out.write("\" class=\"btn btn-secondary\" style=\"padding:6px 12px;font-size:12px;\">Muat Turun</a>\r\n");
      out.write("                </li>\r\n");
      out.write("                ");
 } 
      out.write("\r\n");
      out.write("            </ul>\r\n");
      out.write("            ");
 } 
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("    ");
 String adminNotes = app.get("admin_notes") == null ? "" : String.valueOf(app.get("admin_notes")); 
      out.write("\r\n");
      out.write("    ");
 if (!adminNotes.isBlank()) { 
      out.write("\r\n");
      out.write("    <div class=\"card\">\r\n");
      out.write("        <div class=\"card-header\"><h2>Nota Pentadbir</h2></div>\r\n");
      out.write("        <div class=\"card-body\" style=\"white-space:pre-wrap;\">");
      out.print( adminNotes );
      out.write("</div>\r\n");
      out.write("    </div>\r\n");
      out.write("    ");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <div style=\"display:flex;gap:12px;margin-top:8px;\">\r\n");
      out.write("        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/dashboard\" class=\"btn btn-secondary\" title=\"Kembali ke Dashboard\" aria-label=\"Kembali ke Dashboard\"><img class=\"icon-inline\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/icon/dashboard.png\" alt=\"Dashboard\"></a>\r\n");
      out.write("        ");
 if ("DRAFT".equals(status) || "NEW".equals(status) || "UNDER_REVIEW".equals(status) || "IN_PROGRESS".equals(status) || "REJECTED".equals(status)) { 
      out.write("\r\n");
      out.write("        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/applications/");
      out.print( appId );
      out.write("/edit\" class=\"btn btn-primary\">Kemaskini Permohonan</a>\r\n");
      out.write("        ");
 } 
      out.write("\r\n");
      out.write("        ");
 if ("APPROVED".equals(status) && certNum != null) { 
      out.write("\r\n");
      out.write("        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/certificate?id=");
      out.print( appId );
      out.write("\" class=\"btn btn-green\" target=\"_blank\">Lihat Perakuan</a>\r\n");
      out.write("        ");
 } 
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
